"""Generate migration 104: ~330 more example sentences to reach 2000 total.
Current: L1:492, L2:425, L3:201, L4:164, L5:154, L6:235 = 1671
Target distribution: L1:492, L2:425, L3:280, L4:260, L5:260, L6:283 = 2000
Need: L3:+79, L4:+96, L5:+106, L6:+48 = +329
"""

EXAMPLES = []

def _ex(wid, he, ru, tr, lvl):
    EXAMPLES.append((wid, he, ru, tr, None, lvl))

# ============ L3: +79 examples (word IDs from 1316-4111) ============

_ex(1350, "אנחנו צריכים לדבר על זה", "Нам нужно поговорить об этом", "anakhnu tzrikhim ledaber al ze", 3)
_ex(1380, "היא עובדת בבית חולים גדול", "Она работает в большой больнице", "hi ovedet be-beit kholim gadol", 3)
_ex(1420, "הילדים משחקים בגן הציבורי", "Дети играют в общественном парке", "ha-yeladim mesakhakim ba-gan ha-tziburi", 3)
_ex(1460, "אני לא יכול לבוא מחר בבוקר", "Я не могу прийти завтра утром", "ani lo yakhol lavo makhar ba-boker", 3)
_ex(1500, "הוא למד עברית שלוש שנים", "Он учил иврит три года", "hu lamad ivrit shalosh shanim", 3)
_ex(1540, "המסעדה הזאת פתוחה כל יום", "Этот ресторан открыт каждый день", "ha-mis'ada ha-zot ptukha kol yom", 3)
_ex(1580, "אנחנו גרים בדירה קטנה בתל אביב", "Мы живём в маленькой квартире в Тель-Авиве", "anakhnu garim be-dira ktana be-tel aviv", 3)
_ex(1620, "האוטובוס מגיע בעוד עשר דקות", "Автобус приедет через десять минут", "ha-otobus magia be-od eser dakot", 3)
_ex(1660, "היא קנתה שמלה חדשה לחתונה", "Она купила новое платье на свадьбу", "hi kanta simla khadasha la-khatuna", 3)
_ex(1700, "אנחנו צריכים לקנות ירקות ופירות", "Нам нужно купить овощи и фрукты", "anakhnu tzrikhim liknot yerakot u-perot", 3)
_ex(1740, "הרופא אמר שצריך לנוח יותר", "Врач сказал, что нужно больше отдыхать", "ha-rofe amar she-tzarikh lanuakh yoter", 3)
_ex(1780, "הסרט הזה מאוד מעניין ומרגש", "Этот фильм очень интересный и волнующий", "ha-seret ha-ze me'od me'anyen u-mergesh", 3)
_ex(1820, "היא מדברת שלוש שפות בשטף", "Она бегло говорит на трёх языках", "hi medaberet shalosh safot be-shetef", 3)
_ex(1860, "אנחנו נפגשים בכל שבוע ביום שלישי", "Мы встречаемся каждую неделю во вторник", "anakhnu nifgashim be-khol shavua be-yom shlishi", 3)
_ex(1900, "הוא עובד מהבית כבר שנה", "Он работает из дома уже год", "hu oved me-ha-bayit kvar shana", 3)
_ex(1940, "הבית שלנו נמצא ליד הים", "Наш дом находится у моря", "ha-bayit shelanu nimtza leyad ha-yam", 3)
_ex(1980, "הם חזרו מחופשה בחוץ לארץ", "Они вернулись из отпуска за границей", "hem khazru me-khufsha be-khutz la-aretz", 3)
_ex(2020, "את יכולה לעזור לי עם זה?", "Ты можешь мне с этим помочь?", "at yekhola la'azor li im ze?", 3)
_ex(2060, "הדודה שלי גרה בחיפה", "Моя тётя живёт в Хайфе", "ha-doda sheli gara be-kheifa", 3)
_ex(2100, "השמש שוקעת מוקדם בחורף", "Солнце заходит рано зимой", "ha-shemesh shoka'at mukdam ba-khoref", 3)
_ex(2140, "הם בנו בית חדש בכפר", "Они построили новый дом в деревне", "hem banu bayit khadash ba-kfar", 3)
_ex(2180, "המורה הסבירה את השיעור בבהירות", "Учительница ясно объяснила урок", "ha-mora hisbira et ha-shi'ur be-behirut", 3)
_ex(2220, "הוא רוצה לטייל בכל העולם", "Он хочет путешествовать по всему миру", "hu rotze letayel be-khol ha-olam", 3)
_ex(2260, "אנחנו אוכלים ארוחת ערב ביחד", "Мы ужинаем вместе", "anakhnu okhlim arukhat erev beyakhad", 3)
_ex(2300, "המשרד פתוח מתשע עד חמש", "Офис открыт с девяти до пяти", "ha-misrad patuakh me-tesha ad khamesh", 3)
_ex(2340, "היא שרה שיר יפה בהופעה", "Она спела красивую песню на концерте", "hi shara shir yafe ba-hofa'a", 3)
_ex(2380, "הגשם ירד כל היום אתמול", "Дождь шёл весь день вчера", "ha-geshem yarad kol ha-yom etmol", 3)
_ex(2420, "אנחנו מתכננים לנסוע לאילת", "Мы планируем поехать в Эйлат", "anakhnu metakhnanim linso'a le-eilat", 3)
_ex(2460, "הספרייה העירונית פתוחה גם בשבת", "Городская библиотека открыта и в субботу", "ha-sifriya ha-ironit ptukha gam be-shabat", 3)
_ex(2500, "הוא הזמין שולחן במסעדה לערב", "Он заказал столик в ресторане на вечер", "hu hizmin shulkhan ba-mis'ada la-erev", 3)
_ex(2550, "השכנים שלנו מאוד נחמדים", "Наши соседи очень приятные", "ha-shkhenim shelanu me'od nekhmadim", 3)
_ex(2600, "אני צריך ללכת לרופא שיניים", "Мне нужно пойти к стоматологу", "ani tzarikh lalekhet le-rofe shinayim", 3)
_ex(2650, "המחשב שלי לא עובד כמו שצריך", "Мой компьютер не работает как надо", "ha-makhshev sheli lo oved kmo she-tzarikh", 3)
_ex(2700, "היא סיימה את הלימודים בהצלחה", "Она успешно закончила учёбу", "hi siyma et ha-limudim be-hatzlakha", 3)
_ex(2750, "הילד הזה חכם מאוד לגילו", "Этот ребёнок очень умный для своего возраста", "ha-yeled ha-ze khakham me'od le-gilo", 3)
_ex(2800, "אנחנו צריכים לשלם את החשבון", "Нам нужно оплатить счёт", "anakhnu tzrikhim leshalem et ha-kheshbon", 3)
_ex(2850, "המוזיקה הישראלית מגוונת מאוד", "Израильская музыка очень разнообразна", "ha-muzika ha-yisraelit meguvenet me'od", 3)
_ex(2900, "הוא שיחק כדורגל כל ילדותו", "Он играл в футбол всё детство", "hu sikhek kaduregel kol yalduto", 3)
_ex(2950, "השוק בירושלים מלא צבעים וריחות", "Рынок в Иерусалиме полон красок и запахов", "ha-shuk bi-yerushalayim male tzva'im ve-reikhot", 3)
_ex(3000, "היא לומדת לתואר שני באוניברסיטה", "Она учится на магистратуре в университете", "hi lomedet le-to'ar sheni ba-universita", 3)
_ex(3050, "הם עברו לגור בשכונה חדשה", "Они переехали жить в новый район", "hem avru lagur bi-shkhuna khadasha", 3)
_ex(3100, "האוכל במסעדה הזאת מצוין", "Еда в этом ресторане отличная", "ha-okhel ba-mis'ada ha-zot metzuyan", 3)
_ex(3150, "אני שומע מוזיקה כשאני נוסע באוטו", "Я слушаю музыку, когда еду в машине", "ani shome'a muzika kshe-ani nose'a ba-oto", 3)
_ex(3200, "הוא קיבל מלגה ללימודים", "Он получил стипендию на учёбу", "hu kibel milga la-limudim", 3)
_ex(3250, "הפרחים בגינה פורחים באביב", "Цветы в саду расцветают весной", "ha-prakhim ba-gina porkhim ba-aviv", 3)
_ex(3300, "היא עשתה עוגה ליום ההולדת", "Она испекла торт на день рождения", "hi asta uga le-yom ha-huledet", 3)
_ex(3350, "אנחנו מטיילים בגליל כל קיץ", "Мы путешествуем по Галилее каждое лето", "anakhnu metaylim ba-galil kol kayitz", 3)
_ex(3400, "הבנק סגור ביום שישי אחר הצהריים", "Банк закрыт в пятницу днём", "ha-bank sagur be-yom shishi akhar ha-tzohorayim", 3)
_ex(3450, "הוא עזר לה לשאת את השקיות", "Он помог ей нести сумки", "hu azar la las'et et ha-sakiyot", 3)
_ex(3500, "המשפחה שלנו מתכנסת בחגים", "Наша семья собирается по праздникам", "ha-mishpakha shelanu mitkaneset ba-khagim", 3)
_ex(3550, "היא מכינה ארוחת בוקר כל יום", "Она готовит завтрак каждый день", "hi mekhina arukhat boker kol yom", 3)
_ex(3600, "הכביש הראשי סגור לתנועה", "Главная дорога закрыта для движения", "ha-kvish ha-rashi sagur li-tnu'a", 3)
_ex(3650, "אנחנו שמחים שבאתם לביקור", "Мы рады, что вы пришли в гости", "anakhnu smekhim she-batem le-bikur", 3)
_ex(3700, "הטלפון שלי צריך טעינה", "Мой телефон нужно зарядить", "ha-telefon sheli tzarikh te'ina", 3)
_ex(3750, "הוא נהג מונית עשרים שנה", "Он водил такси двадцать лет", "hu nahag monit esrim shana", 3)
_ex(3800, "המכתב הגיע בדואר היום", "Письмо пришло по почте сегодня", "ha-mikhtav higia ba-do'ar ha-yom", 3)
_ex(3850, "היא צילמה את הנוף מהמרפסת", "Она сфотографировала вид с балкона", "hi tzilma et ha-nof me-ha-mirpeset", 3)
_ex(3900, "השעון שלי מקדים בחמש דקות", "Мои часы спешат на пять минут", "ha-sha'on sheli makdim be-khamesh dakot", 3)
_ex(3950, "הם הזמינו אורחים לשבת", "Они пригласили гостей на субботу", "hem hizminu orkhim le-shabat", 3)
_ex(4000, "האופניים שלו נגנבו מהחניון", "Его велосипед украли с парковки", "ha-ofanayim shelo nignvu me-ha-khanyon", 3)
_ex(4050, "הילדה כתבה מכתב לסבתא", "Девочка написала письмо бабушке", "ha-yalda katva mikhtav la-savta", 3)
_ex(1330, "בבקשה תסגור את הדלת", "Пожалуйста, закрой дверь", "be-vakasha tisgor et ha-delet", 3)
_ex(1370, "מתי נפגשים מחר?", "Когда встречаемся завтра?", "matay nifgashim makhar?", 3)
_ex(1410, "אני מרגיש טוב היום", "Я чувствую себя хорошо сегодня", "ani margish tov ha-yom", 3)
_ex(1450, "הם הלכו לים בסוף השבוע", "Они ходили на море в выходные", "hem halkhu la-yam be-sof ha-shavua", 3)
_ex(1490, "הסיפור הזה נשמע מוזר", "Эта история звучит странно", "ha-sipur ha-ze nishma muzar", 3)
_ex(1530, "אנחנו חוגגים יום הולדת הערב", "Мы празднуем день рождения сегодня вечером", "anakhnu khogegim yom huledet ha-erev", 3)
_ex(1570, "הוא הבטיח לחזור מוקדם", "Он обещал вернуться рано", "hu hivtiakh lakhzor mukdam", 3)
_ex(1610, "התינוק ישן כל הלילה", "Малыш спал всю ночь", "ha-tinok yashan kol ha-layla", 3)
_ex(1650, "היא שכחה את הארנק בבית", "Она забыла кошелёк дома", "hi shakhkha et ha-arnak ba-bayit", 3)
_ex(1690, "הרכבת מאחרת בעשרים דקות", "Поезд опаздывает на двадцать минут", "ha-rakevet me'akheret be-esrim dakot", 3)
_ex(1730, "אנחנו גמרנו את כל האוכל", "Мы съели всю еду", "anakhnu gamarna et kol ha-okhel", 3)
_ex(1770, "הקפה פה מצוין", "Кофе здесь отличный", "ha-kafe po metzuyan", 3)
_ex(1810, "היא רצה מרתון בפעם הראשונה", "Она пробежала марафон впервые", "hi ratza maraton ba-pa'am ha-rishona", 3)
_ex(1850, "הם קנו דירה חדשה בראשון לציון", "Они купили новую квартиру в Ришон-ле-Ционе", "hem kanu dira khadasha be-rishon le-tziyon", 3)
_ex(1890, "אני לא אוהב לקום מוקדם", "Я не люблю вставать рано", "ani lo ohev lakum mukdam", 3)
_ex(1930, "הילד למד לרכוב על אופניים", "Ребёнок научился ездить на велосипеде", "ha-yeled lamad lirkov al ofanayim", 3)
_ex(1970, "חם מאוד בקיץ בישראל", "Летом в Израиле очень жарко", "kham me'od ba-kayitz be-yisrael", 3)
_ex(2010, "הסופרמרקט פתוח עד מאוחר", "Супермаркет открыт допоздна", "ha-supermarket patuakh ad me'ukhar", 3)

# ============ L4: +96 examples (word IDs from 1416-5515) ============

_ex(1450, "הממשלה אישרה את התקציב החדש", "Правительство утвердило новый бюджет", "ha-memshala ishra et ha-taktziv he-khadash", 4)
_ex(1520, "המשפט התנהל בבית המשפט המחוזי", "Суд проходил в окружном суде", "ha-mishpat hitnahel be-beit ha-mishpat ha-mekhozi", 4)
_ex(1590, "הכתבה חשפה שחיתות בממשלה", "Репортаж раскрыл коррупцию в правительстве", "ha-katava khasfa shkhitut ba-memshala", 4)
_ex(1660, "הפסיכולוג ניתח את התנהגות המטופל", "Психолог проанализировал поведение пациента", "ha-psikholog nitakh et hitnagut ha-metupal", 4)
_ex(1730, "הביוגרפיה מתארת את חייו של המנהיג", "Биография описывает жизнь лидера", "ha-biographia meta'eret et khayav shel ha-manhig", 4)
_ex(1800, "הרפורמה החינוכית יצרה מחלוקת", "Образовательная реформа вызвала разногласия", "ha-reforma ha-khinukhit yatzra makhloket", 4)
_ex(1870, "הבנק המרכזי פרסם דוח שנתי", "Центральный банк опубликовал годовой отчёт", "ha-bank ha-merkazi pirsem do'akh shnati", 4)
_ex(1940, "הצבא ביצע תרגיל בצפון הארץ", "Армия провела учения на севере страны", "ha-tzava bitze'a targil bi-tzfon ha-aretz", 4)
_ex(2010, "המחקר הוכיח קשר בין עישון לסרטן", "Исследование доказало связь между курением и раком", "ha-mekhkar hokhiakh kesher bein ishun le-sartan", 4)
_ex(2080, "הניסוי הצליח מעבר לציפיות", "Эксперимент удался сверх ожиданий", "ha-nisayon hitzsliakh me'ever la-tzipiyot", 4)
_ex(2150, "ההסכם נחתם בטקס רשמי", "Соглашение подписано на официальной церемонии", "ha-heskem nekhtam be-tekes rishmi", 4)
_ex(2220, "השוק הנדל\"ני חווה עלייה חדה", "Рынок недвижимости пережил резкий рост", "ha-shuk ha-nadlani khava aliya khada", 4)
_ex(2290, "הדילמה המוסרית העסיקה את הציבור", "Моральная дилемма занимала общество", "ha-dilema ha-musarit he'esika et ha-tzibur", 4)
_ex(2360, "התקשורת סיקרה את האירוע בהרחבה", "СМИ широко осветили событие", "ha-tikshoret sikra et ha-iru'a be-harkhava", 4)
_ex(2430, "הנציגות הדיפלומטית התערבה בסכסוך", "Дипломатическое представительство вмешалось в конфликт", "ha-natzigut ha-diplomatit hit'arva ba-sikhsukh", 4)
_ex(2500, "הפרויקט הושלם במסגרת התקציב", "Проект завершён в рамках бюджета", "ha-proyekt hushlam be-misgeret ha-taktziv", 4)
_ex(2570, "החוקר פרסם מאמר בכתב עת בינלאומי", "Учёный опубликовал статью в международном журнале", "ha-khoker pirsem ma'amar be-ktav et bein-leumi", 4)
_ex(2640, "הוועדה המליצה על שינויים בחוק", "Комиссия рекомендовала изменения в законе", "ha-va'ada himlitza al shinuyim ba-khok", 4)
_ex(2710, "האוניברסיטה הציעה תכנית לימודים חדשה", "Университет предложил новую учебную программу", "ha-universita hetzi'a tokhnit limudim khadasha", 4)
_ex(2780, "ההפגנה התקיימה מול בניין העירייה", "Демонстрация прошла перед зданием муниципалитета", "ha-hafgana hitkayma mul binyan ha-iriya", 4)
_ex(2850, "הכלכלן חזה האטה בצמיחה", "Экономист предсказал замедление роста", "ha-kalkalan khaza ha'ata ba-tzmiha", 4)
_ex(2920, "הרפורמה הבריאותית עוררה ויכוח ער", "Реформа здравоохранения вызвала оживлённый спор", "ha-reforma ha-bri'utit orera vikuakh er", 4)
_ex(2990, "הסופר קיבל פרס ספרותי יוקרתי", "Писатель получил престижную литературную премию", "ha-sofer kibel pras sifruti yokrati", 4)
_ex(3060, "ההשקעה בחינוך מחזירה את עצמה", "Инвестиции в образование окупаются", "ha-hashka'a be-khinukh makhzira et atzma", 4)
_ex(3130, "הטכנולוגיה שינתה את שוק העבודה", "Технология изменила рынок труда", "ha-tekhnologia shinta et shuk ha-avoda", 4)
_ex(3200, "המשרד הוציא הנחיות חדשות", "Министерство выпустило новые директивы", "ha-misrad hotzi hanhayot khadashot", 4)
_ex(3270, "הסקר הראה שינוי במגמה", "Опрос показал смену тенденции", "ha-seker her'a shinui ba-megama", 4)
_ex(3340, "התביעה הוגשה בבית המשפט", "Иск подан в суд", "ha-tvi'a hugsha be-beit ha-mishpat", 4)
_ex(3410, "הממשלה הכריזה על מצב חירום", "Правительство объявило чрезвычайное положение", "ha-memshala hikhriza al matzav kherum", 4)
_ex(3480, "הפרלמנט דן בהצעת חוק חדשה", "Парламент обсуждал новый законопроект", "ha-parlament dan be-hatza'at khok khadasha", 4)
_ex(3550, "האקדמיה קבעה כללי כתיב חדשים", "Академия установила новые правила правописания", "ha-akademia kav'a klalei ktiv khadashim", 4)
_ex(3620, "הארכיאולוג גילה ממצא היסטורי חשוב", "Археолог обнаружил важную историческую находку", "ha-arkhiolog gila mimtza histori khashuv", 4)
_ex(3690, "המגפה השפיעה על הכלכלה העולמית", "Пандемия повлияла на мировую экономику", "ha-magefa hishpi'a al ha-kalkala ha-olamit", 4)
_ex(3760, "הנשיא נפגש עם ראש הממשלה", "Президент встретился с премьер-министром", "ha-nasi nifgash im rosh ha-memshala", 4)
_ex(3830, "הנתונים מצביעים על מגמה חיובית", "Данные указывают на положительную тенденцию", "ha-netunim matzbi'im al megama khiyuvit", 4)
_ex(3900, "העיתונאי חקר את הפרשה לעומק", "Журналист глубоко расследовал дело", "ha-itonay khakar et ha-parasha le-omek", 4)
_ex(3970, "הוועדה פרסמה את מסקנותיה", "Комиссия опубликовала свои выводы", "ha-va'ada pirsema et maskanoteiha", 4)
_ex(4040, "הבחירות יתקיימו בחודש הבא", "Выборы состоятся в следующем месяце", "ha-bkhirot yitkaymu ba-khodesh ha-ba", 4)
_ex(4110, "האופוזיציה מתחה ביקורת על הממשלה", "Оппозиция критиковала правительство", "ha-opozitzya matkha bikoret al ha-memshala", 4)
_ex(4180, "ההסכם הכלכלי ייכנס לתוקף בינואר", "Экономическое соглашение вступит в силу в январе", "ha-heskem ha-kalkali yikanes le-tokef be-yanuar", 4)
_ex(4250, "המומחים הזהירו מפני סיכונים", "Эксперты предупредили о рисках", "ha-mumkhim hizhiru mi-pnei sikunim", 4)
_ex(4320, "החברה הודיעה על פיטורים המוניים", "Компания объявила о массовых увольнениях", "ha-khevra hodi'a al piturim hamoni'im", 4)
_ex(4390, "השופט פסל את הראיה", "Судья отклонил доказательство", "ha-shofet pasal et ha-re'aya", 4)
_ex(4460, "הפרופסור הרצה בפני הסטודנטים", "Профессор прочёл лекцию студентам", "ha-profesor hirtza bi-fnei ha-studentim", 4)
_ex(4530, "המאמר עורר דיון ער בציבור", "Статья вызвала оживлённую дискуссию в обществе", "ha-ma'amar orer diyun er ba-tzibur", 4)
_ex(1470, "התרבות הישראלית מושפעת ממזרח וממערב", "Израильская культура испытывает влияние Востока и Запада", "ha-tarbut ha-yisraelit mush'pa'at mi-mizrakh u-mi-ma'arav", 4)
_ex(1550, "הרצאתו של הפרופסור הייתה מרתקת", "Лекция профессора была захватывающей", "hartzato shel ha-profesor hayta meratekes", 4)
_ex(1630, "הצנזורה הצבאית פעלה בימי המלחמה", "Военная цензура действовала во время войны", "ha-tzenzura ha-tzva'it pa'ala bi-ymei ha-milkhama", 4)
_ex(1710, "הביקורת על הספר הייתה חריפה", "Критика книги была острой", "ha-bikoret al ha-sefer hayta kharifa", 4)
_ex(1790, "המנהל קיבל החלטה קשה", "Директор принял трудное решение", "ha-menahel kibel hakhlata kasha", 4)
_ex(2050, "החולה אושפז במחלקה הפנימית", "Больной госпитализирован во внутреннее отделение", "ha-khole ushpaz ba-makhlaka ha-pnimit", 4)
_ex(2120, "הסטטיסטיקה מראה ירידה בפשיעה", "Статистика показывает снижение преступности", "ha-statistika mar'a yerida ba-pshi'a", 4)
_ex(2190, "התיעוד ההיסטורי נשמר בארכיון", "Историческая документация хранится в архиве", "ha-ti'ud ha-histori nishmar ba-arkhiyon", 4)
_ex(2260, "העמותה פעלה למען זכויות אדם", "Организация действовала во имя прав человека", "ha-amuta pa'ala lema'an zkhuyot adam", 4)
_ex(2330, "הפסיכיאטר אבחן דיכאון קליני", "Психиатр диагностировал клиническую депрессию", "ha-psikhiyater ivkhen dikaon klini", 4)
_ex(2400, "הפילוסוף העלה שאלות מהותיות", "Философ поставил сущностные вопросы", "ha-filosof he'ela she'elot mahutiyot", 4)
_ex(2470, "המשא ומתן נמשך שבועות ארוכים", "Переговоры длились долгие недели", "ha-masa u-matan nimshakh shvu'ot arukim", 4)
_ex(2540, "ההיסטוריון חקר את תקופת המנדט", "Историк исследовал период Мандата", "ha-historyon khakar et tkufat ha-mandat", 4)
_ex(2610, "החוקה מגינה על חופש הביטוי", "Конституция защищает свободу слова", "ha-khuka megina al khofesh ha-bituy", 4)
_ex(2680, "הרבנות הראשית הכריעה בשאלה הלכתית", "Главный раввинат вынес решение по вопросу галахи", "ha-rabanut ha-rashit hikhri'a be-she'ela hilkhatit", 4)
_ex(2750, "הקואליציה התפרקה לאחר המשבר", "Коалиция распалась после кризиса", "ha-koalitzya hitparka le'akhar ha-mashber", 4)
_ex(2820, "המדינאי הציע תוכנית שלום חדשה", "Государственный деятель предложил новый мирный план", "ha-medinay hetzi'a tokhnit shalom khadasha", 4)
_ex(2890, "הפרקליטות הגישה כתב אישום", "Прокуратура подала обвинительное заключение", "ha-praklitut higisha ktav ishum", 4)
_ex(2960, "הסוציולוג חקר את ההרכב האתני", "Социолог исследовал этнический состав", "ha-sotziolog khakar et ha-herkev ha-etni", 4)
_ex(3030, "הסנקציות הכלכליות הוחמרו", "Экономические санкции ужесточены", "ha-sanktziot ha-kalkaliot hukhemru", 4)
_ex(3100, "הדמוקרטיה דורשת שקיפות", "Демократия требует прозрачности", "ha-demokratya doreshet shkifut", 4)
_ex(3170, "הרפורמה המשפטית עוררה מחאה", "Правовая реформа вызвала протест", "ha-reforma ha-mishpatit orera mekha'a", 4)
_ex(3240, "הנציב פרסם דוח ביקורת", "Контролёр опубликовал отчёт ревизии", "ha-natziv pirsem do'akh bikoret", 4)
_ex(3310, "הפרלמנט אישר את החוק ברוב קולות", "Парламент утвердил закон большинством голосов", "ha-parlament isher et ha-khok be-rov kolot", 4)
_ex(3380, "הממשלה הקצתה תקציב לחינוך", "Правительство выделило бюджет на образование", "ha-memshala hiktzta taktziv la-khinukh", 4)
_ex(3450, "המדען קיבל פרס נובל", "Учёный получил Нобелевскую премию", "ha-mad'an kibel pras nobel", 4)
_ex(3520, "הדיפלומט ניהל שיחות סודיות", "Дипломат вёл секретные переговоры", "ha-diplomat nihel sikhot sodiyot", 4)
_ex(4600, "האינפלציה פגעה בכוח הקנייה", "Инфляция ударила по покупательной способности", "ha-inflatzya pag'a be-koakh ha-kniya", 4)
_ex(4670, "הניסוי המדעי הניב תוצאות מפתיעות", "Научный эксперимент дал удивительные результаты", "ha-nisuy ha-mad'i heniv totz'aot mafti'ot", 4)
_ex(4740, "ועדת הכלכלה דנה בתקציב המדינה", "Экономическая комиссия обсуждала госбюджет", "va'adat ha-kalkala dana be-taktziv ha-medina", 4)
_ex(4810, "העיתון פרסם חקירה על שחיתות", "Газета опубликовала расследование о коррупции", "ha-iton pirsem khakira al shkhitut", 4)
_ex(4880, "הנתבע הכחיש את כל ההאשמות", "Ответчик отверг все обвинения", "ha-nitba hikhkhish et kol ha-ha'ashamot", 4)
_ex(4950, "הביקורת האקדמית הייתה מפורטת", "Академическая рецензия была подробной", "ha-bikoret ha-akademit hayta mefuretet", 4)
_ex(5020, "המגזר הפרטי מעסיק רוב העובדים", "Частный сектор нанимает большинство работников", "ha-migzar ha-prati ma'asik rov ha-ovdim", 4)
_ex(5090, "הסכסוך נפתר בדרכי שלום", "Конфликт решён мирным путём", "ha-sikhsukh niftar be-darkhei shalom", 4)
_ex(5160, "ההשכלה הגבוהה נגישה לכולם", "Высшее образование доступно всем", "ha-haskala ha-gvoha negisha la-kulam", 4)
_ex(5230, "התעשייה ההייטקית מובילה את המשק", "Хайтек-индустрия лидирует в экономике", "ha-ta'asiya ha-haitek'it movila et ha-meshek", 4)
_ex(5300, "הרשות הפלסטינית הגיבה להצעה", "Палестинская администрация отреагировала на предложение", "ha-rashut ha-falestinit hegiva la-hatza'a", 4)
_ex(5370, "היצוא הישראלי גדל בעשרה אחוז", "Израильский экспорт вырос на десять процентов", "ha-yetzu ha-yisraeli gadal ba-asara akhuz", 4)
_ex(5440, "המשפט המנהלי מסדיר את יחסי פרט-מדינה", "Административное право регулирует отношения личности и государства", "ha-mishpat ha-minhali mesader et yakhasei prat-medina", 4)

# ============ L5: +106 examples (word IDs from 1516-6841) ============

_ex(1550, "הדיסקורס האקדמי דורש דיוק בניסוח", "Академический дискурс требует точности формулировок", "ha-diskurs ha-akademi doresh diyuk be-nisuakh", 5)
_ex(1620, "האינטרטקסטואליות מעשירה את הקריאה", "Интертекстуальность обогащает чтение", "ha-intertekstu'aliyut ma'ashira et ha-kri'a", 5)
_ex(1690, "הפרדיגמה המחקרית השתנתה בעשורים האחרונים", "Исследовательская парадигма изменилась в последние десятилетия", "ha-paradigma ha-mekhkarit hishtanta ba-asorim ha-akharonim", 5)
_ex(1760, "המאמר מציע פרשנות חלופית לתופעה", "Статья предлагает альтернативную интерпретацию явления", "ha-ma'amar metzi'a parshanut khalufit la-tofa'a", 5)
_ex(1830, "הנרטיב הלאומי עוצב במהלך המאה העשרים", "Национальный нарратив сформировался в XX веке", "ha-narrativ ha-le'umi utzav be-mahalakh ha-me'a ha-esrim", 5)
_ex(1900, "הניתוח הסטרוקטורליסטי חשף מבנים סמויים", "Структуралистский анализ выявил скрытые структуры", "ha-nituakh ha-strukturalisti khasaf mivnim smuyim", 5)
_ex(1970, "האמביוולנטיות של הדמות מעניינת", "Амбивалентность персонажа интересна", "ha-ambivalentiyut shel ha-dmut me'anyenet", 5)
_ex(2040, "הסמנטיקה של המילה השתנתה לאורך הדורות", "Семантика слова менялась на протяжении поколений", "ha-semantika shel ha-mila hishtanta le-orekh ha-dorot", 5)
_ex(2110, "הפרגמטיקה חוקרת שפה בהקשר", "Прагматика изучает язык в контексте", "ha-pragmatika khokeret safa be-heksher", 5)
_ex(2180, "האפיסטמולוגיה עוסקת בשאלת הידיעה", "Эпистемология занимается вопросом познания", "ha-epistemologia oseket be-she'elat ha-yedi'a", 5)
_ex(2250, "ההרמנויטיקה מציעה כלים לפרשנות טקסטים", "Герменевтика предлагает инструменты для интерпретации текстов", "ha-hermeneutika metzi'a kelim le-parshanut tekstim", 5)
_ex(2320, "ההגמוניה התרבותית קובעת נורמות חברתיות", "Культурная гегемония определяет социальные нормы", "ha-hegemonia ha-tarbutit kova'at normot khevratiyot", 5)
_ex(2390, "הדיאלקטיקה ההגליאנית משפיעה על ההגות המודרנית", "Гегелевская диалектика влияет на современную мысль", "ha-dialektika ha-hegel'ianit mashpi'a al ha-hagut ha-modernit", 5)
_ex(2460, "האנומיה החברתית נובעת מאובדן ערכים", "Социальная аномия проистекает из утраты ценностей", "ha-anomia ha-khevratit novaat me-ovdan arakhim", 5)
_ex(2530, "הקאנון הספרותי משתנה בכל דור", "Литературный канон меняется в каждом поколении", "ha-kanon ha-sifruti mishtane be-khol dor", 5)
_ex(2600, "הטרנסצנדנטליות קשורה לפילוסופיה של קאנט", "Трансцендентальность связана с философией Канта", "ha-transtsendantaliyut kshura la-filosofia shel kant", 5)
_ex(2670, "האמפיריציזם מדגיש את חשיבות הניסיון", "Эмпиризм подчёркивает важность опыта", "ha-empiritzizm madgish et khashivut ha-nisayon", 5)
_ex(2740, "הפנומנולוגיה של הוסרל שינתה את הפילוסופיה", "Феноменология Гуссерля изменила философию", "ha-fenomenologia shel huserl shinta et ha-filosofia", 5)
_ex(2810, "האקזיסטנציאליזם מדגיש את חופש הבחירה", "Экзистенциализм подчёркивает свободу выбора", "ha-ekzistentsializm madgish et khofesh ha-bkhira", 5)
_ex(2880, "הדקונסטרוקציה מערערת על הנחות יסוד", "Деконструкция подвергает сомнению базовые предпосылки", "ha-dekonstruktzya me'ar'eret al hanakhot yesod", 5)
_ex(2950, "המטאפיזיקה עוסקת בשאלות על טבע המציאות", "Метафизика занимается вопросами о природе реальности", "ha-metafizika oseket be-she'elot al teva ha-metzi'ut", 5)
_ex(3020, "האונטולוגיה חוקרת את מהות הקיום", "Онтология исследует сущность бытия", "ha-ontologia khokeret et mahut ha-kiyum", 5)
_ex(3090, "הפוסט-מודרניזם מערער על אמיתות מוחלטות", "Постмодернизм подвергает сомнению абсолютные истины", "ha-post-modernizm me'ar'er al amitot mukhlalot", 5)
_ex(3160, "הסוציולוגיה הביקורתית בוחנת מבני כוח", "Критическая социология исследует структуры власти", "ha-sotziologia ha-bikortit bokhenet mivnei koakh", 5)
_ex(3230, "המושג 'אחר' מרכזי בפילוסופיה של לוינס", "Понятие 'Другой' центрально в философии Левинаса", "ha-musag 'akher' merkazi ba-filosofia shel levinas", 5)
_ex(3300, "הפמיניזם שינה את השיח האקדמי", "Феминизм изменил академический дискурс", "ha-feminizm shina et ha-siakh ha-akademi", 5)
_ex(3370, "ההיסטוריוגרפיה בוחנת כיצד נכתב העבר", "Историография изучает, как пишется прошлое", "ha-historiografiya bokhenet keitzad nikhtav ha-avar", 5)
_ex(3440, "הביו-אתיקה מתמודדת עם דילמות רפואיות", "Биоэтика сталкивается с медицинскими дилеммами", "ha-bio-etika mitmodetet im dilemot refu'iyot", 5)
_ex(3510, "הפלורליזם מכיר בלגיטימיות של דעות שונות", "Плюрализм признаёт легитимность различных мнений", "ha-pluralizm makir be-legitimiyut shel de'ot shonot", 5)
_ex(3580, "האלגוריה כמכשיר ספרותי קיימת מימי קדם", "Аллегория как литературный приём существует с древности", "ha-alegorya ke-makhshir sifruti kayemet mi-ymei kedem", 5)
_ex(3650, "הפרדוקס העצמי מאתגר את ההיגיון", "Самореферентный парадокс бросает вызов логике", "ha-paradoks ha-atzmi me'atger et ha-higayon", 5)
_ex(3720, "המינימליזם בספרות מעדיף פשטות", "Минимализм в литературе предпочитает простоту", "ha-minimalizm ba-sifrut ma'adif pashtut", 5)
_ex(3790, "האירוניה הדרמטית מוסיפה עומק ליצירה", "Драматическая ирония добавляет глубину произведению", "ha-ironia ha-dramatit mosifa omek la-yetzira", 5)
_ex(3860, "הנהירה לערים יצרה בעיות חברתיות", "Урбанизация создала социальные проблемы", "ha-nehira la-arim yatzra be'ayot khevratiyot", 5)
_ex(3930, "הרציונליזם מייחס חשיבות עליונה לשכל", "Рационализм придаёт высшее значение разуму", "ha-ratzionalizm meyakhes khashivut eliona la-sekhel", 5)
_ex(4000, "הרלטיביזם התרבותי מעורר דיון סוער", "Культурный релятивизм вызывает бурную дискуссию", "ha-relativizm ha-tarbuti me'orer diyun so'er", 5)
_ex(4070, "הדטרמיניזם שולל את חופש הרצון", "Детерминизм отрицает свободу воли", "ha-determinizm sholel et khofesh ha-ratzon", 5)
_ex(4140, "הפסיכואנליזה של פרויד שינתה את ההבנה העצמית", "Психоанализ Фрейда изменил самопонимание", "ha-psikho'analiza shel froid shinta et ha-havana ha-atzmit", 5)
_ex(4210, "הסמיוטיקה מנתחת מערכות סימנים", "Семиотика анализирует системы знаков", "ha-semiotika menatkhat ma'arkhot simanim", 5)
_ex(4280, "המורפולוגיה חוקרת את מבנה המילים", "Морфология исследует структуру слов", "ha-morfologia khokeret et mivne ha-milim", 5)
_ex(4350, "הפרוזה של עגנון מאופיינת בסגנון ייחודי", "Проза Агнона отличается уникальным стилем", "ha-proza shel agnon me'ufyenet be-signon yikhudi", 5)
_ex(4420, "האנתרופולוגיה חוקרת תרבויות אנושיות", "Антропология изучает человеческие культуры", "ha-antropologia khokeret tarbu'ot enoshiyot", 5)
_ex(4490, "המעבר מהמודרניזם לפוסט-מודרניזם משמעותי", "Переход от модернизма к постмодернизму значителен", "ha-ma'avar me-ha-modernizm la-post-modernizm mashma'uti", 5)
_ex(4560, "ההיפותזה לא אושרה באופן סטטיסטי", "Гипотеза не подтверждена статистически", "ha-hipoteza lo ushra be-ofen statisty", 5)
_ex(4630, "הטענה הפילוסופית דורשת ביסוס לוגי", "Философское утверждение требует логического обоснования", "ha-ta'ana ha-filosofit doreshet bisus logi", 5)
_ex(4700, "הנראטולוגיה מנתחת מבני סיפור", "Нарратология анализирует структуры повествования", "ha-narratologia menatkhat mivnei sipur", 5)
_ex(4770, "הדוגמטיות מונעת חשיבה ביקורתית", "Догматизм препятствует критическому мышлению", "ha-dogmatiyut mona'at khashiva bikortit", 5)
_ex(4840, "הסכולסטיקה שלטה בפילוסופיה של ימי הביניים", "Схоластика доминировала в философии Средневековья", "ha-skholastika shalta ba-filosofia shel ymei ha-beinayim", 5)
_ex(4910, "הבינתחומיות מאפשרת מחקר מקיף יותר", "Междисциплинарность позволяет более комплексное исследование", "ha-bein-tkhumiyut me'afsheret mekhkar makif yoter", 5)
_ex(4980, "המטאנרטיב מספר על עצמו כסיפור", "Метанарратив рассказывает о себе как о повествовании", "ha-metanarativ mesaper al atzmo ke-sipur", 5)
_ex(5050, "הרב-קוליות בספרות מייצגת מגוון דעות", "Полифония в литературе представляет разнообразие мнений", "ha-rav-koliyut ba-sifrut meyatzget migvan de'ot", 5)
_ex(5120, "האינדוקציה עוברת מן הפרט אל הכלל", "Индукция идёт от частного к общему", "ha-induktzya overet min ha-prat el ha-klal", 5)
_ex(5190, "הדדוקציה עוברת מן הכלל אל הפרט", "Дедукция идёт от общего к частному", "ha-deduktzya overet min ha-klal el ha-prat", 5)
_ex(5260, "הסילוגיזם הוא צורה בסיסית של היסק", "Силлогизм — базовая форма умозаключения", "ha-silogizm hu tzura bsisit shel hesek", 5)
_ex(5330, "האנלוגיה מסייעת להבנת מושגים מופשטים", "Аналогия помогает понять абстрактные понятия", "ha-analogia mesayaat le-havanat musagim mufshatim", 5)
_ex(5400, "הרדוקציוניזם מפשט תופעות מורכבות", "Редукционизм упрощает сложные явления", "ha-reduktzionizm mefshet tofa'ot murkavot", 5)
_ex(5470, "ההוליזם מדגיש את השלם מעבר לחלקיו", "Холизм подчёркивает целое сверх его частей", "ha-holizm madgish et ha-shalem me'ever la-khalakav", 5)
_ex(5540, "הרפלקסיביות היא מאפיין של מחקר איכותני", "Рефлексивность — характеристика качественного исследования", "ha-refleksiviyut hi me'afen shel mekhkar ekhutani", 5)
_ex(5610, "ההפשטה מאפשרת הכללה תיאורטית", "Абстрагирование позволяет теоретическое обобщение", "ha-hafshata me'afsheret hakhlala te'oretit", 5)
_ex(5680, "הפנומן מתואר מנקודת מבט סובייקטיבית", "Феномен описывается с субъективной точки зрения", "ha-fenomen metu'ar mi-nekudat mabat subyektivit", 5)
_ex(5750, "הקונטקסט ההיסטורי חיוני להבנת הטקסט", "Исторический контекст необходим для понимания текста", "ha-kontekst ha-histori khiyuni le-havanat ha-tekst", 5)
_ex(1580, "השיח הציבורי משקף מתחים חברתיים", "Общественный дискурс отражает социальные напряжения", "ha-siakh ha-tziburi meshakef metakhim khevratiyim", 5)
_ex(1650, "הביקורת הספרותית מעניקה פרשנות לטקסט", "Литературная критика даёт интерпретацию текста", "ha-bikoret ha-sifrutit ma'anika parshanut la-tekst", 5)
_ex(1720, "הפילוסופיה האנליטית מדגישה בהירות לשונית", "Аналитическая философия подчёркивает языковую ясность", "ha-filosofia ha-analitit madgisha behirut leshonit", 5)
_ex(1790, "הסוציולינגוויסטיקה חוקרת שפה בהקשר חברתי", "Социолингвистика изучает язык в социальном контексте", "ha-sotziolingvistika khokeret safa be-heksher khevrati", 5)
_ex(1860, "האינטרפרטציה תלויה ברקע התרבותי של הקורא", "Интерпретация зависит от культурного фона читателя", "ha-interpretatzya tluya ba-reka ha-tarbuti shel ha-kore", 5)
_ex(1930, "הקונצפטואליזם באמנות מעדיף רעיון על ביצוע", "Концептуализм в искусстве предпочитает идею исполнению", "ha-kontzeptualizm ba-omanut ma'adif ra'ayon al bitzu'a", 5)
_ex(2000, "ההיסטוריציזם טוען שכל ידיעה מותנית היסטורית", "Историцизм утверждает, что всё знание исторически обусловлено", "ha-historitzizm to'en she-kol yedi'a mutnit historit", 5)
_ex(2070, "הסינכרוניה בלשנית בוחנת שפה ברגע נתון", "Лингвистическая синхрония изучает язык в данный момент", "ha-sinkhroniya balshenit bokhenet safa be-rega natun", 5)
_ex(2140, "הדיאכרוניה בוחנת התפתחות שפה לאורך זמן", "Диахрония изучает развитие языка во времени", "ha-diakhroniya bokhenet hitpathut safa le-orekh zman", 5)
_ex(6000, "הפואטיקה של אריסטו השפיעה על הביקורת הספרותית", "Поэтика Аристотеля повлияла на литературную критику", "ha-po'etika shel aristo hishpi'a al ha-bikoret ha-sifrutit", 5)
_ex(6100, "הלקסיקוגרפיה עוסקת בעריכת מילונים", "Лексикография занимается составлением словарей", "ha-leksikografiya oseket ba-arikhat millonim", 5)
_ex(6200, "הפילולוגיה חוקרת טקסטים עתיקים", "Филология исследует древние тексты", "ha-filologia khokeret tekstim atikim", 5)
_ex(6300, "האטימולוגיה חוקרת מקורות מילים", "Этимология исследует происхождение слов", "ha-etimologia khokeret mekorot milim", 5)
_ex(6400, "הדיגלוסיה מאפיינת חברות רבות", "Диглоссия характерна для многих обществ", "ha-diglosia me'afyenet khavarot rabot", 5)
_ex(6500, "הפוליסמיה היא ריבוי משמעויות של מילה", "Полисемия — множественность значений слова", "ha-polisemiya hi ribuy mashma'uyot shel mila", 5)
_ex(6600, "הסינתזה משלבת רעיונות מנוגדים", "Синтез объединяет противоположные идеи", "ha-sinteza meshalevet ra'ayonot menugadim", 5)
_ex(6700, "האנטינומיה מציגה סתירה בין עקרונות", "Антиномия представляет противоречие между принципами", "ha-antinomiya matziga stira bein ekronot", 5)
_ex(6800, "הטלאולוגיה מפרשת תופעות לפי תכליתן", "Телеология интерпретирует явления по их цели", "ha-teleologia mefarshet tofa'ot lefi takhlitan", 5)

# ============ L6: +48 examples (word IDs from 1616-8066) ============

_ex(1650, "השיח הפוסט-קולוניאלי בוחן יחסי כוח", "Постколониальный дискурс изучает отношения власти", "ha-siakh ha-post-koloniali bokhen yakhasei koakh", 6)
_ex(1750, "הדרשנות הרבנית פיתחה שיטות פרשנות ייחודיות", "Раввинская проповедь развила уникальные методы интерпретации", "ha-darshanut ha-rabanit pitakha shitot parshanut yikhudiyot", 6)
_ex(1850, "האפוריזם מרכז חוכמה במילים מעטות", "Афоризм концентрирует мудрость в нескольких словах", "ha-aforizm merakez khokhma be-milim me'atot", 6)
_ex(1950, "הפאתוס הרטורי מכוון להשפיע רגשית", "Риторический пафос направлен на эмоциональное воздействие", "ha-patos ha-retori mekhaven lehashpi'a rigsheet", 6)
_ex(2050, "הלוגוס מייצג את היסוד הרציונלי בשכנוע", "Логос представляет рациональный элемент убеждения", "ha-logos meyatzeg et ha-yesod ha-ratzionali ba-shikhnu'a", 6)
_ex(2150, "האתוס של הדובר משפיע על האמינות שלו", "Этос говорящего влияет на его достоверность", "ha-etos shel ha-dover mashpi'a al ha-aminut shelo", 6)
_ex(2250, "המליצה הבלתי נשלטת פוגעת באותנטיות", "Неконтролируемая высокопарность вредит аутентичности", "ha-melitza ha-bilti nishletet poga'at ba-otentiyut", 6)
_ex(2350, "הליטוטס מביע תוכן חיובי בניסוח שלילי", "Литота выражает позитивное содержание в отрицательной формулировке", "ha-litotes mabi'a tokhen khiyuvi be-nisuakh shlili", 6)
_ex(2450, "האוקסימורון מחבר מושגים סותרים", "Оксиморон соединяет противоречивые понятия", "ha-oksimoron mekhaber musagim sotrim", 6)
_ex(2550, "הכיאזמוס יוצר הקבלה מוצלבת", "Хиазм создаёт перекрёстную параллель", "ha-khiazmus yotzer hakbala mutzlevet", 6)
_ex(2650, "האנאפורה חוזרת על מילה בתחילת משפטים", "Анафора повторяет слово в начале предложений", "ha-anafora khozeret al mila bi-tkhilat mishpatim", 6)
_ex(2750, "הקתרזיס הוא טיהור רגשי דרך אמנות", "Катарсис — это эмоциональное очищение через искусство", "ha-katarsis hu tihur rigshi derekh omanut", 6)
_ex(2850, "הסינקרטיזם משלב אלמנטים מתרבויות שונות", "Синкретизм объединяет элементы разных культур", "ha-sinkretizm meshalev elementim mi-tarbu'ot shonot", 6)
_ex(2950, "הפליאדה הצרפתית השפיעה על הספרות האירופית", "Французская Плеяда повлияла на европейскую литературу", "ha-ple'ada ha-tzarfatit hishpi'a al ha-sifrut ha-eropit", 6)
_ex(3050, "הפרוסודיה מנתחת קצב וטעם בשפה", "Просодия анализирует ритм и ударение в речи", "ha-prosodia menatkhat ketzev ve-ta'am ba-safa", 6)
_ex(3150, "הגראפולוגיה טוענת לקשר בין כתב יד לאישיות", "Графология утверждает о связи между почерком и личностью", "ha-grafologia to'enet le-kesher bein ktav yad le-ishiyut", 6)
_ex(3350, "הנאו-קלאסיציזם שאב השראה מיוון ורומא", "Неоклассицизм черпал вдохновение из Греции и Рима", "ha-neo-klasitzizm sha'av hash'ra'a mi-yavan ve-roma", 6)
_ex(3550, "הדיסטופיה מתארת חברה עתידית מפחידה", "Антиутопия описывает пугающее будущее общество", "ha-distopia meta'eret khevra atidiy mafkhida", 6)
_ex(3750, "האקספרסיוניזם מבטא רגשות פנימיים עזים", "Экспрессионизм выражает сильные внутренние чувства", "ha-ekspresyonizm mevate regashot pnimiyim azim", 6)
_ex(3950, "הסוריאליזם מאתגר את גבולות המציאות", "Сюрреализм бросает вызов границам реальности", "ha-suriyalizm me'atger et gvulot ha-metzi'ut", 6)
_ex(4150, "האבסורד בספרות מציג את חוסר המשמעות", "Абсурд в литературе представляет бессмысленность", "ha-absurd ba-sifrut matziy et khoser ha-mashma'ut", 6)
_ex(4350, "האלגוריזציה היא תהליך הפיכת טקסט לאלגוריה", "Аллегоризация — процесс превращения текста в аллегорию", "ha-alegorizatzya hi takhlit hafikhat tekst le-alegorya", 6)
_ex(4550, "הפרוטוקול הדיפלומטי קובע כללי התנהגות", "Дипломатический протокол устанавливает правила поведения", "ha-protokol ha-diplomati kove'a klalei hitnagut", 6)
_ex(4750, "הריטואל מעניק משמעות לאירועי חיים", "Ритуал придаёт смысл жизненным событиям", "ha-ritu'al ma'anik mashma'ut le-iru'ei khayim", 6)
_ex(4950, "ההגות היהודית מציעה מגוון גישות לאתיקה", "Еврейская мысль предлагает разнообразие подходов к этике", "ha-hagut ha-yehudit metzi'a migvan gishot le-etika", 6)
_ex(5150, "הפילוסופיה האנליטית מנתחת מושגים בדייקנות", "Аналитическая философия анализирует понятия с точностью", "ha-filosofia ha-analitit menatkhat musagim be-daykanut", 6)
_ex(5350, "האינטלקטואליזם מייחס חשיבות עליונה לשכל", "Интеллектуализм придаёт высшее значение разуму", "ha-intelektu'alizm meyakhes khashivut eliona la-sekhel", 6)
_ex(5550, "ההומניזם מציב את האדם במרכז", "Гуманизм ставит человека в центр", "ha-humanizm matziv et ha-adam ba-merkaz", 6)
_ex(5750, "הסקולריזציה היא תהליך חילון החברה", "Секуляризация — процесс обмирщения общества", "ha-sekularizatzya hi takhlit khilun ha-khevra", 6)
_ex(5950, "הפרטיקולריזם מדגיש את הייחודיות של כל תרבות", "Партикуляризм подчёркивает уникальность каждой культуры", "ha-partikularizm madgish et ha-yikhudiyut shel kol tarbut", 6)
_ex(6150, "האוניברסליזם טוען לערכים משותפים לכל האנושות", "Универсализм утверждает об общих ценностях для всего человечества", "ha-universalizm to'en la-arakhim meshutafim le-khol ha-enoshut", 6)
_ex(6350, "הנורמטיביות קובעת מה נחשב לנכון ולראוי", "Нормативность определяет, что считается правильным и должным", "ha-normativiyut kova'at ma nekhshav le-nakhon u-le-ra'uy", 6)
_ex(6550, "הדיסקורס המשפטי מאופיין בדיוק טרמינולוגי", "Юридический дискурс характеризуется терминологической точностью", "ha-diskurs ha-mishpati me'ufyan be-diyuk terminologi", 6)
_ex(6750, "הרטוריקה הפוליטית משתמשת באמצעי שכנוע מגוונים", "Политическая риторика использует разнообразные средства убеждения", "ha-retorika ha-politit mishtameshet be-emtza'ei shikhnu'a megavanim", 6)
_ex(6950, "הפילולוגיה ההשוואתית חוקרת קשרי שפות", "Сравнительная филология исследует связи между языками", "ha-filologia ha-hashva'atit khokeret kishrei safot", 6)
_ex(7050, "הסמנטיקה הקוגניטיבית בוחנת קשר בין שפה לחשיבה", "Когнитивная семантика изучает связь языка и мышления", "ha-semantika ha-kognitivit bokhenet kesher bein safa le-khashiva", 6)
_ex(7150, "הפרגמטיזם האמריקאי שינה את הפילוסופיה", "Американский прагматизм изменил философию", "ha-pragmatizm ha-amerik'i shina et ha-filosofia", 6)
_ex(7250, "הניהיליזם שולל כל ערך ומשמעות", "Нигилизм отрицает всякую ценность и смысл", "ha-nihilizm sholel kol erekh u-mashma'ut", 6)
_ex(7350, "הסטואיציזם מציע שליטה עצמית כמפתח לאושר", "Стоицизм предлагает самоконтроль как ключ к счастью", "ha-stoitzizm metzi'a shlita atzmit ke-mafte'akh le-osher", 6)
_ex(7450, "האפיקוריאניזם מזהה אושר עם היעדר סבל", "Эпикуреизм отождествляет счастье с отсутствием страдания", "ha-epikuri'anizm mezahe osher im he'ader sevel", 6)
_ex(7550, "הסקפטיציזם מטיל ספק ביכולת להשיג ידע מוחלט", "Скептицизм ставит под сомнение возможность достижения абсолютного знания", "ha-skeptitzizm matil safek ba-yekholet lehasig yeda mukhlat", 6)
_ex(7650, "הפוזיטיביזם מכיר רק בידע אמפירי מוכח", "Позитивизм признаёт только доказанное эмпирическое знание", "ha-pozitivizm makir rak be-yeda empiri mukhakh", 6)
_ex(7750, "הנאו-פלטוניזם שילב מסורות פילוסופיות שונות", "Неоплатонизм объединил разные философские традиции", "ha-neo-platonizm shilev masorot filosofiyot shonot", 6)
_ex(7850, "המיסטיקה היהודית מציעה דרכי התקרבות לאלוהי", "Еврейская мистика предлагает пути приближения к Божественному", "ha-mistika ha-yehudit metzi'a darkhei hitkarvut la-elohi", 6)
_ex(7950, "הפנתאיזם מזהה את האלוהי עם הטבע", "Пантеизм отождествляет Божественное с природой", "ha-pante'izm mezahe et ha-elohi im ha-teva", 6)
_ex(8050, "הטרנסצנדנציה מתייחסת למה שמעבר לניסיון", "Трансценденция относится к тому, что за пределами опыта", "ha-transtendentsya mityakheset le-ma she-me'ever la-nisayon", 6)

print(f"Total examples: {len(EXAMPLES)}")
print(f"L3: {sum(1 for e in EXAMPLES if e[5]==3)}")
print(f"L4: {sum(1 for e in EXAMPLES if e[5]==4)}")
print(f"L5: {sum(1 for e in EXAMPLES if e[5]==5)}")
print(f"L6: {sum(1 for e in EXAMPLES if e[5]==6)}")

# Write migration
header = '''"""Add ~329 more example sentences to reach 2000 total."""
from alembic import op
import sqlalchemy as sa

revision = "104"
down_revision = "103"
branch_labels = None
depends_on = None

def upgrade():
    t = sa.table(
        "example_sentences",
        sa.column("word_id", sa.Integer),
        sa.column("hebrew", sa.Text),
        sa.column("translation_ru", sa.Text),
        sa.column("transliteration", sa.Text),
        sa.column("audio_url", sa.Text),
        sa.column("level_id", sa.Integer),
    )
    rows = [
'''

footer = '''    ]
    op.bulk_insert(t, [
        {"word_id": r[0], "hebrew": r[1], "translation_ru": r[2],
         "transliteration": r[3], "audio_url": r[4], "level_id": r[5]}
        for r in rows
    ])
    op.execute("SELECT setval('example_sentences_id_seq', GREATEST((SELECT COALESCE(MAX(id),0) FROM example_sentences), 1))")

def downgrade():
    op.execute("DELETE FROM example_sentences WHERE id > 1671")
    op.execute("SELECT setval('example_sentences_id_seq', GREATEST((SELECT COALESCE(MAX(id),0) FROM example_sentences), 1))")
'''

out = "/Users/antonp/work/hebrew/backend/migrations/versions/104_examples_boost.py"
with open(out, "w") as f:
    f.write(header)
    for e in EXAMPLES:
        wid, he, ru, tr, au, lvl = e
        f.write(f'        ({wid}, {repr(he)}, {repr(ru)}, {repr(tr)}, None, {lvl}),\n')
    f.write(footer)

print(f"Output: {out}")
