"""initial_schema

Revision ID: 001
Revises: 
Create Date: 2026-03-05 07:43:23.714442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title_ru', sa.String(length=100), nullable=False),
    sa.Column('description_ru', sa.String(length=300), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('condition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('alphabet_letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('letter', sa.String(length=5), nullable=False),
    sa.Column('name_ru', sa.String(length=50), nullable=False),
    sa.Column('translit', sa.String(length=20), nullable=False),
    sa.Column('sound_description', sa.String(length=200), nullable=True),
    sa.Column('numeric_value', sa.Integer(), nullable=True),
    sa.Column('is_sofit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sofit_of', sa.String(length=5), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name_ru', sa.String(length=50), nullable=False),
    sa.Column('name_he', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('cefr_equivalent', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('nikkud',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=False),
    sa.Column('name_he', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.String(length=50), nullable=False),
    sa.Column('sound', sa.String(length=50), nullable=False),
    sa.Column('example_word', sa.String(length=50), nullable=True),
    sa.Column('example_translit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prepositions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_form', sa.String(length=30), nullable=False),
    sa.Column('meaning_ru', sa.String(length=100), nullable=False),
    sa.Column('declension_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('root_families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('root', sa.String(length=20), nullable=False),
    sa.Column('meaning_ru', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_root_families_root'), 'root_families', ['root'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('native_lang', sa.String(length=10), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_table('binyanim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_he', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pattern', sa.String(length=50), nullable=True),
    sa.Column('example_root', sa.String(length=20), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culture_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title_ru', sa.String(length=200), nullable=False),
    sa.Column('title_he', sa.String(length=200), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialogues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('situation_ru', sa.Text(), nullable=True),
    sa.Column('lines_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vocabulary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grammar_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_ru', sa.String(length=200), nullable=False),
    sa.Column('title_he', sa.String(length=200), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=200), nullable=False),
    sa.Column('title_he', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_texts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('title_he', sa.String(length=200), nullable=False),
    sa.Column('title_ru', sa.String(length=200), nullable=False),
    sa.Column('content_he', sa.Text(), nullable=False),
    sa.Column('content_ru', sa.Text(), nullable=False),
    sa.Column('vocabulary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('srs_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('card_type', sa.String(length=30), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('front_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('back_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_srs_cards_user_id'), 'srs_cards', ['user_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=False),
    sa.Column('name_he', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_daily_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('exercises_done', sa.Integer(), nullable=False),
    sa.Column('reviews_done', sa.Integer(), nullable=False),
    sa.Column('time_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_daily')
    )
    op.create_index(op.f('ix_user_daily_activity_user_id'), 'user_daily_activity', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('daily_new_cards', sa.Integer(), nullable=False),
    sa.Column('srs_algorithm', sa.String(length=20), nullable=False),
    sa.Column('ui_theme', sa.String(length=10), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_skill_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('last_practice', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hebrew', sa.String(length=100), nullable=False),
    sa.Column('nikkud', sa.String(length=100), nullable=True),
    sa.Column('transliteration', sa.String(length=200), nullable=True),
    sa.Column('translation_ru', sa.String(length=500), nullable=False),
    sa.Column('pos', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('root', sa.String(length=20), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_hebrew'), 'words', ['hebrew'], unique=False)
    op.create_table('collocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('phrase_he', sa.String(length=300), nullable=False),
    sa.Column('phrase_ru', sa.String(length=300), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collocations_word_id'), 'collocations', ['word_id'], unique=False)
    op.create_table('example_sentences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('hebrew', sa.Text(), nullable=False),
    sa.Column('translation_ru', sa.Text(), nullable=False),
    sa.Column('transliteration', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_sentences_word_id'), 'example_sentences', ['word_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('prompt_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_lesson_id'), 'exercises', ['lesson_id'], unique=False)
    op.create_table('grammar_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('rule_text_ru', sa.Text(), nullable=False),
    sa.Column('examples_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exceptions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['grammar_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_rules_topic_id'), 'grammar_rules', ['topic_id'], unique=False)
    op.create_table('root_family_members',
    sa.Column('root_family_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['root_family_id'], ['root_families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('root_family_id', 'word_id')
    )
    op.create_table('srs_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['srs_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_srs_reviews_card_id'), 'srs_reviews', ['card_id'], unique=False)
    op.create_table('srs_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('next_review', sa.DateTime(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['srs_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id')
    )
    op.create_table('user_topic_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('words_learned', sa.Integer(), nullable=False),
    sa.Column('exercises_done', sa.Integer(), nullable=False),
    sa.Column('mastery_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'topic_id')
    )
    op.create_table('verb_conjugations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('binyan_id', sa.Integer(), nullable=False),
    sa.Column('tense', sa.String(length=20), nullable=False),
    sa.Column('person', sa.String(length=5), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('form_he', sa.String(length=100), nullable=False),
    sa.Column('form_nikkud', sa.String(length=100), nullable=True),
    sa.Column('transliteration', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['binyan_id'], ['binyanim.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verb_conjugations_binyan_id'), 'verb_conjugations', ['binyan_id'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_word_id'), 'verb_conjugations', ['word_id'], unique=False)
    op.create_table('word_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=50), nullable=False),
    sa.Column('hebrew', sa.String(length=100), nullable=False),
    sa.Column('nikkud', sa.String(length=100), nullable=True),
    sa.Column('transliteration', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_forms_word_id'), 'word_forms', ['word_id'], unique=False)
    op.create_table('word_relations',
    sa.Column('word_id_1', sa.Integer(), nullable=False),
    sa.Column('word_id_2', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['word_id_1'], ['words.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id_2'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id_1', 'word_id_2', 'relation_type')
    )
    op.create_table('exercise_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('answer_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_results_exercise_id'), 'exercise_results', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_results_user_id'), 'exercise_results', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_results_user_id'), table_name='exercise_results')
    op.drop_index(op.f('ix_exercise_results_exercise_id'), table_name='exercise_results')
    op.drop_table('exercise_results')
    op.drop_table('word_relations')
    op.drop_index(op.f('ix_word_forms_word_id'), table_name='word_forms')
    op.drop_table('word_forms')
    op.drop_index(op.f('ix_verb_conjugations_word_id'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_binyan_id'), table_name='verb_conjugations')
    op.drop_table('verb_conjugations')
    op.drop_table('user_topic_progress')
    op.drop_table('srs_schedule')
    op.drop_index(op.f('ix_srs_reviews_card_id'), table_name='srs_reviews')
    op.drop_table('srs_reviews')
    op.drop_table('root_family_members')
    op.drop_index(op.f('ix_grammar_rules_topic_id'), table_name='grammar_rules')
    op.drop_table('grammar_rules')
    op.drop_index(op.f('ix_exercises_lesson_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_example_sentences_word_id'), table_name='example_sentences')
    op.drop_table('example_sentences')
    op.drop_index(op.f('ix_collocations_word_id'), table_name='collocations')
    op.drop_table('collocations')
    op.drop_index(op.f('ix_words_hebrew'), table_name='words')
    op.drop_table('words')
    op.drop_table('user_skill_progress')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_daily_activity_user_id'), table_name='user_daily_activity')
    op.drop_table('user_daily_activity')
    op.drop_table('topics')
    op.drop_index(op.f('ix_srs_cards_user_id'), table_name='srs_cards')
    op.drop_table('srs_cards')
    op.drop_table('reading_texts')
    op.drop_table('lessons')
    op.drop_table('grammar_topics')
    op.drop_table('dialogues')
    op.drop_table('culture_articles')
    op.drop_table('binyanim')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_index(op.f('ix_root_families_root'), table_name='root_families')
    op.drop_table('root_families')
    op.drop_table('prepositions')
    op.drop_table('nikkud')
    op.drop_table('levels')
    op.drop_table('alphabet_letters')
    op.drop_table('achievement_definitions')
    # ### end Alembic commands ###
