"""Add 500 words across levels 1, 3, 4, 5, 6

Currently all 1215 words sit in level_id=2. This migration populates the
remaining five levels with 100 words each, covering A1 through C2.

Revision ID: 036
Revises: 035
Create Date: 2026-03-01

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "036"
down_revision: Union[str, None] = "035"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ══════════════════════════════════════════════════════════════════════════════
# 500 new words: 100 per level (1, 3, 4, 5, 6)
# ══════════════════════════════════════════════════════════════════════════════

words_table = sa.table(
    "words",
    sa.column("hebrew", sa.String),
    sa.column("transliteration", sa.String),
    sa.column("translation_ru", sa.String),
    sa.column("pos", sa.String),
    sa.column("level_id", sa.Integer),
)

# ── Level 1 (A1) — most basic vocabulary ────────────────────────────────────
# Family, food, colors, numbers, body, animals, house, school, greetings

LEVEL_1_WORDS = [
    # Family (13)
    {"hebrew": "אמא", "transliteration": "Има", "translation_ru": "мама", "pos": "noun", "level_id": 1},
    {"hebrew": "אבא", "transliteration": "Аба", "translation_ru": "папа", "pos": "noun", "level_id": 1},
    {"hebrew": "ילד", "transliteration": "йЕлед", "translation_ru": "мальчик, ребёнок", "pos": "noun", "level_id": 1},
    {"hebrew": "ילדה", "transliteration": "ялдА", "translation_ru": "девочка", "pos": "noun", "level_id": 1},
    {"hebrew": "אח", "transliteration": "ах", "translation_ru": "брат", "pos": "noun", "level_id": 1},
    {"hebrew": "אחות", "transliteration": "ахОт", "translation_ru": "сестра", "pos": "noun", "level_id": 1},
    {"hebrew": "סבא", "transliteration": "сАба", "translation_ru": "дедушка", "pos": "noun", "level_id": 1},
    {"hebrew": "סבתא", "transliteration": "сАвта", "translation_ru": "бабушка", "pos": "noun", "level_id": 1},
    {"hebrew": "בן", "transliteration": "бен", "translation_ru": "сын", "pos": "noun", "level_id": 1},
    {"hebrew": "בת", "transliteration": "бат", "translation_ru": "дочь", "pos": "noun", "level_id": 1},
    {"hebrew": "משפחה", "transliteration": "мишпахА", "translation_ru": "семья", "pos": "noun", "level_id": 1},
    {"hebrew": "בעל", "transliteration": "бАаль", "translation_ru": "муж", "pos": "noun", "level_id": 1},
    {"hebrew": "אישה", "transliteration": "ишА", "translation_ru": "жена; женщина", "pos": "noun", "level_id": 1},
    # Food (11)
    {"hebrew": "לחם", "transliteration": "лЕхем", "translation_ru": "хлеб", "pos": "noun", "level_id": 1},
    {"hebrew": "מים", "transliteration": "мАйим", "translation_ru": "вода", "pos": "noun", "level_id": 1},
    {"hebrew": "חלב", "transliteration": "халАв", "translation_ru": "молоко", "pos": "noun", "level_id": 1},
    {"hebrew": "ביצה", "transliteration": "бейцА", "translation_ru": "яйцо", "pos": "noun", "level_id": 1},
    {"hebrew": "תפוח", "transliteration": "тапУах", "translation_ru": "яблоко", "pos": "noun", "level_id": 1},
    {"hebrew": "בננה", "transliteration": "банАна", "translation_ru": "банан", "pos": "noun", "level_id": 1},
    {"hebrew": "אורז", "transliteration": "Орез", "translation_ru": "рис", "pos": "noun", "level_id": 1},
    {"hebrew": "עוף", "transliteration": "оф", "translation_ru": "курица (мясо); птица", "pos": "noun", "level_id": 1},
    {"hebrew": "דג", "transliteration": "даг", "translation_ru": "рыба", "pos": "noun", "level_id": 1},
    {"hebrew": "סוכר", "transliteration": "сукАр", "translation_ru": "сахар", "pos": "noun", "level_id": 1},
    {"hebrew": "מלח", "transliteration": "мЕлах", "translation_ru": "соль", "pos": "noun", "level_id": 1},
    # Colors (6)
    {"hebrew": "אדום", "transliteration": "адОм", "translation_ru": "красный", "pos": "adj", "level_id": 1},
    {"hebrew": "כחול", "transliteration": "кахОль", "translation_ru": "синий, голубой", "pos": "adj", "level_id": 1},
    {"hebrew": "ירוק", "transliteration": "ярОк", "translation_ru": "зелёный", "pos": "adj", "level_id": 1},
    {"hebrew": "צהוב", "transliteration": "цаhОв", "translation_ru": "жёлтый", "pos": "adj", "level_id": 1},
    {"hebrew": "לבן", "transliteration": "лавАн", "translation_ru": "белый", "pos": "adj", "level_id": 1},
    {"hebrew": "שחור", "transliteration": "шахОр", "translation_ru": "чёрный", "pos": "adj", "level_id": 1},
    # Numbers (5)
    {"hebrew": "אחד", "transliteration": "эхАд", "translation_ru": "один", "pos": "noun", "level_id": 1},
    {"hebrew": "שניים", "transliteration": "шнАйим", "translation_ru": "два", "pos": "noun", "level_id": 1},
    {"hebrew": "שלושה", "transliteration": "шлошА", "translation_ru": "три", "pos": "noun", "level_id": 1},
    {"hebrew": "ארבעה", "transliteration": "арбаА", "translation_ru": "четыре", "pos": "noun", "level_id": 1},
    {"hebrew": "חמישה", "transliteration": "хамишА", "translation_ru": "пять", "pos": "noun", "level_id": 1},
    # Body (9)
    {"hebrew": "ראש", "transliteration": "рош", "translation_ru": "голова", "pos": "noun", "level_id": 1},
    {"hebrew": "יד", "transliteration": "яд", "translation_ru": "рука", "pos": "noun", "level_id": 1},
    {"hebrew": "רגל", "transliteration": "рЕгель", "translation_ru": "нога", "pos": "noun", "level_id": 1},
    {"hebrew": "פה", "transliteration": "пе", "translation_ru": "рот", "pos": "noun", "level_id": 1},
    {"hebrew": "אוזן", "transliteration": "Озен", "translation_ru": "ухо", "pos": "noun", "level_id": 1},
    {"hebrew": "אף", "transliteration": "аф", "translation_ru": "нос", "pos": "noun", "level_id": 1},
    {"hebrew": "בטן", "transliteration": "бЕтен", "translation_ru": "живот", "pos": "noun", "level_id": 1},
    {"hebrew": "גב", "transliteration": "гав", "translation_ru": "спина", "pos": "noun", "level_id": 1},
    {"hebrew": "לב", "transliteration": "лев", "translation_ru": "сердце", "pos": "noun", "level_id": 1},
    # Animals (6)
    {"hebrew": "כלב", "transliteration": "кЕлев", "translation_ru": "собака", "pos": "noun", "level_id": 1},
    {"hebrew": "חתול", "transliteration": "хатУль", "translation_ru": "кот, кошка", "pos": "noun", "level_id": 1},
    {"hebrew": "ציפור", "transliteration": "ципОр", "translation_ru": "птица", "pos": "noun", "level_id": 1},
    {"hebrew": "דוב", "transliteration": "дов", "translation_ru": "медведь", "pos": "noun", "level_id": 1},
    {"hebrew": "סוס", "transliteration": "сус", "translation_ru": "лошадь, конь", "pos": "noun", "level_id": 1},
    {"hebrew": "פרפר", "transliteration": "парпАр", "translation_ru": "бабочка", "pos": "noun", "level_id": 1},
    # House / school (13)
    {"hebrew": "בית", "transliteration": "бАйит", "translation_ru": "дом", "pos": "noun", "level_id": 1},
    {"hebrew": "חדר", "transliteration": "хЕдер", "translation_ru": "комната", "pos": "noun", "level_id": 1},
    {"hebrew": "דלת", "transliteration": "дЕлет", "translation_ru": "дверь", "pos": "noun", "level_id": 1},
    {"hebrew": "חלון", "transliteration": "халОн", "translation_ru": "окно", "pos": "noun", "level_id": 1},
    {"hebrew": "שולחן", "transliteration": "шульхАн", "translation_ru": "стол", "pos": "noun", "level_id": 1},
    {"hebrew": "כיסא", "transliteration": "кисЭ", "translation_ru": "стул", "pos": "noun", "level_id": 1},
    {"hebrew": "מיטה", "transliteration": "митА", "translation_ru": "кровать", "pos": "noun", "level_id": 1},
    {"hebrew": "ספר", "transliteration": "сЕфер", "translation_ru": "книга", "pos": "noun", "level_id": 1},
    {"hebrew": "עט", "transliteration": "эт", "translation_ru": "ручка (для письма)", "pos": "noun", "level_id": 1},
    {"hebrew": "מחברת", "transliteration": "махбЕрет", "translation_ru": "тетрадь", "pos": "noun", "level_id": 1},
    {"hebrew": "מורה", "transliteration": "морЕ", "translation_ru": "учитель", "pos": "noun", "level_id": 1},
    {"hebrew": "תלמיד", "transliteration": "тальмИд", "translation_ru": "ученик", "pos": "noun", "level_id": 1},
    {"hebrew": "כיתה", "transliteration": "китА", "translation_ru": "класс (помещение)", "pos": "noun", "level_id": 1},
    # Basic verbs (14)
    {"hebrew": "לאכול", "transliteration": "леэхОль", "translation_ru": "есть, кушать", "pos": "verb", "level_id": 1},
    {"hebrew": "לשתות", "transliteration": "лиштОт", "translation_ru": "пить", "pos": "verb", "level_id": 1},
    {"hebrew": "לישון", "transliteration": "лишОн", "translation_ru": "спать", "pos": "verb", "level_id": 1},
    {"hebrew": "ללכת", "transliteration": "лалЕхет", "translation_ru": "идти, ходить", "pos": "verb", "level_id": 1},
    {"hebrew": "לכתוב", "transliteration": "лихтОв", "translation_ru": "писать", "pos": "verb", "level_id": 1},
    {"hebrew": "לקרוא", "transliteration": "ликрО", "translation_ru": "читать; звать", "pos": "verb", "level_id": 1},
    {"hebrew": "לדבר", "transliteration": "ледабЭр", "translation_ru": "говорить", "pos": "verb", "level_id": 1},
    {"hebrew": "לשמוע", "transliteration": "лишмОа", "translation_ru": "слышать", "pos": "verb", "level_id": 1},
    {"hebrew": "לראות", "transliteration": "лирОт", "translation_ru": "видеть", "pos": "verb", "level_id": 1},
    {"hebrew": "לתת", "transliteration": "латЕт", "translation_ru": "давать", "pos": "verb", "level_id": 1},
    {"hebrew": "לקחת", "transliteration": "лакАхат", "translation_ru": "брать", "pos": "verb", "level_id": 1},
    {"hebrew": "לשחק", "transliteration": "лесахЭк", "translation_ru": "играть", "pos": "verb", "level_id": 1},
    {"hebrew": "ללמוד", "transliteration": "лильмОд", "translation_ru": "учиться", "pos": "verb", "level_id": 1},
    {"hebrew": "לעבוד", "transliteration": "лаавОд", "translation_ru": "работать", "pos": "verb", "level_id": 1},
    # Basic adjectives (9)
    {"hebrew": "גדול", "transliteration": "гадОль", "translation_ru": "большой", "pos": "adj", "level_id": 1},
    {"hebrew": "קטן", "transliteration": "катАн", "translation_ru": "маленький", "pos": "adj", "level_id": 1},
    {"hebrew": "טוב", "transliteration": "тов", "translation_ru": "хороший", "pos": "adj", "level_id": 1},
    {"hebrew": "רע", "transliteration": "ра", "translation_ru": "плохой", "pos": "adj", "level_id": 1},
    {"hebrew": "חדש", "transliteration": "хадАш", "translation_ru": "новый", "pos": "adj", "level_id": 1},
    {"hebrew": "ישן", "transliteration": "яшАн", "translation_ru": "старый (о предмете)", "pos": "adj", "level_id": 1},
    {"hebrew": "יפה", "transliteration": "яфЕ", "translation_ru": "красивый", "pos": "adj", "level_id": 1},
    {"hebrew": "חם", "transliteration": "хам", "translation_ru": "горячий, жаркий", "pos": "adj", "level_id": 1},
    {"hebrew": "קר", "transliteration": "кар", "translation_ru": "холодный", "pos": "adj", "level_id": 1},
    # Greetings / basic phrases (5) — שלום removed (exists in DB)
    {"hebrew": "תודה", "transliteration": "тодА", "translation_ru": "спасибо", "pos": "noun", "level_id": 1},
    {"hebrew": "בבקשה", "transliteration": "бевакашА", "translation_ru": "пожалуйста", "pos": "adv", "level_id": 1},
    {"hebrew": "סליחה", "transliteration": "слихА", "translation_ru": "извините, простите", "pos": "noun", "level_id": 1},
    {"hebrew": "כן", "transliteration": "кен", "translation_ru": "да", "pos": "adv", "level_id": 1},
    {"hebrew": "לא", "transliteration": "ло", "translation_ru": "нет; не", "pos": "adv", "level_id": 1},
    # Nature basics (5) — ירח removed (exists in DB)
    {"hebrew": "שמש", "transliteration": "шЕмеш", "translation_ru": "солнце", "pos": "noun", "level_id": 1},
    {"hebrew": "שמים", "transliteration": "шамАйим", "translation_ru": "небо", "pos": "noun", "level_id": 1},
    {"hebrew": "ארץ", "transliteration": "Эрец", "translation_ru": "земля; страна", "pos": "noun", "level_id": 1},
    {"hebrew": "עץ", "transliteration": "эц", "translation_ru": "дерево", "pos": "noun", "level_id": 1},
    {"hebrew": "פרח", "transliteration": "пЕрах", "translation_ru": "цветок", "pos": "noun", "level_id": 1},
    # Extra basic words to reach 100 (4)
    {"hebrew": "איש", "transliteration": "иш", "translation_ru": "мужчина; человек", "pos": "noun", "level_id": 1},
    {"hebrew": "חבר", "transliteration": "хавЭр", "translation_ru": "друг", "pos": "noun", "level_id": 1},
    {"hebrew": "שעון", "transliteration": "шаОн", "translation_ru": "часы", "pos": "noun", "level_id": 1},
    {"hebrew": "תמונה", "transliteration": "тмунА", "translation_ru": "картина; фотография", "pos": "noun", "level_id": 1},
]

# ── Level 3 (B1) — intermediate ─────────────────────────────────────────────
# Work, health, travel, media, emotions, nature, society

LEVEL_3_WORDS = [
    # Work (10)
    {"hebrew": "משרד", "transliteration": "мисрАд", "translation_ru": "офис; министерство", "pos": "noun", "level_id": 3},
    {"hebrew": "שכיר", "transliteration": "сахИр", "translation_ru": "наёмный работник", "pos": "noun", "level_id": 3},
    {"hebrew": "משימה", "transliteration": "мешимА", "translation_ru": "задание, задача", "pos": "noun", "level_id": 3},
    {"hebrew": "ישיבה", "transliteration": "ешивА", "translation_ru": "заседание; ешива", "pos": "noun", "level_id": 3},
    {"hebrew": "עמלה", "transliteration": "амалА", "translation_ru": "комиссия (оплата)", "pos": "noun", "level_id": 3},
    {"hebrew": "פרויקט", "transliteration": "проЕкт", "translation_ru": "проект", "pos": "noun", "level_id": 3},
    {"hebrew": "לפתור", "transliteration": "лифтОр", "translation_ru": "решать (задачу)", "pos": "verb", "level_id": 3},
    {"hebrew": "לנצל", "transliteration": "ленацЭль", "translation_ru": "использовать; эксплуатировать", "pos": "verb", "level_id": 3},
    {"hebrew": "להעסיק", "transliteration": "леhаасИк", "translation_ru": "нанимать, занимать (работой)", "pos": "verb", "level_id": 3},
    {"hebrew": "ראיון עבודה", "transliteration": "реайОн аводА", "translation_ru": "собеседование", "pos": "noun", "level_id": 3},
    # Health (10)
    {"hebrew": "רופא", "transliteration": "рофЭ", "translation_ru": "врач", "pos": "noun", "level_id": 3},
    {"hebrew": "מרפאה", "transliteration": "мирпаА", "translation_ru": "клиника, поликлиника", "pos": "noun", "level_id": 3},
    {"hebrew": "תרופה", "transliteration": "труфА", "translation_ru": "лекарство", "pos": "noun", "level_id": 3},
    {"hebrew": "מחלה", "transliteration": "махалА", "translation_ru": "болезнь", "pos": "noun", "level_id": 3},
    {"hebrew": "כאב ראש", "transliteration": "кеЭв рош", "translation_ru": "головная боль", "pos": "noun", "level_id": 3},
    {"hebrew": "חום", "transliteration": "хом", "translation_ru": "жар, температура; тепло", "pos": "noun", "level_id": 3},
    {"hebrew": "בריא", "transliteration": "барИ", "translation_ru": "здоровый", "pos": "adj", "level_id": 3},
    {"hebrew": "חולה", "transliteration": "холЕ", "translation_ru": "больной", "pos": "adj", "level_id": 3},
    {"hebrew": "להתאושש", "transliteration": "леhитошЭш", "translation_ru": "выздоравливать", "pos": "verb", "level_id": 3},
    {"hebrew": "אלרגיה", "transliteration": "алЕргия", "translation_ru": "аллергия", "pos": "noun", "level_id": 3},
    # Travel (10)
    {"hebrew": "מזוודה", "transliteration": "мизвадА", "translation_ru": "чемодан", "pos": "noun", "level_id": 3},
    {"hebrew": "דרכון", "transliteration": "даркОн", "translation_ru": "паспорт", "pos": "noun", "level_id": 3},
    {"hebrew": "מלון", "transliteration": "малОн", "translation_ru": "гостиница", "pos": "noun", "level_id": 3},
    {"hebrew": "תחנה", "transliteration": "таханА", "translation_ru": "станция, остановка", "pos": "noun", "level_id": 3},
    {"hebrew": "נסיעה", "transliteration": "несиА", "translation_ru": "поездка", "pos": "noun", "level_id": 3},
    {"hebrew": "מפה", "transliteration": "мАпа", "translation_ru": "карта (географическая)", "pos": "noun", "level_id": 3},
    {"hebrew": "כביש", "transliteration": "квИш", "translation_ru": "шоссе, дорога", "pos": "noun", "level_id": 3},
    {"hebrew": "שדה תעופה", "transliteration": "сдЕ теуфА", "translation_ru": "аэропорт", "pos": "noun", "level_id": 3},
    {"hebrew": "טיול מאורגן", "transliteration": "тиУль меургАн", "translation_ru": "организованная экскурсия", "pos": "noun", "level_id": 3},
    {"hebrew": "ויזה", "transliteration": "вИза", "translation_ru": "виза", "pos": "noun", "level_id": 3},
    # Media (10)
    {"hebrew": "חדשות", "transliteration": "хадашОт", "translation_ru": "новости", "pos": "noun", "level_id": 3},
    {"hebrew": "כתבה", "transliteration": "катавА", "translation_ru": "статья; репортаж", "pos": "noun", "level_id": 3},
    {"hebrew": "רדיו", "transliteration": "рАдио", "translation_ru": "радио", "pos": "noun", "level_id": 3},
    {"hebrew": "פרסומת", "transliteration": "пирсОмет", "translation_ru": "реклама (объявление)", "pos": "noun", "level_id": 3},
    {"hebrew": "שידור חי", "transliteration": "шидУр хай", "translation_ru": "прямой эфир", "pos": "noun", "level_id": 3},
    {"hebrew": "לשדר", "transliteration": "лешадЭр", "translation_ru": "транслировать", "pos": "verb", "level_id": 3},
    {"hebrew": "קריין", "transliteration": "карьЯн", "translation_ru": "диктор", "pos": "noun", "level_id": 3},
    {"hebrew": "כותרת", "transliteration": "котЕрет", "translation_ru": "заголовок", "pos": "noun", "level_id": 3},
    {"hebrew": "ראיון", "transliteration": "реайОн", "translation_ru": "интервью", "pos": "noun", "level_id": 3},
    {"hebrew": "תוכנית טלוויזיה", "transliteration": "тохнИт телевИзия", "translation_ru": "телепередача", "pos": "noun", "level_id": 3},
    # Emotions (10)
    {"hebrew": "שמח", "transliteration": "самЕах", "translation_ru": "счастливый, радостный", "pos": "adj", "level_id": 3},
    {"hebrew": "עצוב", "transliteration": "ацУв", "translation_ru": "грустный", "pos": "adj", "level_id": 3},
    {"hebrew": "כועס", "transliteration": "коЭс", "translation_ru": "сердитый", "pos": "adj", "level_id": 3},
    {"hebrew": "מפחד", "transliteration": "мефахЭд", "translation_ru": "боящийся, испуганный", "pos": "adj", "level_id": 3},
    {"hebrew": "גאה", "transliteration": "геЭ", "translation_ru": "гордый", "pos": "adj", "level_id": 3},
    {"hebrew": "מקנא", "transliteration": "меканЭ", "translation_ru": "ревнивый, завидующий", "pos": "adj", "level_id": 3},
    {"hebrew": "מאוהב", "transliteration": "меухАв", "translation_ru": "влюблённый", "pos": "adj", "level_id": 3},
    {"hebrew": "מודאג", "transliteration": "мудАг", "translation_ru": "обеспокоенный", "pos": "adj", "level_id": 3},
    {"hebrew": "להתרגש", "transliteration": "леhитрагЭш", "translation_ru": "волноваться, быть растроганным", "pos": "verb", "level_id": 3},
    {"hebrew": "להתאכזב", "transliteration": "леhитахзЭв", "translation_ru": "разочароваться", "pos": "verb", "level_id": 3},
    # Nature (10)
    {"hebrew": "הר", "transliteration": "hар", "translation_ru": "гора", "pos": "noun", "level_id": 3},
    {"hebrew": "נהר", "transliteration": "наhАр", "translation_ru": "река", "pos": "noun", "level_id": 3},
    {"hebrew": "ים", "transliteration": "ям", "translation_ru": "море", "pos": "noun", "level_id": 3},
    {"hebrew": "מדבר", "transliteration": "мидбАр", "translation_ru": "пустыня", "pos": "noun", "level_id": 3},
    {"hebrew": "יער", "transliteration": "яАр", "translation_ru": "лес", "pos": "noun", "level_id": 3},
    {"hebrew": "חוף", "transliteration": "хоф", "translation_ru": "берег, пляж", "pos": "noun", "level_id": 3},
    {"hebrew": "אקלים", "transliteration": "аклИм", "translation_ru": "климат", "pos": "noun", "level_id": 3},
    {"hebrew": "רעש אדמה", "transliteration": "рАаш адамА", "translation_ru": "землетрясение", "pos": "noun", "level_id": 3},
    {"hebrew": "זריחה", "transliteration": "зрихА", "translation_ru": "рассвет, восход", "pos": "noun", "level_id": 3},
    {"hebrew": "שקיעה", "transliteration": "шкиА", "translation_ru": "закат", "pos": "noun", "level_id": 3},
    # Society (10)
    {"hebrew": "חברה", "transliteration": "хеврА", "translation_ru": "общество; компания", "pos": "noun", "level_id": 3},
    {"hebrew": "שכן", "transliteration": "шахЭн", "translation_ru": "сосед", "pos": "noun", "level_id": 3},
    {"hebrew": "אזרחי", "transliteration": "эзрахИ", "translation_ru": "гражданский", "pos": "adj", "level_id": 3},
    {"hebrew": "מתנדב", "transliteration": "митнадЭв", "translation_ru": "волонтёр, доброволец", "pos": "noun", "level_id": 3},
    {"hebrew": "עולה", "transliteration": "олЕ", "translation_ru": "репатриант", "pos": "noun", "level_id": 3},
    {"hebrew": "עדה", "transliteration": "эдА", "translation_ru": "община, этническая группа", "pos": "noun", "level_id": 3},
    {"hebrew": "מושב", "transliteration": "мошАв", "translation_ru": "мошав (сельское поселение)", "pos": "noun", "level_id": 3},
    {"hebrew": "קיבוץ", "transliteration": "кибУц", "translation_ru": "кибуц", "pos": "noun", "level_id": 3},
    {"hebrew": "עלייה", "transliteration": "алиЯ", "translation_ru": "репатриация", "pos": "noun", "level_id": 3},
    {"hebrew": "תושב", "transliteration": "тошАв", "translation_ru": "житель, резидент", "pos": "noun", "level_id": 3},
    # Everyday life (20)
    {"hebrew": "דירה", "transliteration": "дирА", "translation_ru": "квартира", "pos": "noun", "level_id": 3},
    {"hebrew": "שכירות", "transliteration": "схирУт", "translation_ru": "аренда", "pos": "noun", "level_id": 3},
    {"hebrew": "משכורת", "transliteration": "маскОрет", "translation_ru": "зарплата", "pos": "noun", "level_id": 3},
    {"hebrew": "חשבון", "transliteration": "хешбОн", "translation_ru": "счёт (в банке, ресторане)", "pos": "noun", "level_id": 3},
    {"hebrew": "הלוואה", "transliteration": "hалваА", "translation_ru": "ссуда, кредит", "pos": "noun", "level_id": 3},
    {"hebrew": "לחסוך", "transliteration": "лахсОх", "translation_ru": "экономить, копить", "pos": "verb", "level_id": 3},
    {"hebrew": "חנות", "transliteration": "ханУт", "translation_ru": "магазин", "pos": "noun", "level_id": 3},
    {"hebrew": "קניון", "transliteration": "каньОн", "translation_ru": "торговый центр", "pos": "noun", "level_id": 3},
    {"hebrew": "להחליף", "transliteration": "леhахлИф", "translation_ru": "обменивать, заменять", "pos": "verb", "level_id": 3},
    {"hebrew": "להחזיר", "transliteration": "леhахзИр", "translation_ru": "возвращать", "pos": "verb", "level_id": 3},
    {"hebrew": "מתאים", "transliteration": "матъИм", "translation_ru": "подходящий", "pos": "adj", "level_id": 3},
    {"hebrew": "נוח", "transliteration": "нОах", "translation_ru": "удобный", "pos": "adj", "level_id": 3},
    {"hebrew": "דחוף", "transliteration": "дахУф", "translation_ru": "срочный", "pos": "adj", "level_id": 3},
    {"hebrew": "מגוון", "transliteration": "мегувАн", "translation_ru": "разнообразный", "pos": "adj", "level_id": 3},
    {"hebrew": "מורגש", "transliteration": "мургАш", "translation_ru": "ощутимый", "pos": "adj", "level_id": 3},
    {"hebrew": "מכתב", "transliteration": "михтАв", "translation_ru": "письмо", "pos": "noun", "level_id": 3},
    {"hebrew": "מרכז", "transliteration": "меркАз", "translation_ru": "центр", "pos": "noun", "level_id": 3},
    {"hebrew": "תור", "transliteration": "тор", "translation_ru": "очередь; запись (на приём)", "pos": "noun", "level_id": 3},
    {"hebrew": "רמזור", "transliteration": "рамзОр", "translation_ru": "светофор", "pos": "noun", "level_id": 3},
    {"hebrew": "מדרכה", "transliteration": "мидрахА", "translation_ru": "тротуар", "pos": "noun", "level_id": 3},
    # Additional B1 words (10)
    {"hebrew": "אוטובוס", "transliteration": "отобУс", "translation_ru": "автобус", "pos": "noun", "level_id": 3},
    {"hebrew": "רכבת", "transliteration": "ракЕвет", "translation_ru": "поезд", "pos": "noun", "level_id": 3},
    {"hebrew": "מונית", "transliteration": "монИт", "translation_ru": "такси", "pos": "noun", "level_id": 3},
    {"hebrew": "בית חולים", "transliteration": "бейт холИм", "translation_ru": "больница", "pos": "noun", "level_id": 3},
    {"hebrew": "בית ספר", "transliteration": "бейт сЕфер", "translation_ru": "школа", "pos": "noun", "level_id": 3},
    {"hebrew": "אוניברסיטה", "transliteration": "университА", "translation_ru": "университет", "pos": "noun", "level_id": 3},
    {"hebrew": "מסעדה", "transliteration": "мисъадА", "translation_ru": "ресторан", "pos": "noun", "level_id": 3},
    {"hebrew": "להזהיר", "transliteration": "леhазhИр", "translation_ru": "предупреждать", "pos": "verb", "level_id": 3},
    {"hebrew": "להמליץ", "transliteration": "леhамлИц", "translation_ru": "рекомендовать", "pos": "verb", "level_id": 3},
    {"hebrew": "לארגן", "transliteration": "леаргЭн", "translation_ru": "организовать", "pos": "verb", "level_id": 3},
]

# ── Level 4 (B2) — upper intermediate ───────────────────────────────────────
# Politics, economy, law, science, abstract concepts

LEVEL_4_WORDS = [
    # Politics (12)
    {"hebrew": "כנסת", "transliteration": "кнЕсет", "translation_ru": "Кнессет (парламент)", "pos": "noun", "level_id": 4},
    {"hebrew": "חוק יסוד", "transliteration": "хок есОд", "translation_ru": "основной закон", "pos": "noun", "level_id": 4},
    {"hebrew": "אופוזיציה", "transliteration": "опозИция", "translation_ru": "оппозиция", "pos": "noun", "level_id": 4},
    {"hebrew": "מפלגה", "transliteration": "мифлагА", "translation_ru": "партия (политическая)", "pos": "noun", "level_id": 4},
    {"hebrew": "חקיקה", "transliteration": "хакикА", "translation_ru": "законодательство", "pos": "noun", "level_id": 4},
    {"hebrew": "פליט", "transliteration": "палИт", "translation_ru": "беженец", "pos": "noun", "level_id": 4},
    {"hebrew": "לחוקק", "transliteration": "лехокЭк", "translation_ru": "законодательствовать", "pos": "verb", "level_id": 4},
    {"hebrew": "קולות", "transliteration": "колОт", "translation_ru": "голоса (на выборах)", "pos": "noun", "level_id": 4},
    {"hebrew": "קמפיין בחירות", "transliteration": "кампЕйн бехирОт", "translation_ru": "предвыборная кампания", "pos": "noun", "level_id": 4},
    {"hebrew": "שר", "transliteration": "сар", "translation_ru": "министр", "pos": "noun", "level_id": 4},
    {"hebrew": "ח\"כ", "transliteration": "хак", "translation_ru": "депутат Кнессета", "pos": "noun", "level_id": 4},
    {"hebrew": "ראש ממשלה", "transliteration": "рош мемшалА", "translation_ru": "премьер-министр", "pos": "noun", "level_id": 4},
    # Economy (12)
    {"hebrew": "אינפלציה", "transliteration": "инфлЯция", "translation_ru": "инфляция", "pos": "noun", "level_id": 4},
    {"hebrew": "מיתון", "transliteration": "митУн", "translation_ru": "рецессия", "pos": "noun", "level_id": 4},
    {"hebrew": "יבוא", "transliteration": "йевУ", "translation_ru": "импорт", "pos": "noun", "level_id": 4},
    {"hebrew": "בורסה", "transliteration": "бУрса", "translation_ru": "биржа", "pos": "noun", "level_id": 4},
    {"hebrew": "תמ\"ג", "transliteration": "тамАг", "translation_ru": "ВВП", "pos": "noun", "level_id": 4},
    {"hebrew": "מכרז", "transliteration": "михрАз", "translation_ru": "тендер, конкурс", "pos": "noun", "level_id": 4},
    {"hebrew": "יזם", "transliteration": "язАм", "translation_ru": "предприниматель", "pos": "noun", "level_id": 4},
    {"hebrew": "להפריט", "transliteration": "леhафрИт", "translation_ru": "приватизировать", "pos": "verb", "level_id": 4},
    {"hebrew": "גירעון", "transliteration": "гираОн", "translation_ru": "дефицит", "pos": "noun", "level_id": 4},
    {"hebrew": "עודף", "transliteration": "одЭф", "translation_ru": "излишек, профицит", "pos": "noun", "level_id": 4},
    {"hebrew": "מדד המחירים", "transliteration": "мадАд hа-мехирИм", "translation_ru": "индекс цен", "pos": "noun", "level_id": 4},
    {"hebrew": "משכנתא", "transliteration": "машкантА", "translation_ru": "ипотека", "pos": "noun", "level_id": 4},
    # Law (10)
    {"hebrew": "משפט", "transliteration": "мишпАт", "translation_ru": "суд; предложение (грамм.)", "pos": "noun", "level_id": 4},
    {"hebrew": "נאשם", "transliteration": "неэшАм", "translation_ru": "подсудимый, обвиняемый", "pos": "noun", "level_id": 4},
    {"hebrew": "פסק דין", "transliteration": "псАк дин", "translation_ru": "приговор, судебное решение", "pos": "noun", "level_id": 4},
    {"hebrew": "ערעור", "transliteration": "ирУр", "translation_ru": "апелляция", "pos": "noun", "level_id": 4},
    {"hebrew": "עבירה", "transliteration": "аверА", "translation_ru": "правонарушение", "pos": "noun", "level_id": 4},
    {"hebrew": "חפות", "transliteration": "хафУт", "translation_ru": "невиновность", "pos": "noun", "level_id": 4},
    {"hebrew": "להרשיע", "transliteration": "леhаршИа", "translation_ru": "признать виновным", "pos": "verb", "level_id": 4},
    {"hebrew": "לזכות", "transliteration": "лезакОт", "translation_ru": "оправдать (в суде)", "pos": "verb", "level_id": 4},
    {"hebrew": "תובע", "transliteration": "товЭа", "translation_ru": "прокурор; истец", "pos": "noun", "level_id": 4},
    {"hebrew": "סנגור", "transliteration": "санегОр", "translation_ru": "защитник (адвокат)", "pos": "noun", "level_id": 4},
    # Science (10)
    {"hebrew": "מעבדה", "transliteration": "маабадА", "translation_ru": "лаборатория", "pos": "noun", "level_id": 4},
    {"hebrew": "תיאוריה", "transliteration": "теОрия", "translation_ru": "теория", "pos": "noun", "level_id": 4},
    {"hebrew": "השערה", "transliteration": "hашаарА", "translation_ru": "гипотеза", "pos": "noun", "level_id": 4},
    {"hebrew": "ממצא", "transliteration": "мимцА", "translation_ru": "находка, вывод (научный)", "pos": "noun", "level_id": 4},
    {"hebrew": "נתונים", "transliteration": "нетунИм", "translation_ru": "данные", "pos": "noun", "level_id": 4},
    {"hebrew": "לנסות", "transliteration": "ленасОт", "translation_ru": "пробовать, пытаться", "pos": "verb", "level_id": 4},
    {"hebrew": "להפריך", "transliteration": "леhафрИх", "translation_ru": "опровергать", "pos": "verb", "level_id": 4},
    {"hebrew": "משתנה", "transliteration": "миштанЕ", "translation_ru": "переменная (научн.)", "pos": "noun", "level_id": 4},
    {"hebrew": "מדגם", "transliteration": "мидгАм", "translation_ru": "выборка", "pos": "noun", "level_id": 4},
    {"hebrew": "סטייה", "transliteration": "стиЯ", "translation_ru": "отклонение", "pos": "noun", "level_id": 4},
    # Abstract concepts (16)
    {"hebrew": "מציאות", "transliteration": "мециУт", "translation_ru": "реальность, действительность", "pos": "noun", "level_id": 4},
    {"hebrew": "תפיסה", "transliteration": "тфисА", "translation_ru": "восприятие; концепция", "pos": "noun", "level_id": 4},
    {"hebrew": "מודעות", "transliteration": "мудаУт", "translation_ru": "осознанность", "pos": "noun", "level_id": 4},
    {"hebrew": "השראה", "transliteration": "hашраА", "translation_ru": "вдохновение", "pos": "noun", "level_id": 4},
    {"hebrew": "מוסר", "transliteration": "мусАр", "translation_ru": "мораль, нравственность", "pos": "noun", "level_id": 4},
    {"hebrew": "סתירה", "transliteration": "стирА", "translation_ru": "противоречие", "pos": "noun", "level_id": 4},
    {"hebrew": "מורכבות", "transliteration": "муркавУт", "translation_ru": "сложность, комплексность", "pos": "noun", "level_id": 4},
    {"hebrew": "הקשר", "transliteration": "hЕкшер", "translation_ru": "контекст", "pos": "noun", "level_id": 4},
    {"hebrew": "מהות", "transliteration": "маhУт", "translation_ru": "сущность", "pos": "noun", "level_id": 4},
    {"hebrew": "זהות", "transliteration": "зеhУт", "translation_ru": "идентичность", "pos": "noun", "level_id": 4},
    {"hebrew": "מגמה", "transliteration": "мегамА", "translation_ru": "тенденция", "pos": "noun", "level_id": 4},
    {"hebrew": "השלכה", "transliteration": "hашлахА", "translation_ru": "последствие", "pos": "noun", "level_id": 4},
    {"hebrew": "מהותי", "transliteration": "маhутИ", "translation_ru": "существенный", "pos": "adj", "level_id": 4},
    {"hebrew": "מופשט", "transliteration": "муфшАт", "translation_ru": "абстрактный", "pos": "adj", "level_id": 4},
    {"hebrew": "יחסי", "transliteration": "яхасИ", "translation_ru": "относительный", "pos": "adj", "level_id": 4},
    {"hebrew": "מוחלט", "transliteration": "мухлАт", "translation_ru": "абсолютный", "pos": "adj", "level_id": 4},
    # Upper-intermediate adjectives & misc (8)
    {"hebrew": "סובייקטיבי", "transliteration": "субъектИви", "translation_ru": "субъективный", "pos": "adj", "level_id": 4},
    {"hebrew": "רלוונטי", "transliteration": "релевАнти", "translation_ru": "релевантный", "pos": "adj", "level_id": 4},
    {"hebrew": "תקדים", "transliteration": "такдИм", "translation_ru": "прецедент", "pos": "noun", "level_id": 4},
    {"hebrew": "פשרה", "transliteration": "пшарА", "translation_ru": "компромисс", "pos": "noun", "level_id": 4},
    {"hebrew": "עימות", "transliteration": "имУт", "translation_ru": "конфронтация", "pos": "noun", "level_id": 4},
    {"hebrew": "גישור", "transliteration": "гишУр", "translation_ru": "посредничество", "pos": "noun", "level_id": 4},
    {"hebrew": "שחיתות", "transliteration": "шхитУт", "translation_ru": "коррупция", "pos": "noun", "level_id": 4},
    {"hebrew": "שקיפות", "transliteration": "шкифУт", "translation_ru": "прозрачность", "pos": "noun", "level_id": 4},
    # Upper-intermediate verbs (10)
    {"hebrew": "לנתח", "transliteration": "ленатЭах", "translation_ru": "анализировать; оперировать", "pos": "verb", "level_id": 4},
    {"hebrew": "לגבש", "transliteration": "легабЭш", "translation_ru": "формировать, кристаллизовать", "pos": "verb", "level_id": 4},
    {"hebrew": "ליישם", "transliteration": "лейашЭм", "translation_ru": "применять, реализовывать", "pos": "verb", "level_id": 4},
    {"hebrew": "לשקף", "transliteration": "лешакЭф", "translation_ru": "отражать", "pos": "verb", "level_id": 4},
    {"hebrew": "להקצות", "transliteration": "леhакцОт", "translation_ru": "выделять, распределять", "pos": "verb", "level_id": 4},
    {"hebrew": "להתמקד", "transliteration": "леhитмакЭд", "translation_ru": "сосредоточиться", "pos": "verb", "level_id": 4},
    {"hebrew": "לסכל", "transliteration": "лесакЭль", "translation_ru": "срывать, предотвращать", "pos": "verb", "level_id": 4},
    {"hebrew": "להסדיר", "transliteration": "леhасдИр", "translation_ru": "урегулировать", "pos": "verb", "level_id": 4},
    {"hebrew": "לאכוף", "transliteration": "леэхОф", "translation_ru": "обеспечивать выполнение (закона)", "pos": "verb", "level_id": 4},
    {"hebrew": "לגנוז", "transliteration": "лигнОз", "translation_ru": "сдать в архив; отклонить (законопроект)", "pos": "verb", "level_id": 4},
    # Additional B2 words (22)
    {"hebrew": "הסלמה", "transliteration": "hасламА", "translation_ru": "эскалация", "pos": "noun", "level_id": 4},
    {"hebrew": "דו-קיום", "transliteration": "ду-киЮм", "translation_ru": "сосуществование", "pos": "noun", "level_id": 4},
    {"hebrew": "ריבונות", "transliteration": "рибонУт", "translation_ru": "суверенитет", "pos": "noun", "level_id": 4},
    {"hebrew": "הפרטה", "transliteration": "hафратА", "translation_ru": "приватизация", "pos": "noun", "level_id": 4},
    {"hebrew": "הלאמה", "transliteration": "hалъамА", "translation_ru": "национализация", "pos": "noun", "level_id": 4},
    {"hebrew": "ביזור", "transliteration": "бизУр", "translation_ru": "децентрализация", "pos": "noun", "level_id": 4},
    {"hebrew": "אוטונומיה", "transliteration": "автонОмия", "translation_ru": "автономия", "pos": "noun", "level_id": 4},
    {"hebrew": "הגירה", "transliteration": "hагирА", "translation_ru": "миграция", "pos": "noun", "level_id": 4},
    {"hebrew": "מניפולציה", "transliteration": "манипулЯция", "translation_ru": "манипуляция", "pos": "noun", "level_id": 4},
    {"hebrew": "פרופגנדה", "transliteration": "пропагАнда", "translation_ru": "пространства", "pos": "noun", "level_id": 4},
    {"hebrew": "צנזורה", "transliteration": "цензУра", "translation_ru": "цензура", "pos": "noun", "level_id": 4},
    {"hebrew": "לסנן", "transliteration": "лесанЭн", "translation_ru": "фильтровать", "pos": "verb", "level_id": 4},
    {"hebrew": "להחרים", "transliteration": "леhахрИм", "translation_ru": "бойкотировать; конфисковать", "pos": "verb", "level_id": 4},
    {"hebrew": "להפלות", "transliteration": "леhафлОт", "translation_ru": "дискриминировать", "pos": "verb", "level_id": 4},
    {"hebrew": "אחריותיות", "transliteration": "ахраютиЮт", "translation_ru": "подотчётность", "pos": "noun", "level_id": 4},
    {"hebrew": "עצומה", "transliteration": "ацумА", "translation_ru": "петиция", "pos": "noun", "level_id": 4},
    {"hebrew": "רגולציה", "transliteration": "регулЯция", "translation_ru": "регулирование", "pos": "noun", "level_id": 4},
    {"hebrew": "סובסידיה", "transliteration": "субсИдия", "translation_ru": "субсидия", "pos": "noun", "level_id": 4},
    {"hebrew": "אמברגו", "transliteration": "эмбАрго", "translation_ru": "эмбарго", "pos": "noun", "level_id": 4},
    {"hebrew": "רטרואקטיבי", "transliteration": "ретроактИви", "translation_ru": "ретроактивный", "pos": "adj", "level_id": 4},
    {"hebrew": "קונסטיטוציוני", "transliteration": "конституциОни", "translation_ru": "конституционный", "pos": "adj", "level_id": 4},
    {"hebrew": "נורמטיבי", "transliteration": "нормативИ", "translation_ru": "нормативный", "pos": "adj", "level_id": 4},
]

# ── Level 5 (C1) — advanced ─────────────────────────────────────────────────
# Academic, literary, philosophical, formal register

LEVEL_5_WORDS = [
    # Academic / scholarly (15)
    {"hebrew": "פרדיגמה", "transliteration": "парадИгма", "translation_ru": "парадигма", "pos": "noun", "level_id": 5},
    {"hebrew": "דיסציפלינה", "transliteration": "дисциплИна", "translation_ru": "дисциплина (научная)", "pos": "noun", "level_id": 5},
    {"hebrew": "מתודולוגיה", "transliteration": "методолОгия", "translation_ru": "методология", "pos": "noun", "level_id": 5},
    {"hebrew": "אמפירי", "transliteration": "эмпИри", "translation_ru": "эмпирический", "pos": "adj", "level_id": 5},
    {"hebrew": "אפיסטמולוגיה", "transliteration": "эпистемолОгия", "translation_ru": "эпистемология", "pos": "noun", "level_id": 5},
    {"hebrew": "דיסרטציה", "transliteration": "дисертАция", "translation_ru": "диссертация", "pos": "noun", "level_id": 5},
    {"hebrew": "סינתזה", "transliteration": "синтЕза", "translation_ru": "синтез", "pos": "noun", "level_id": 5},
    {"hebrew": "אנלוגיה", "transliteration": "аналОгия", "translation_ru": "аналогия", "pos": "noun", "level_id": 5},
    {"hebrew": "קורלציה", "transliteration": "корелЯция", "translation_ru": "корреляция", "pos": "noun", "level_id": 5},
    {"hebrew": "קריטריון", "transliteration": "критЕрион", "translation_ru": "критерий", "pos": "noun", "level_id": 5},
    {"hebrew": "היבט", "transliteration": "hибЭт", "translation_ru": "аспект", "pos": "noun", "level_id": 5},
    {"hebrew": "טיעון", "transliteration": "тиУн", "translation_ru": "аргумент, довод", "pos": "noun", "level_id": 5},
    {"hebrew": "הנמקה", "transliteration": "hанмакА", "translation_ru": "обоснование, мотивировка", "pos": "noun", "level_id": 5},
    {"hebrew": "פרשנות", "transliteration": "паршанУт", "translation_ru": "интерпретация, толкование", "pos": "noun", "level_id": 5},
    {"hebrew": "הפשטה", "transliteration": "hафшатА", "translation_ru": "абстракция, обобщение", "pos": "noun", "level_id": 5},
    # Literary (10)
    {"hebrew": "מטאפורה", "transliteration": "метАфора", "translation_ru": "метафора", "pos": "noun", "level_id": 5},
    {"hebrew": "אלגוריה", "transliteration": "алегОрия", "translation_ru": "аллегория", "pos": "noun", "level_id": 5},
    {"hebrew": "סאטירה", "transliteration": "сатИра", "translation_ru": "сатира", "pos": "noun", "level_id": 5},
    {"hebrew": "פרוזה", "transliteration": "прОза", "translation_ru": "проза", "pos": "noun", "level_id": 5},
    {"hebrew": "שירה", "transliteration": "ширА", "translation_ru": "поэзия", "pos": "noun", "level_id": 5},
    {"hebrew": "עלילה", "transliteration": "алилА", "translation_ru": "сюжет", "pos": "noun", "level_id": 5},
    {"hebrew": "רטוריקה", "transliteration": "ретОрика", "translation_ru": "риторика", "pos": "noun", "level_id": 5},
    {"hebrew": "אירוניה", "transliteration": "ирОния", "translation_ru": "ирония", "pos": "noun", "level_id": 5},
    {"hebrew": "פתוס", "transliteration": "пАтос", "translation_ru": "пафос", "pos": "noun", "level_id": 5},
    {"hebrew": "מליצה", "transliteration": "мелицА", "translation_ru": "красноречие; вычурный стиль", "pos": "noun", "level_id": 5},
    # Philosophical (10)
    {"hebrew": "אונטולוגיה", "transliteration": "онтолОгия", "translation_ru": "онтология", "pos": "noun", "level_id": 5},
    {"hebrew": "דטרמיניזם", "transliteration": "детерминИзм", "translation_ru": "детерминизм", "pos": "noun", "level_id": 5},
    {"hebrew": "רלטיביזם", "transliteration": "релятивИзм", "translation_ru": "релятивизм", "pos": "noun", "level_id": 5},
    {"hebrew": "אתיקה", "transliteration": "Этика", "translation_ru": "этика", "pos": "noun", "level_id": 5},
    {"hebrew": "דילמה", "transliteration": "дилЕма", "translation_ru": "дилемма", "pos": "noun", "level_id": 5},
    {"hebrew": "פרדוקס", "transliteration": "парадОкс", "translation_ru": "парадокс", "pos": "noun", "level_id": 5},
    {"hebrew": "אוטופיה", "transliteration": "утОпия", "translation_ru": "утопия", "pos": "noun", "level_id": 5},
    {"hebrew": "דיאלקטיקה", "transliteration": "диалЕктика", "translation_ru": "диалектика", "pos": "noun", "level_id": 5},
    {"hebrew": "אקסיומה", "transliteration": "аксиОма", "translation_ru": "аксиома", "pos": "noun", "level_id": 5},
    {"hebrew": "תזה", "transliteration": "тЕза", "translation_ru": "тезис", "pos": "noun", "level_id": 5},
    # Formal register verbs (15)
    {"hebrew": "לגלם", "transliteration": "легалЭм", "translation_ru": "воплощать, олицетворять", "pos": "verb", "level_id": 5},
    {"hebrew": "להתוות", "transliteration": "леhитвОт", "translation_ru": "намечать (курс); очерчивать", "pos": "verb", "level_id": 5},
    {"hebrew": "לאמוד", "transliteration": "леэмОд", "translation_ru": "оценивать, определять масштаб", "pos": "verb", "level_id": 5},
    {"hebrew": "להשתית", "transliteration": "леhаштИт", "translation_ru": "основывать, строить (базу)", "pos": "verb", "level_id": 5},
    {"hebrew": "לנבוע", "transliteration": "линбОа", "translation_ru": "проистекать, вытекать", "pos": "verb", "level_id": 5},
    {"hebrew": "להטמיע", "transliteration": "леhатмИа", "translation_ru": "внедрять, усваивать", "pos": "verb", "level_id": 5},
    {"hebrew": "לחולל", "transliteration": "лехолЭль", "translation_ru": "порождать, вызывать (перемены)", "pos": "verb", "level_id": 5},
    {"hebrew": "לגזור", "transliteration": "лигзОр", "translation_ru": "выводить (заключение); отрезать", "pos": "verb", "level_id": 5},
    {"hebrew": "להניב", "transliteration": "леhанИв", "translation_ru": "приносить (плоды, результат)", "pos": "verb", "level_id": 5},
    {"hebrew": "לדגול", "transliteration": "лидгОль", "translation_ru": "стоять за (идею), отстаивать", "pos": "verb", "level_id": 5},
    {"hebrew": "להתגבש", "transliteration": "леhитгабЭш", "translation_ru": "формироваться, кристаллизоваться", "pos": "verb", "level_id": 5},
    {"hebrew": "לשזור", "transliteration": "лишзОр", "translation_ru": "вплетать, переплетать", "pos": "verb", "level_id": 5},
    {"hebrew": "להיטיב", "transliteration": "леhейтИв", "translation_ru": "улучшать; уметь (книжн.)", "pos": "verb", "level_id": 5},
    {"hebrew": "לסלף", "transliteration": "лесалЭф", "translation_ru": "искажать, фальсифицировать", "pos": "verb", "level_id": 5},
    {"hebrew": "לעוות", "transliteration": "леавЭт", "translation_ru": "искривлять, деформировать", "pos": "verb", "level_id": 5},
    # Formal adjectives (12)
    {"hebrew": "מובהק", "transliteration": "мувhАк", "translation_ru": "явный, несомненный", "pos": "adj", "level_id": 5},
    {"hebrew": "חד-משמעי", "transliteration": "хад-машмаИ", "translation_ru": "однозначный", "pos": "adj", "level_id": 5},
    {"hebrew": "רב-ממדי", "transliteration": "рав-мемадИ", "translation_ru": "многомерный", "pos": "adj", "level_id": 5},
    {"hebrew": "הכרחי", "transliteration": "hехрехИ", "translation_ru": "необходимый", "pos": "adj", "level_id": 5},
    {"hebrew": "טבוע", "transliteration": "тавУа", "translation_ru": "врождённый, присущий", "pos": "adj", "level_id": 5},
    {"hebrew": "מופרך", "transliteration": "муфрАх", "translation_ru": "абсурдный, несостоятельный", "pos": "adj", "level_id": 5},
    {"hebrew": "מרומז", "transliteration": "мерумАз", "translation_ru": "подразумеваемый, имплицитный", "pos": "adj", "level_id": 5},
    {"hebrew": "מוחשי", "transliteration": "мухашИ", "translation_ru": "ощутимый, осязаемый", "pos": "adj", "level_id": 5},
    {"hebrew": "גורף", "transliteration": "горЭф", "translation_ru": "всеобъемлющий, тотальный", "pos": "adj", "level_id": 5},
    {"hebrew": "חלוצי", "transliteration": "халуцИ", "translation_ru": "новаторский, пионерский", "pos": "adj", "level_id": 5},
    {"hebrew": "מכונן", "transliteration": "мехонЭн", "translation_ru": "учредительный, основополагающий", "pos": "adj", "level_id": 5},
    {"hebrew": "תקדימי", "transliteration": "такдимИ", "translation_ru": "прецедентный, беспрецедентный", "pos": "adj", "level_id": 5},
    # Advanced nouns (15)
    {"hebrew": "רציונליזם", "transliteration": "рационалИзм", "translation_ru": "рационализм", "pos": "noun", "level_id": 5},
    {"hebrew": "אמביוולנטיות", "transliteration": "амбивалЕнтиют", "translation_ru": "амбивалентность", "pos": "noun", "level_id": 5},
    {"hebrew": "רדוקציה", "transliteration": "редУкция", "translation_ru": "редукция", "pos": "noun", "level_id": 5},
    {"hebrew": "אינדוקציה", "transliteration": "индУкция", "translation_ru": "индукция", "pos": "noun", "level_id": 5},
    {"hebrew": "דדוקציה", "transliteration": "дедУкция", "translation_ru": "дедукция", "pos": "noun", "level_id": 5},
    {"hebrew": "הרמנויטיקה", "transliteration": "герменЕвтика", "translation_ru": "герменевтика", "pos": "noun", "level_id": 5},
    {"hebrew": "פנומנולוגיה", "transliteration": "феноменолОгия", "translation_ru": "феноменология", "pos": "noun", "level_id": 5},
    {"hebrew": "סולידריות", "transliteration": "солидарИют", "translation_ru": "солидарность", "pos": "noun", "level_id": 5},
    {"hebrew": "לגיטימציה", "transliteration": "легитимАция", "translation_ru": "легитимация", "pos": "noun", "level_id": 5},
    {"hebrew": "הגמוניה", "transliteration": "hегемОния", "translation_ru": "гегемония", "pos": "noun", "level_id": 5},
    {"hebrew": "פלורליזם", "transliteration": "плюралИзм", "translation_ru": "плюрализм", "pos": "noun", "level_id": 5},
    {"hebrew": "אלטרואיזם", "transliteration": "альтруИзм", "translation_ru": "альтруизм", "pos": "noun", "level_id": 5},
    {"hebrew": "ניהיליזם", "transliteration": "ниhилИзм", "translation_ru": "нигилизм", "pos": "noun", "level_id": 5},
    {"hebrew": "פרגמטיזם", "transliteration": "прагматИзм", "translation_ru": "прагматизм", "pos": "noun", "level_id": 5},
    {"hebrew": "אינטואיציה", "transliteration": "интуИция", "translation_ru": "интуиция", "pos": "noun", "level_id": 5},
    # Advanced formal adverbs/conjunctions (3)
    {"hebrew": "הואיל", "transliteration": "hоИль", "translation_ru": "поскольку (книжн.)", "pos": "adv", "level_id": 5},
    {"hebrew": "בדיעבד", "transliteration": "бедиавАд", "translation_ru": "задним числом, ретроспективно", "pos": "adv", "level_id": 5},
    {"hebrew": "אף על פי כן", "transliteration": "аф аль пи хен", "translation_ru": "тем не менее (книжн.)", "pos": "adv", "level_id": 5},
    # Additional C1 words (20)
    {"hebrew": "אנומליה", "transliteration": "аномАлия", "translation_ru": "аномалия", "pos": "noun", "level_id": 5},
    {"hebrew": "קוהרנטי", "transliteration": "коhерЕнти", "translation_ru": "когерентный, связный", "pos": "adj", "level_id": 5},
    {"hebrew": "לאפיין", "transliteration": "леафйЭн", "translation_ru": "характеризовать", "pos": "verb", "level_id": 5},
    {"hebrew": "להבנות", "transliteration": "леhибанОт", "translation_ru": "конструироваться, выстраиваться", "pos": "verb", "level_id": 5},
    {"hebrew": "לקטלג", "transliteration": "лекатлЭг", "translation_ru": "каталогизировать", "pos": "verb", "level_id": 5},
    {"hebrew": "להמשיג", "transliteration": "леhамшИг", "translation_ru": "концептуализировать", "pos": "verb", "level_id": 5},
    {"hebrew": "אנכרוניזם", "transliteration": "анахронИзм", "translation_ru": "анахронизм", "pos": "noun", "level_id": 5},
    {"hebrew": "דיכוטומיה", "transliteration": "дихотОмия", "translation_ru": "дихотомия", "pos": "noun", "level_id": 5},
    {"hebrew": "אנטיתזה", "transliteration": "антитЕза", "translation_ru": "антитеза", "pos": "noun", "level_id": 5},
    {"hebrew": "סטיגמה", "transliteration": "стИгма", "translation_ru": "стигма", "pos": "noun", "level_id": 5},
    {"hebrew": "דוגמטיזם", "transliteration": "догматИзм", "translation_ru": "догматизм", "pos": "noun", "level_id": 5},
    {"hebrew": "טאבו", "transliteration": "табУ", "translation_ru": "табу", "pos": "noun", "level_id": 5},
    {"hebrew": "סינרגיה", "transliteration": "синЕргия", "translation_ru": "синергия", "pos": "noun", "level_id": 5},
    {"hebrew": "סטטוס קוו", "transliteration": "стАтус кво", "translation_ru": "статус-кво", "pos": "noun", "level_id": 5},
    {"hebrew": "הומניזם", "transliteration": "hуманИзм", "translation_ru": "гуманизм", "pos": "noun", "level_id": 5},
    {"hebrew": "מנדט", "transliteration": "мандАт", "translation_ru": "мандат", "pos": "noun", "level_id": 5},
    {"hebrew": "אוטוריטרי", "transliteration": "авторитАри", "translation_ru": "авторитарный", "pos": "adj", "level_id": 5},
    {"hebrew": "טוטליטרי", "transliteration": "тоталитАри", "translation_ru": "тоталитарный", "pos": "adj", "level_id": 5},
    {"hebrew": "פטרנליסטי", "transliteration": "патерналИсти", "translation_ru": "патерналистский", "pos": "adj", "level_id": 5},
    {"hebrew": "אגוצנטרי", "transliteration": "эгоцЕнтри", "translation_ru": "эгоцентричный", "pos": "adj", "level_id": 5},
]

# ── Level 6 (C2) — mastery ──────────────────────────────────────────────────
# Rare, archaic, legal, poetic, slang

LEVEL_6_WORDS = [
    # Archaic / biblical (15)
    {"hebrew": "נאד", "transliteration": "нод", "translation_ru": "бурдюк, мех (для воды)", "pos": "noun", "level_id": 6},
    {"hebrew": "צנצנת", "transliteration": "цинцЕнет", "translation_ru": "кувшин; банка (библ.)", "pos": "noun", "level_id": 6},
    {"hebrew": "עטרה", "transliteration": "атарА", "translation_ru": "венец, корона (поэт.)", "pos": "noun", "level_id": 6},
    {"hebrew": "שרביט", "transliteration": "шарвИт", "translation_ru": "скипетр, жезл", "pos": "noun", "level_id": 6},
    {"hebrew": "חרב", "transliteration": "хЕрев", "translation_ru": "меч", "pos": "noun", "level_id": 6},
    {"hebrew": "מגן", "transliteration": "магЭн", "translation_ru": "щит", "pos": "noun", "level_id": 6},
    {"hebrew": "נביא", "transliteration": "навИ", "translation_ru": "пророк", "pos": "noun", "level_id": 6},
    {"hebrew": "משיח", "transliteration": "машИах", "translation_ru": "мессия, помазанник", "pos": "noun", "level_id": 6},
    {"hebrew": "מזמור", "transliteration": "мизмОр", "translation_ru": "псалом", "pos": "noun", "level_id": 6},
    {"hebrew": "נבואה", "transliteration": "невуА", "translation_ru": "пророчество", "pos": "noun", "level_id": 6},
    {"hebrew": "גלות", "transliteration": "галУт", "translation_ru": "изгнание, диаспора", "pos": "noun", "level_id": 6},
    {"hebrew": "תשובה", "transliteration": "тшувА", "translation_ru": "покаяние; ответ (книжн.)", "pos": "noun", "level_id": 6},
    {"hebrew": "כפרה", "transliteration": "капарА", "translation_ru": "искупление", "pos": "noun", "level_id": 6},
    {"hebrew": "כרוב", "transliteration": "керУв", "translation_ru": "херувим", "pos": "noun", "level_id": 6},
    {"hebrew": "קדושה", "transliteration": "кдушА", "translation_ru": "святость", "pos": "noun", "level_id": 6},
    # Legal / formal (12)
    {"hebrew": "פלוני", "transliteration": "плонИ", "translation_ru": "некий, такой-то (юрид.)", "pos": "noun", "level_id": 6},
    {"hebrew": "תקנה", "transliteration": "таканА", "translation_ru": "постановление, регламент", "pos": "noun", "level_id": 6},
    {"hebrew": "צו", "transliteration": "цав", "translation_ru": "ордер, указ", "pos": "noun", "level_id": 6},
    {"hebrew": "חזקה", "transliteration": "хазакА", "translation_ru": "презумпция; владение (юрид.)", "pos": "noun", "level_id": 6},
    {"hebrew": "שיפוט", "transliteration": "шипУт", "translation_ru": "юрисдикция, судопроизводство", "pos": "noun", "level_id": 6},
    {"hebrew": "עתירה", "transliteration": "атирА", "translation_ru": "петиция (в суд)", "pos": "noun", "level_id": 6},
    {"hebrew": "סעיף", "transliteration": "саИф", "translation_ru": "пункт, параграф (закона)", "pos": "noun", "level_id": 6},
    {"hebrew": "פסיקה", "transliteration": "псикА", "translation_ru": "судебная практика; прецедентное право", "pos": "noun", "level_id": 6},
    {"hebrew": "תקנון", "transliteration": "таканОн", "translation_ru": "устав, регламент", "pos": "noun", "level_id": 6},
    {"hebrew": "שטר חוב", "transliteration": "штАр хов", "translation_ru": "долговая расписка (юрид.)", "pos": "noun", "level_id": 6},
    {"hebrew": "שעבוד", "transliteration": "шиабУд", "translation_ru": "залог (юрид.); порабощение", "pos": "noun", "level_id": 6},
    {"hebrew": "אפוטרופוס", "transliteration": "апотрОпус", "translation_ru": "опекун (юрид.)", "pos": "noun", "level_id": 6},
    # Poetic / literary (12)
    {"hebrew": "עגמה", "transliteration": "агмА", "translation_ru": "печаль, тоска (поэт.)", "pos": "noun", "level_id": 6},
    {"hebrew": "געגוע", "transliteration": "гаагУа", "translation_ru": "тоска, ностальгия", "pos": "noun", "level_id": 6},
    {"hebrew": "דממה", "transliteration": "дмамА", "translation_ru": "тишь, безмолвие", "pos": "noun", "level_id": 6},
    {"hebrew": "ערגה", "transliteration": "аргА", "translation_ru": "томление, страстное желание", "pos": "noun", "level_id": 6},
    {"hebrew": "זוהר", "transliteration": "зОhар", "translation_ru": "сияние; Зоhар (каббала)", "pos": "noun", "level_id": 6},
    {"hebrew": "שממה", "transliteration": "шмамА", "translation_ru": "пустошь, запустение", "pos": "noun", "level_id": 6},
    {"hebrew": "אשמורת", "transliteration": "ашмОрет", "translation_ru": "стража (ночная); вахта (поэт.)", "pos": "noun", "level_id": 6},
    {"hebrew": "חזון", "transliteration": "хазОн", "translation_ru": "видение; пророчество", "pos": "noun", "level_id": 6},
    {"hebrew": "תמהון", "transliteration": "тимаhОн", "translation_ru": "изумление, оторопь", "pos": "noun", "level_id": 6},
    {"hebrew": "תוגה", "transliteration": "тугА", "translation_ru": "скорбь, печаль (высок.)", "pos": "noun", "level_id": 6},
    {"hebrew": "הוד", "transliteration": "hод", "translation_ru": "великолепие, величие (поэт.)", "pos": "noun", "level_id": 6},
    {"hebrew": "תפארת", "transliteration": "тифЭрет", "translation_ru": "слава, великолепие (каббал.)", "pos": "noun", "level_id": 6},
    # Slang / colloquial (11)
    {"hebrew": "חפיף", "transliteration": "хафИф", "translation_ru": "халтурный, поверхностный (сленг)", "pos": "adj", "level_id": 6},
    {"hebrew": "פראייר", "transliteration": "фраЕр", "translation_ru": "простак, лох (сленг)", "pos": "noun", "level_id": 6},
    {"hebrew": "חבל על הזמן", "transliteration": "хавАль аль hа-змАн", "translation_ru": "потрясающе (сленг)", "pos": "adv", "level_id": 6},
    {"hebrew": "סבבה", "transliteration": "сабАба", "translation_ru": "отлично, класс (сленг)", "pos": "adv", "level_id": 6},
    {"hebrew": "אחלה", "transliteration": "Ахла", "translation_ru": "супер, отлично (сленг, из араб.)", "pos": "adv", "level_id": 6},
    {"hebrew": "יאללה", "transliteration": "яАлла", "translation_ru": "давай, пошли (из араб.)", "pos": "adv", "level_id": 6},
    {"hebrew": "באסה", "transliteration": "бАса", "translation_ru": "облом, разочарование (сленг)", "pos": "noun", "level_id": 6},
    {"hebrew": "חנון", "transliteration": "ханУн", "translation_ru": "ботаник, зубрила (сленг)", "pos": "noun", "level_id": 6},
    {"hebrew": "מסטול", "transliteration": "местУль", "translation_ru": "обдолбанный, одурманенный (сленг)", "pos": "adj", "level_id": 6},
    {"hebrew": "פלצור", "transliteration": "фальцУр", "translation_ru": "подделка, фальшивка (сленг)", "pos": "noun", "level_id": 6},
    {"hebrew": "וואלה", "transliteration": "вАлла", "translation_ru": "правда? серьёзно? (сленг, из араб.)", "pos": "adv", "level_id": 6},
    # Linguistics (10)
    {"hebrew": "קונוטציה", "transliteration": "коноtАция", "translation_ru": "коннотация", "pos": "noun", "level_id": 6},
    {"hebrew": "דנוטציה", "transliteration": "деноtАция", "translation_ru": "денотация", "pos": "noun", "level_id": 6},
    {"hebrew": "סמנטיקה", "transliteration": "семАнтика", "translation_ru": "семантика", "pos": "noun", "level_id": 6},
    {"hebrew": "פרגמטיקה", "transliteration": "прагмАтика", "translation_ru": "прагматика", "pos": "noun", "level_id": 6},
    {"hebrew": "מורפולוגיה", "transliteration": "морфолОгия", "translation_ru": "морфология", "pos": "noun", "level_id": 6},
    {"hebrew": "סינטקסיס", "transliteration": "синтАксис", "translation_ru": "синтаксис", "pos": "noun", "level_id": 6},
    {"hebrew": "לקסיקון", "transliteration": "лексикОн", "translation_ru": "лексикон, словарь", "pos": "noun", "level_id": 6},
    {"hebrew": "אטימולוגיה", "transliteration": "этимолОгия", "translation_ru": "этимология", "pos": "noun", "level_id": 6},
    {"hebrew": "פונטיקה", "transliteration": "фонЕтика", "translation_ru": "фонетика", "pos": "noun", "level_id": 6},
    {"hebrew": "פונולוגיה", "transliteration": "фонолОгия", "translation_ru": "фонология", "pos": "noun", "level_id": 6},
    # Archaic / literary verbs (10)
    {"hebrew": "לכונן", "transliteration": "лехонЭн", "translation_ru": "учреждать, основывать (высок.)", "pos": "verb", "level_id": 6},
    {"hebrew": "לחרוץ", "transliteration": "лахарОц", "translation_ru": "решать (судьбу); постановлять", "pos": "verb", "level_id": 6},
    {"hebrew": "לשוש", "transliteration": "ласУс", "translation_ru": "радоваться, ликовать (библ.)", "pos": "verb", "level_id": 6},
    {"hebrew": "להתנשא", "transliteration": "леhитнасЭ", "translation_ru": "возвышаться; высокомерничать", "pos": "verb", "level_id": 6},
    {"hebrew": "להתגאות", "transliteration": "леhитгаОт", "translation_ru": "гордиться; кичиться", "pos": "verb", "level_id": 6},
    {"hebrew": "לרקום", "transliteration": "лиркОм", "translation_ru": "вышивать; плести (интриги)", "pos": "verb", "level_id": 6},
    {"hebrew": "לזעוק", "transliteration": "лизОк", "translation_ru": "вопить, взывать (высок.)", "pos": "verb", "level_id": 6},
    {"hebrew": "להשתוקק", "transliteration": "леhиштокЭк", "translation_ru": "страстно желать, жаждать", "pos": "verb", "level_id": 6},
    {"hebrew": "להתעלות", "transliteration": "леhитъалОт", "translation_ru": "возвыситься, превзойти себя", "pos": "verb", "level_id": 6},
    {"hebrew": "להיחלץ", "transliteration": "леhихалЭц", "translation_ru": "высвободиться; прийти на помощь", "pos": "verb", "level_id": 6},
    # Rare adjectives (10)
    {"hebrew": "אפל", "transliteration": "афЭль", "translation_ru": "мрачный, тёмный (поэт.)", "pos": "adj", "level_id": 6},
    {"hebrew": "נשגב", "transliteration": "нисгАв", "translation_ru": "возвышенный, величественный", "pos": "adj", "level_id": 6},
    {"hebrew": "נלוז", "transliteration": "налОз", "translation_ru": "порочный, извращённый (книжн.)", "pos": "adj", "level_id": 6},
    {"hebrew": "תמהוני", "transliteration": "тимhонИ", "translation_ru": "диковинный, причудливый", "pos": "adj", "level_id": 6},
    {"hebrew": "מזעזע", "transliteration": "мезаазЭа", "translation_ru": "шокирующий, ужасающий", "pos": "adj", "level_id": 6},
    {"hebrew": "נעלה", "transliteration": "наалА", "translation_ru": "возвышенный, благородный", "pos": "adj", "level_id": 6},
    {"hebrew": "ארכאי", "transliteration": "архаИ", "translation_ru": "архаичный", "pos": "adj", "level_id": 6},
    {"hebrew": "אניגמטי", "transliteration": "энигмАти", "translation_ru": "загадочный, энигматичный", "pos": "adj", "level_id": 6},
    {"hebrew": "סוריאליסטי", "transliteration": "сюрреалИсти", "translation_ru": "сюрреалистический", "pos": "adj", "level_id": 6},
    {"hebrew": "אלוזיבי", "transliteration": "алюзИви", "translation_ru": "иллюзорный; намекающий", "pos": "adj", "level_id": 6},
    # Extra rare / archaic (10)
    {"hebrew": "שאול", "transliteration": "шеОль", "translation_ru": "преисподняя, шеол (библ.)", "pos": "noun", "level_id": 6},
    {"hebrew": "תהו ובהו", "transliteration": "тОhу ва-вОhу", "translation_ru": "хаос, неразбериха (библ.)", "pos": "noun", "level_id": 6},
    {"hebrew": "גורן", "transliteration": "гОрен", "translation_ru": "гумно, ток (библ.)", "pos": "noun", "level_id": 6},
    {"hebrew": "מגילה", "transliteration": "мегилА", "translation_ru": "свиток; длинный рассказ", "pos": "noun", "level_id": 6},
    {"hebrew": "סנהדרין", "transliteration": "санhедрИн", "translation_ru": "Синедрион", "pos": "noun", "level_id": 6},
    {"hebrew": "בת קול", "transliteration": "бат коль", "translation_ru": "глас небесный (талмуд.)", "pos": "noun", "level_id": 6},
    {"hebrew": "פיוט", "transliteration": "пиЮт", "translation_ru": "литургическое стихотворение", "pos": "noun", "level_id": 6},
    {"hebrew": "מדרש", "transliteration": "мидрАш", "translation_ru": "мидраш (толкование Торы)", "pos": "noun", "level_id": 6},
    {"hebrew": "הלכה", "transliteration": "hалахА", "translation_ru": "hалаха (еврейский закон)", "pos": "noun", "level_id": 6},
    {"hebrew": "אגדתא", "transliteration": "агадтА", "translation_ru": "аггада (повествование Талмуда)", "pos": "noun", "level_id": 6},
    # Additional C2 words (10)
    {"hebrew": "לכפר", "transliteration": "лехапЭр", "translation_ru": "искупать (грех)", "pos": "verb", "level_id": 6},
    {"hebrew": "להתחנן", "transliteration": "леhитханЭн", "translation_ru": "молить, умолять", "pos": "verb", "level_id": 6},
    {"hebrew": "להאדיר", "transliteration": "леhаадИр", "translation_ru": "возвеличивать, прославлять", "pos": "verb", "level_id": 6},
    {"hebrew": "אנכרוניסטי", "transliteration": "анахронИсти", "translation_ru": "анахронистический", "pos": "adj", "level_id": 6},
    {"hebrew": "מיתולוגי", "transliteration": "митолОги", "translation_ru": "мифологический", "pos": "adj", "level_id": 6},
    {"hebrew": "אפוקליפטי", "transliteration": "апокалИпти", "translation_ru": "апокалиптический", "pos": "adj", "level_id": 6},
    {"hebrew": "אסכטולוגי", "transliteration": "эсхатолОги", "translation_ru": "эсхатологический", "pos": "adj", "level_id": 6},
    {"hebrew": "פנתאיזם", "transliteration": "пантеИзм", "translation_ru": "пантеизм", "pos": "noun", "level_id": 6},
    {"hebrew": "מונותאיזם", "transliteration": "монотеИзм", "translation_ru": "монотеизм", "pos": "noun", "level_id": 6},
    {"hebrew": "פוליתאיזם", "transliteration": "политеИзм", "translation_ru": "политеизм", "pos": "noun", "level_id": 6},
]


def upgrade() -> None:
    op.bulk_insert(words_table, LEVEL_1_WORDS)
    op.bulk_insert(words_table, LEVEL_3_WORDS)
    op.bulk_insert(words_table, LEVEL_4_WORDS)
    op.bulk_insert(words_table, LEVEL_5_WORDS)
    op.bulk_insert(words_table, LEVEL_6_WORDS)

    # Fix the sequence so that new inserts get the correct next id
    op.execute("SELECT setval('words_id_seq', (SELECT COALESCE(MAX(id), 0) FROM words))")


def downgrade() -> None:
    op.execute("DELETE FROM words WHERE level_id IN (1, 3, 4, 5, 6)")

    # Fix the sequence after deletion
    op.execute("SELECT setval('words_id_seq', (SELECT COALESCE(MAX(id), 0) FROM words))")
