"""Add ~329 more example sentences to reach 2000 total."""
from alembic import op
import sqlalchemy as sa

revision = "104"
down_revision = "103"
branch_labels = None
depends_on = None

def upgrade():
    t = sa.table(
        "example_sentences",
        sa.column("word_id", sa.Integer),
        sa.column("hebrew", sa.Text),
        sa.column("translation_ru", sa.Text),
        sa.column("transliteration", sa.Text),
        sa.column("audio_url", sa.Text),
        sa.column("level_id", sa.Integer),
    )
    rows = [
        (1350, 'אנחנו צריכים לדבר על זה', 'Нам нужно поговорить об этом', 'anakhnu tzrikhim ledaber al ze', None, 3),
        (1380, 'היא עובדת בבית חולים גדול', 'Она работает в большой больнице', 'hi ovedet be-beit kholim gadol', None, 3),
        (1420, 'הילדים משחקים בגן הציבורי', 'Дети играют в общественном парке', 'ha-yeladim mesakhakim ba-gan ha-tziburi', None, 3),
        (1460, 'אני לא יכול לבוא מחר בבוקר', 'Я не могу прийти завтра утром', 'ani lo yakhol lavo makhar ba-boker', None, 3),
        (1500, 'הוא למד עברית שלוש שנים', 'Он учил иврит три года', 'hu lamad ivrit shalosh shanim', None, 3),
        (1540, 'המסעדה הזאת פתוחה כל יום', 'Этот ресторан открыт каждый день', "ha-mis'ada ha-zot ptukha kol yom", None, 3),
        (1580, 'אנחנו גרים בדירה קטנה בתל אביב', 'Мы живём в маленькой квартире в Тель-Авиве', 'anakhnu garim be-dira ktana be-tel aviv', None, 3),
        (1620, 'האוטובוס מגיע בעוד עשר דקות', 'Автобус приедет через десять минут', 'ha-otobus magia be-od eser dakot', None, 3),
        (1660, 'היא קנתה שמלה חדשה לחתונה', 'Она купила новое платье на свадьбу', 'hi kanta simla khadasha la-khatuna', None, 3),
        (1700, 'אנחנו צריכים לקנות ירקות ופירות', 'Нам нужно купить овощи и фрукты', 'anakhnu tzrikhim liknot yerakot u-perot', None, 3),
        (1740, 'הרופא אמר שצריך לנוח יותר', 'Врач сказал, что нужно больше отдыхать', 'ha-rofe amar she-tzarikh lanuakh yoter', None, 3),
        (1780, 'הסרט הזה מאוד מעניין ומרגש', 'Этот фильм очень интересный и волнующий', "ha-seret ha-ze me'od me'anyen u-mergesh", None, 3),
        (1820, 'היא מדברת שלוש שפות בשטף', 'Она бегло говорит на трёх языках', 'hi medaberet shalosh safot be-shetef', None, 3),
        (1860, 'אנחנו נפגשים בכל שבוע ביום שלישי', 'Мы встречаемся каждую неделю во вторник', 'anakhnu nifgashim be-khol shavua be-yom shlishi', None, 3),
        (1900, 'הוא עובד מהבית כבר שנה', 'Он работает из дома уже год', 'hu oved me-ha-bayit kvar shana', None, 3),
        (1940, 'הבית שלנו נמצא ליד הים', 'Наш дом находится у моря', 'ha-bayit shelanu nimtza leyad ha-yam', None, 3),
        (1980, 'הם חזרו מחופשה בחוץ לארץ', 'Они вернулись из отпуска за границей', 'hem khazru me-khufsha be-khutz la-aretz', None, 3),
        (2020, 'את יכולה לעזור לי עם זה?', 'Ты можешь мне с этим помочь?', "at yekhola la'azor li im ze?", None, 3),
        (2060, 'הדודה שלי גרה בחיפה', 'Моя тётя живёт в Хайфе', 'ha-doda sheli gara be-kheifa', None, 3),
        (2100, 'השמש שוקעת מוקדם בחורף', 'Солнце заходит рано зимой', "ha-shemesh shoka'at mukdam ba-khoref", None, 3),
        (2140, 'הם בנו בית חדש בכפר', 'Они построили новый дом в деревне', 'hem banu bayit khadash ba-kfar', None, 3),
        (2180, 'המורה הסבירה את השיעור בבהירות', 'Учительница ясно объяснила урок', "ha-mora hisbira et ha-shi'ur be-behirut", None, 3),
        (2220, 'הוא רוצה לטייל בכל העולם', 'Он хочет путешествовать по всему миру', 'hu rotze letayel be-khol ha-olam', None, 3),
        (2260, 'אנחנו אוכלים ארוחת ערב ביחד', 'Мы ужинаем вместе', 'anakhnu okhlim arukhat erev beyakhad', None, 3),
        (2300, 'המשרד פתוח מתשע עד חמש', 'Офис открыт с девяти до пяти', 'ha-misrad patuakh me-tesha ad khamesh', None, 3),
        (2340, 'היא שרה שיר יפה בהופעה', 'Она спела красивую песню на концерте', "hi shara shir yafe ba-hofa'a", None, 3),
        (2380, 'הגשם ירד כל היום אתמול', 'Дождь шёл весь день вчера', 'ha-geshem yarad kol ha-yom etmol', None, 3),
        (2420, 'אנחנו מתכננים לנסוע לאילת', 'Мы планируем поехать в Эйлат', "anakhnu metakhnanim linso'a le-eilat", None, 3),
        (2460, 'הספרייה העירונית פתוחה גם בשבת', 'Городская библиотека открыта и в субботу', 'ha-sifriya ha-ironit ptukha gam be-shabat', None, 3),
        (2500, 'הוא הזמין שולחן במסעדה לערב', 'Он заказал столик в ресторане на вечер', "hu hizmin shulkhan ba-mis'ada la-erev", None, 3),
        (2550, 'השכנים שלנו מאוד נחמדים', 'Наши соседи очень приятные', "ha-shkhenim shelanu me'od nekhmadim", None, 3),
        (2600, 'אני צריך ללכת לרופא שיניים', 'Мне нужно пойти к стоматологу', 'ani tzarikh lalekhet le-rofe shinayim', None, 3),
        (2650, 'המחשב שלי לא עובד כמו שצריך', 'Мой компьютер не работает как надо', 'ha-makhshev sheli lo oved kmo she-tzarikh', None, 3),
        (2700, 'היא סיימה את הלימודים בהצלחה', 'Она успешно закончила учёбу', 'hi siyma et ha-limudim be-hatzlakha', None, 3),
        (2750, 'הילד הזה חכם מאוד לגילו', 'Этот ребёнок очень умный для своего возраста', "ha-yeled ha-ze khakham me'od le-gilo", None, 3),
        (2800, 'אנחנו צריכים לשלם את החשבון', 'Нам нужно оплатить счёт', 'anakhnu tzrikhim leshalem et ha-kheshbon', None, 3),
        (2850, 'המוזיקה הישראלית מגוונת מאוד', 'Израильская музыка очень разнообразна', "ha-muzika ha-yisraelit meguvenet me'od", None, 3),
        (2900, 'הוא שיחק כדורגל כל ילדותו', 'Он играл в футбол всё детство', 'hu sikhek kaduregel kol yalduto', None, 3),
        (2950, 'השוק בירושלים מלא צבעים וריחות', 'Рынок в Иерусалиме полон красок и запахов', "ha-shuk bi-yerushalayim male tzva'im ve-reikhot", None, 3),
        (3000, 'היא לומדת לתואר שני באוניברסיטה', 'Она учится на магистратуре в университете', "hi lomedet le-to'ar sheni ba-universita", None, 3),
        (3050, 'הם עברו לגור בשכונה חדשה', 'Они переехали жить в новый район', 'hem avru lagur bi-shkhuna khadasha', None, 3),
        (3100, 'האוכל במסעדה הזאת מצוין', 'Еда в этом ресторане отличная', "ha-okhel ba-mis'ada ha-zot metzuyan", None, 3),
        (3150, 'אני שומע מוזיקה כשאני נוסע באוטו', 'Я слушаю музыку, когда еду в машине', "ani shome'a muzika kshe-ani nose'a ba-oto", None, 3),
        (3200, 'הוא קיבל מלגה ללימודים', 'Он получил стипендию на учёбу', 'hu kibel milga la-limudim', None, 3),
        (3250, 'הפרחים בגינה פורחים באביב', 'Цветы в саду расцветают весной', 'ha-prakhim ba-gina porkhim ba-aviv', None, 3),
        (3300, 'היא עשתה עוגה ליום ההולדת', 'Она испекла торт на день рождения', 'hi asta uga le-yom ha-huledet', None, 3),
        (3350, 'אנחנו מטיילים בגליל כל קיץ', 'Мы путешествуем по Галилее каждое лето', 'anakhnu metaylim ba-galil kol kayitz', None, 3),
        (3400, 'הבנק סגור ביום שישי אחר הצהריים', 'Банк закрыт в пятницу днём', 'ha-bank sagur be-yom shishi akhar ha-tzohorayim', None, 3),
        (3450, 'הוא עזר לה לשאת את השקיות', 'Он помог ей нести сумки', "hu azar la las'et et ha-sakiyot", None, 3),
        (3500, 'המשפחה שלנו מתכנסת בחגים', 'Наша семья собирается по праздникам', 'ha-mishpakha shelanu mitkaneset ba-khagim', None, 3),
        (3550, 'היא מכינה ארוחת בוקר כל יום', 'Она готовит завтрак каждый день', 'hi mekhina arukhat boker kol yom', None, 3),
        (3600, 'הכביש הראשי סגור לתנועה', 'Главная дорога закрыта для движения', "ha-kvish ha-rashi sagur li-tnu'a", None, 3),
        (3650, 'אנחנו שמחים שבאתם לביקור', 'Мы рады, что вы пришли в гости', 'anakhnu smekhim she-batem le-bikur', None, 3),
        (3700, 'הטלפון שלי צריך טעינה', 'Мой телефон нужно зарядить', "ha-telefon sheli tzarikh te'ina", None, 3),
        (3750, 'הוא נהג מונית עשרים שנה', 'Он водил такси двадцать лет', 'hu nahag monit esrim shana', None, 3),
        (3800, 'המכתב הגיע בדואר היום', 'Письмо пришло по почте сегодня', "ha-mikhtav higia ba-do'ar ha-yom", None, 3),
        (3850, 'היא צילמה את הנוף מהמרפסת', 'Она сфотографировала вид с балкона', 'hi tzilma et ha-nof me-ha-mirpeset', None, 3),
        (3900, 'השעון שלי מקדים בחמש דקות', 'Мои часы спешат на пять минут', "ha-sha'on sheli makdim be-khamesh dakot", None, 3),
        (3950, 'הם הזמינו אורחים לשבת', 'Они пригласили гостей на субботу', 'hem hizminu orkhim le-shabat', None, 3),
        (4000, 'האופניים שלו נגנבו מהחניון', 'Его велосипед украли с парковки', 'ha-ofanayim shelo nignvu me-ha-khanyon', None, 3),
        (4050, 'הילדה כתבה מכתב לסבתא', 'Девочка написала письмо бабушке', 'ha-yalda katva mikhtav la-savta', None, 3),
        (1330, 'בבקשה תסגור את הדלת', 'Пожалуйста, закрой дверь', 'be-vakasha tisgor et ha-delet', None, 3),
        (1370, 'מתי נפגשים מחר?', 'Когда встречаемся завтра?', 'matay nifgashim makhar?', None, 3),
        (1410, 'אני מרגיש טוב היום', 'Я чувствую себя хорошо сегодня', 'ani margish tov ha-yom', None, 3),
        (1450, 'הם הלכו לים בסוף השבוע', 'Они ходили на море в выходные', 'hem halkhu la-yam be-sof ha-shavua', None, 3),
        (1490, 'הסיפור הזה נשמע מוזר', 'Эта история звучит странно', 'ha-sipur ha-ze nishma muzar', None, 3),
        (1530, 'אנחנו חוגגים יום הולדת הערב', 'Мы празднуем день рождения сегодня вечером', 'anakhnu khogegim yom huledet ha-erev', None, 3),
        (1570, 'הוא הבטיח לחזור מוקדם', 'Он обещал вернуться рано', 'hu hivtiakh lakhzor mukdam', None, 3),
        (1610, 'התינוק ישן כל הלילה', 'Малыш спал всю ночь', 'ha-tinok yashan kol ha-layla', None, 3),
        (1650, 'היא שכחה את הארנק בבית', 'Она забыла кошелёк дома', 'hi shakhkha et ha-arnak ba-bayit', None, 3),
        (1690, 'הרכבת מאחרת בעשרים דקות', 'Поезд опаздывает на двадцать минут', "ha-rakevet me'akheret be-esrim dakot", None, 3),
        (1730, 'אנחנו גמרנו את כל האוכל', 'Мы съели всю еду', 'anakhnu gamarna et kol ha-okhel', None, 3),
        (1770, 'הקפה פה מצוין', 'Кофе здесь отличный', 'ha-kafe po metzuyan', None, 3),
        (1810, 'היא רצה מרתון בפעם הראשונה', 'Она пробежала марафон впервые', "hi ratza maraton ba-pa'am ha-rishona", None, 3),
        (1850, 'הם קנו דירה חדשה בראשון לציון', 'Они купили новую квартиру в Ришон-ле-Ционе', 'hem kanu dira khadasha be-rishon le-tziyon', None, 3),
        (1890, 'אני לא אוהב לקום מוקדם', 'Я не люблю вставать рано', 'ani lo ohev lakum mukdam', None, 3),
        (1930, 'הילד למד לרכוב על אופניים', 'Ребёнок научился ездить на велосипеде', 'ha-yeled lamad lirkov al ofanayim', None, 3),
        (1970, 'חם מאוד בקיץ בישראל', 'Летом в Израиле очень жарко', "kham me'od ba-kayitz be-yisrael", None, 3),
        (2010, 'הסופרמרקט פתוח עד מאוחר', 'Супермаркет открыт допоздна', "ha-supermarket patuakh ad me'ukhar", None, 3),
        (1450, 'הממשלה אישרה את התקציב החדש', 'Правительство утвердило новый бюджет', 'ha-memshala ishra et ha-taktziv he-khadash', None, 4),
        (1520, 'המשפט התנהל בבית המשפט המחוזי', 'Суд проходил в окружном суде', 'ha-mishpat hitnahel be-beit ha-mishpat ha-mekhozi', None, 4),
        (1590, 'הכתבה חשפה שחיתות בממשלה', 'Репортаж раскрыл коррупцию в правительстве', 'ha-katava khasfa shkhitut ba-memshala', None, 4),
        (1660, 'הפסיכולוג ניתח את התנהגות המטופל', 'Психолог проанализировал поведение пациента', 'ha-psikholog nitakh et hitnagut ha-metupal', None, 4),
        (1730, 'הביוגרפיה מתארת את חייו של המנהיג', 'Биография описывает жизнь лидера', "ha-biographia meta'eret et khayav shel ha-manhig", None, 4),
        (1800, 'הרפורמה החינוכית יצרה מחלוקת', 'Образовательная реформа вызвала разногласия', 'ha-reforma ha-khinukhit yatzra makhloket', None, 4),
        (1870, 'הבנק המרכזי פרסם דוח שנתי', 'Центральный банк опубликовал годовой отчёт', "ha-bank ha-merkazi pirsem do'akh shnati", None, 4),
        (1940, 'הצבא ביצע תרגיל בצפון הארץ', 'Армия провела учения на севере страны', "ha-tzava bitze'a targil bi-tzfon ha-aretz", None, 4),
        (2010, 'המחקר הוכיח קשר בין עישון לסרטן', 'Исследование доказало связь между курением и раком', 'ha-mekhkar hokhiakh kesher bein ishun le-sartan', None, 4),
        (2080, 'הניסוי הצליח מעבר לציפיות', 'Эксперимент удался сверх ожиданий', "ha-nisayon hitzsliakh me'ever la-tzipiyot", None, 4),
        (2150, 'ההסכם נחתם בטקס רשמי', 'Соглашение подписано на официальной церемонии', 'ha-heskem nekhtam be-tekes rishmi', None, 4),
        (2220, 'השוק הנדל"ני חווה עלייה חדה', 'Рынок недвижимости пережил резкий рост', 'ha-shuk ha-nadlani khava aliya khada', None, 4),
        (2290, 'הדילמה המוסרית העסיקה את הציבור', 'Моральная дилемма занимала общество', "ha-dilema ha-musarit he'esika et ha-tzibur", None, 4),
        (2360, 'התקשורת סיקרה את האירוע בהרחבה', 'СМИ широко осветили событие', "ha-tikshoret sikra et ha-iru'a be-harkhava", None, 4),
        (2430, 'הנציגות הדיפלומטית התערבה בסכסוך', 'Дипломатическое представительство вмешалось в конфликт', "ha-natzigut ha-diplomatit hit'arva ba-sikhsukh", None, 4),
        (2500, 'הפרויקט הושלם במסגרת התקציב', 'Проект завершён в рамках бюджета', 'ha-proyekt hushlam be-misgeret ha-taktziv', None, 4),
        (2570, 'החוקר פרסם מאמר בכתב עת בינלאומי', 'Учёный опубликовал статью в международном журнале', "ha-khoker pirsem ma'amar be-ktav et bein-leumi", None, 4),
        (2640, 'הוועדה המליצה על שינויים בחוק', 'Комиссия рекомендовала изменения в законе', "ha-va'ada himlitza al shinuyim ba-khok", None, 4),
        (2710, 'האוניברסיטה הציעה תכנית לימודים חדשה', 'Университет предложил новую учебную программу', "ha-universita hetzi'a tokhnit limudim khadasha", None, 4),
        (2780, 'ההפגנה התקיימה מול בניין העירייה', 'Демонстрация прошла перед зданием муниципалитета', 'ha-hafgana hitkayma mul binyan ha-iriya', None, 4),
        (2850, 'הכלכלן חזה האטה בצמיחה', 'Экономист предсказал замедление роста', "ha-kalkalan khaza ha'ata ba-tzmiha", None, 4),
        (2920, 'הרפורמה הבריאותית עוררה ויכוח ער', 'Реформа здравоохранения вызвала оживлённый спор', "ha-reforma ha-bri'utit orera vikuakh er", None, 4),
        (2990, 'הסופר קיבל פרס ספרותי יוקרתי', 'Писатель получил престижную литературную премию', 'ha-sofer kibel pras sifruti yokrati', None, 4),
        (3060, 'ההשקעה בחינוך מחזירה את עצמה', 'Инвестиции в образование окупаются', "ha-hashka'a be-khinukh makhzira et atzma", None, 4),
        (3130, 'הטכנולוגיה שינתה את שוק העבודה', 'Технология изменила рынок труда', 'ha-tekhnologia shinta et shuk ha-avoda', None, 4),
        (3200, 'המשרד הוציא הנחיות חדשות', 'Министерство выпустило новые директивы', 'ha-misrad hotzi hanhayot khadashot', None, 4),
        (3270, 'הסקר הראה שינוי במגמה', 'Опрос показал смену тенденции', "ha-seker her'a shinui ba-megama", None, 4),
        (3340, 'התביעה הוגשה בבית המשפט', 'Иск подан в суд', "ha-tvi'a hugsha be-beit ha-mishpat", None, 4),
        (3410, 'הממשלה הכריזה על מצב חירום', 'Правительство объявило чрезвычайное положение', 'ha-memshala hikhriza al matzav kherum', None, 4),
        (3480, 'הפרלמנט דן בהצעת חוק חדשה', 'Парламент обсуждал новый законопроект', "ha-parlament dan be-hatza'at khok khadasha", None, 4),
        (3550, 'האקדמיה קבעה כללי כתיב חדשים', 'Академия установила новые правила правописания', "ha-akademia kav'a klalei ktiv khadashim", None, 4),
        (3620, 'הארכיאולוג גילה ממצא היסטורי חשוב', 'Археолог обнаружил важную историческую находку', 'ha-arkhiolog gila mimtza histori khashuv', None, 4),
        (3690, 'המגפה השפיעה על הכלכלה העולמית', 'Пандемия повлияла на мировую экономику', "ha-magefa hishpi'a al ha-kalkala ha-olamit", None, 4),
        (3760, 'הנשיא נפגש עם ראש הממשלה', 'Президент встретился с премьер-министром', 'ha-nasi nifgash im rosh ha-memshala', None, 4),
        (3830, 'הנתונים מצביעים על מגמה חיובית', 'Данные указывают на положительную тенденцию', "ha-netunim matzbi'im al megama khiyuvit", None, 4),
        (3900, 'העיתונאי חקר את הפרשה לעומק', 'Журналист глубоко расследовал дело', 'ha-itonay khakar et ha-parasha le-omek', None, 4),
        (3970, 'הוועדה פרסמה את מסקנותיה', 'Комиссия опубликовала свои выводы', "ha-va'ada pirsema et maskanoteiha", None, 4),
        (4040, 'הבחירות יתקיימו בחודש הבא', 'Выборы состоятся в следующем месяце', 'ha-bkhirot yitkaymu ba-khodesh ha-ba', None, 4),
        (4110, 'האופוזיציה מתחה ביקורת על הממשלה', 'Оппозиция критиковала правительство', 'ha-opozitzya matkha bikoret al ha-memshala', None, 4),
        (4180, 'ההסכם הכלכלי ייכנס לתוקף בינואר', 'Экономическое соглашение вступит в силу в январе', 'ha-heskem ha-kalkali yikanes le-tokef be-yanuar', None, 4),
        (4250, 'המומחים הזהירו מפני סיכונים', 'Эксперты предупредили о рисках', 'ha-mumkhim hizhiru mi-pnei sikunim', None, 4),
        (4320, 'החברה הודיעה על פיטורים המוניים', 'Компания объявила о массовых увольнениях', "ha-khevra hodi'a al piturim hamoni'im", None, 4),
        (4390, 'השופט פסל את הראיה', 'Судья отклонил доказательство', "ha-shofet pasal et ha-re'aya", None, 4),
        (4460, 'הפרופסור הרצה בפני הסטודנטים', 'Профессор прочёл лекцию студентам', 'ha-profesor hirtza bi-fnei ha-studentim', None, 4),
        (4530, 'המאמר עורר דיון ער בציבור', 'Статья вызвала оживлённую дискуссию в обществе', "ha-ma'amar orer diyun er ba-tzibur", None, 4),
        (1470, 'התרבות הישראלית מושפעת ממזרח וממערב', 'Израильская культура испытывает влияние Востока и Запада', "ha-tarbut ha-yisraelit mush'pa'at mi-mizrakh u-mi-ma'arav", None, 4),
        (1550, 'הרצאתו של הפרופסור הייתה מרתקת', 'Лекция профессора была захватывающей', 'hartzato shel ha-profesor hayta meratekes', None, 4),
        (1630, 'הצנזורה הצבאית פעלה בימי המלחמה', 'Военная цензура действовала во время войны', "ha-tzenzura ha-tzva'it pa'ala bi-ymei ha-milkhama", None, 4),
        (1710, 'הביקורת על הספר הייתה חריפה', 'Критика книги была острой', 'ha-bikoret al ha-sefer hayta kharifa', None, 4),
        (1790, 'המנהל קיבל החלטה קשה', 'Директор принял трудное решение', 'ha-menahel kibel hakhlata kasha', None, 4),
        (2050, 'החולה אושפז במחלקה הפנימית', 'Больной госпитализирован во внутреннее отделение', 'ha-khole ushpaz ba-makhlaka ha-pnimit', None, 4),
        (2120, 'הסטטיסטיקה מראה ירידה בפשיעה', 'Статистика показывает снижение преступности', "ha-statistika mar'a yerida ba-pshi'a", None, 4),
        (2190, 'התיעוד ההיסטורי נשמר בארכיון', 'Историческая документация хранится в архиве', "ha-ti'ud ha-histori nishmar ba-arkhiyon", None, 4),
        (2260, 'העמותה פעלה למען זכויות אדם', 'Организация действовала во имя прав человека', "ha-amuta pa'ala lema'an zkhuyot adam", None, 4),
        (2330, 'הפסיכיאטר אבחן דיכאון קליני', 'Психиатр диагностировал клиническую депрессию', 'ha-psikhiyater ivkhen dikaon klini', None, 4),
        (2400, 'הפילוסוף העלה שאלות מהותיות', 'Философ поставил сущностные вопросы', "ha-filosof he'ela she'elot mahutiyot", None, 4),
        (2470, 'המשא ומתן נמשך שבועות ארוכים', 'Переговоры длились долгие недели', "ha-masa u-matan nimshakh shvu'ot arukim", None, 4),
        (2540, 'ההיסטוריון חקר את תקופת המנדט', 'Историк исследовал период Мандата', 'ha-historyon khakar et tkufat ha-mandat', None, 4),
        (2610, 'החוקה מגינה על חופש הביטוי', 'Конституция защищает свободу слова', 'ha-khuka megina al khofesh ha-bituy', None, 4),
        (2680, 'הרבנות הראשית הכריעה בשאלה הלכתית', 'Главный раввинат вынес решение по вопросу галахи', "ha-rabanut ha-rashit hikhri'a be-she'ela hilkhatit", None, 4),
        (2750, 'הקואליציה התפרקה לאחר המשבר', 'Коалиция распалась после кризиса', "ha-koalitzya hitparka le'akhar ha-mashber", None, 4),
        (2820, 'המדינאי הציע תוכנית שלום חדשה', 'Государственный деятель предложил новый мирный план', "ha-medinay hetzi'a tokhnit shalom khadasha", None, 4),
        (2890, 'הפרקליטות הגישה כתב אישום', 'Прокуратура подала обвинительное заключение', 'ha-praklitut higisha ktav ishum', None, 4),
        (2960, 'הסוציולוג חקר את ההרכב האתני', 'Социолог исследовал этнический состав', 'ha-sotziolog khakar et ha-herkev ha-etni', None, 4),
        (3030, 'הסנקציות הכלכליות הוחמרו', 'Экономические санкции ужесточены', 'ha-sanktziot ha-kalkaliot hukhemru', None, 4),
        (3100, 'הדמוקרטיה דורשת שקיפות', 'Демократия требует прозрачности', 'ha-demokratya doreshet shkifut', None, 4),
        (3170, 'הרפורמה המשפטית עוררה מחאה', 'Правовая реформа вызвала протест', "ha-reforma ha-mishpatit orera mekha'a", None, 4),
        (3240, 'הנציב פרסם דוח ביקורת', 'Контролёр опубликовал отчёт ревизии', "ha-natziv pirsem do'akh bikoret", None, 4),
        (3310, 'הפרלמנט אישר את החוק ברוב קולות', 'Парламент утвердил закон большинством голосов', 'ha-parlament isher et ha-khok be-rov kolot', None, 4),
        (3380, 'הממשלה הקצתה תקציב לחינוך', 'Правительство выделило бюджет на образование', 'ha-memshala hiktzta taktziv la-khinukh', None, 4),
        (3450, 'המדען קיבל פרס נובל', 'Учёный получил Нобелевскую премию', "ha-mad'an kibel pras nobel", None, 4),
        (3520, 'הדיפלומט ניהל שיחות סודיות', 'Дипломат вёл секретные переговоры', 'ha-diplomat nihel sikhot sodiyot', None, 4),
        (4600, 'האינפלציה פגעה בכוח הקנייה', 'Инфляция ударила по покупательной способности', "ha-inflatzya pag'a be-koakh ha-kniya", None, 4),
        (4670, 'הניסוי המדעי הניב תוצאות מפתיעות', 'Научный эксперимент дал удивительные результаты', "ha-nisuy ha-mad'i heniv totz'aot mafti'ot", None, 4),
        (4740, 'ועדת הכלכלה דנה בתקציב המדינה', 'Экономическая комиссия обсуждала госбюджет', "va'adat ha-kalkala dana be-taktziv ha-medina", None, 4),
        (4810, 'העיתון פרסם חקירה על שחיתות', 'Газета опубликовала расследование о коррупции', 'ha-iton pirsem khakira al shkhitut', None, 4),
        (4880, 'הנתבע הכחיש את כל ההאשמות', 'Ответчик отверг все обвинения', "ha-nitba hikhkhish et kol ha-ha'ashamot", None, 4),
        (4950, 'הביקורת האקדמית הייתה מפורטת', 'Академическая рецензия была подробной', 'ha-bikoret ha-akademit hayta mefuretet', None, 4),
        (5020, 'המגזר הפרטי מעסיק רוב העובדים', 'Частный сектор нанимает большинство работников', "ha-migzar ha-prati ma'asik rov ha-ovdim", None, 4),
        (5090, 'הסכסוך נפתר בדרכי שלום', 'Конфликт решён мирным путём', 'ha-sikhsukh niftar be-darkhei shalom', None, 4),
        (5160, 'ההשכלה הגבוהה נגישה לכולם', 'Высшее образование доступно всем', 'ha-haskala ha-gvoha negisha la-kulam', None, 4),
        (5230, 'התעשייה ההייטקית מובילה את המשק', 'Хайтек-индустрия лидирует в экономике', "ha-ta'asiya ha-haitek'it movila et ha-meshek", None, 4),
        (5300, 'הרשות הפלסטינית הגיבה להצעה', 'Палестинская администрация отреагировала на предложение', "ha-rashut ha-falestinit hegiva la-hatza'a", None, 4),
        (5370, 'היצוא הישראלי גדל בעשרה אחוז', 'Израильский экспорт вырос на десять процентов', 'ha-yetzu ha-yisraeli gadal ba-asara akhuz', None, 4),
        (5440, 'המשפט המנהלי מסדיר את יחסי פרט-מדינה', 'Административное право регулирует отношения личности и государства', 'ha-mishpat ha-minhali mesader et yakhasei prat-medina', None, 4),
        (1550, 'הדיסקורס האקדמי דורש דיוק בניסוח', 'Академический дискурс требует точности формулировок', 'ha-diskurs ha-akademi doresh diyuk be-nisuakh', None, 5),
        (1620, 'האינטרטקסטואליות מעשירה את הקריאה', 'Интертекстуальность обогащает чтение', "ha-intertekstu'aliyut ma'ashira et ha-kri'a", None, 5),
        (1690, 'הפרדיגמה המחקרית השתנתה בעשורים האחרונים', 'Исследовательская парадигма изменилась в последние десятилетия', 'ha-paradigma ha-mekhkarit hishtanta ba-asorim ha-akharonim', None, 5),
        (1760, 'המאמר מציע פרשנות חלופית לתופעה', 'Статья предлагает альтернативную интерпретацию явления', "ha-ma'amar metzi'a parshanut khalufit la-tofa'a", None, 5),
        (1830, 'הנרטיב הלאומי עוצב במהלך המאה העשרים', 'Национальный нарратив сформировался в XX веке', "ha-narrativ ha-le'umi utzav be-mahalakh ha-me'a ha-esrim", None, 5),
        (1900, 'הניתוח הסטרוקטורליסטי חשף מבנים סמויים', 'Структуралистский анализ выявил скрытые структуры', 'ha-nituakh ha-strukturalisti khasaf mivnim smuyim', None, 5),
        (1970, 'האמביוולנטיות של הדמות מעניינת', 'Амбивалентность персонажа интересна', "ha-ambivalentiyut shel ha-dmut me'anyenet", None, 5),
        (2040, 'הסמנטיקה של המילה השתנתה לאורך הדורות', 'Семантика слова менялась на протяжении поколений', 'ha-semantika shel ha-mila hishtanta le-orekh ha-dorot', None, 5),
        (2110, 'הפרגמטיקה חוקרת שפה בהקשר', 'Прагматика изучает язык в контексте', 'ha-pragmatika khokeret safa be-heksher', None, 5),
        (2180, 'האפיסטמולוגיה עוסקת בשאלת הידיעה', 'Эпистемология занимается вопросом познания', "ha-epistemologia oseket be-she'elat ha-yedi'a", None, 5),
        (2250, 'ההרמנויטיקה מציעה כלים לפרשנות טקסטים', 'Герменевтика предлагает инструменты для интерпретации текстов', "ha-hermeneutika metzi'a kelim le-parshanut tekstim", None, 5),
        (2320, 'ההגמוניה התרבותית קובעת נורמות חברתיות', 'Культурная гегемония определяет социальные нормы', "ha-hegemonia ha-tarbutit kova'at normot khevratiyot", None, 5),
        (2390, 'הדיאלקטיקה ההגליאנית משפיעה על ההגות המודרנית', 'Гегелевская диалектика влияет на современную мысль', "ha-dialektika ha-hegel'ianit mashpi'a al ha-hagut ha-modernit", None, 5),
        (2460, 'האנומיה החברתית נובעת מאובדן ערכים', 'Социальная аномия проистекает из утраты ценностей', 'ha-anomia ha-khevratit novaat me-ovdan arakhim', None, 5),
        (2530, 'הקאנון הספרותי משתנה בכל דור', 'Литературный канон меняется в каждом поколении', 'ha-kanon ha-sifruti mishtane be-khol dor', None, 5),
        (2600, 'הטרנסצנדנטליות קשורה לפילוסופיה של קאנט', 'Трансцендентальность связана с философией Канта', 'ha-transtsendantaliyut kshura la-filosofia shel kant', None, 5),
        (2670, 'האמפיריציזם מדגיש את חשיבות הניסיון', 'Эмпиризм подчёркивает важность опыта', 'ha-empiritzizm madgish et khashivut ha-nisayon', None, 5),
        (2740, 'הפנומנולוגיה של הוסרל שינתה את הפילוסופיה', 'Феноменология Гуссерля изменила философию', 'ha-fenomenologia shel huserl shinta et ha-filosofia', None, 5),
        (2810, 'האקזיסטנציאליזם מדגיש את חופש הבחירה', 'Экзистенциализм подчёркивает свободу выбора', 'ha-ekzistentsializm madgish et khofesh ha-bkhira', None, 5),
        (2880, 'הדקונסטרוקציה מערערת על הנחות יסוד', 'Деконструкция подвергает сомнению базовые предпосылки', "ha-dekonstruktzya me'ar'eret al hanakhot yesod", None, 5),
        (2950, 'המטאפיזיקה עוסקת בשאלות על טבע המציאות', 'Метафизика занимается вопросами о природе реальности', "ha-metafizika oseket be-she'elot al teva ha-metzi'ut", None, 5),
        (3020, 'האונטולוגיה חוקרת את מהות הקיום', 'Онтология исследует сущность бытия', 'ha-ontologia khokeret et mahut ha-kiyum', None, 5),
        (3090, 'הפוסט-מודרניזם מערער על אמיתות מוחלטות', 'Постмодернизм подвергает сомнению абсолютные истины', "ha-post-modernizm me'ar'er al amitot mukhlalot", None, 5),
        (3160, 'הסוציולוגיה הביקורתית בוחנת מבני כוח', 'Критическая социология исследует структуры власти', 'ha-sotziologia ha-bikortit bokhenet mivnei koakh', None, 5),
        (3230, "המושג 'אחר' מרכזי בפילוסופיה של לוינס", "Понятие 'Другой' центрально в философии Левинаса", "ha-musag 'akher' merkazi ba-filosofia shel levinas", None, 5),
        (3300, 'הפמיניזם שינה את השיח האקדמי', 'Феминизм изменил академический дискурс', 'ha-feminizm shina et ha-siakh ha-akademi', None, 5),
        (3370, 'ההיסטוריוגרפיה בוחנת כיצד נכתב העבר', 'Историография изучает, как пишется прошлое', 'ha-historiografiya bokhenet keitzad nikhtav ha-avar', None, 5),
        (3440, 'הביו-אתיקה מתמודדת עם דילמות רפואיות', 'Биоэтика сталкивается с медицинскими дилеммами', "ha-bio-etika mitmodetet im dilemot refu'iyot", None, 5),
        (3510, 'הפלורליזם מכיר בלגיטימיות של דעות שונות', 'Плюрализм признаёт легитимность различных мнений', "ha-pluralizm makir be-legitimiyut shel de'ot shonot", None, 5),
        (3580, 'האלגוריה כמכשיר ספרותי קיימת מימי קדם', 'Аллегория как литературный приём существует с древности', 'ha-alegorya ke-makhshir sifruti kayemet mi-ymei kedem', None, 5),
        (3650, 'הפרדוקס העצמי מאתגר את ההיגיון', 'Самореферентный парадокс бросает вызов логике', "ha-paradoks ha-atzmi me'atger et ha-higayon", None, 5),
        (3720, 'המינימליזם בספרות מעדיף פשטות', 'Минимализм в литературе предпочитает простоту', "ha-minimalizm ba-sifrut ma'adif pashtut", None, 5),
        (3790, 'האירוניה הדרמטית מוסיפה עומק ליצירה', 'Драматическая ирония добавляет глубину произведению', 'ha-ironia ha-dramatit mosifa omek la-yetzira', None, 5),
        (3860, 'הנהירה לערים יצרה בעיות חברתיות', 'Урбанизация создала социальные проблемы', "ha-nehira la-arim yatzra be'ayot khevratiyot", None, 5),
        (3930, 'הרציונליזם מייחס חשיבות עליונה לשכל', 'Рационализм придаёт высшее значение разуму', 'ha-ratzionalizm meyakhes khashivut eliona la-sekhel', None, 5),
        (4000, 'הרלטיביזם התרבותי מעורר דיון סוער', 'Культурный релятивизм вызывает бурную дискуссию', "ha-relativizm ha-tarbuti me'orer diyun so'er", None, 5),
        (4070, 'הדטרמיניזם שולל את חופש הרצון', 'Детерминизм отрицает свободу воли', 'ha-determinizm sholel et khofesh ha-ratzon', None, 5),
        (4140, 'הפסיכואנליזה של פרויד שינתה את ההבנה העצמית', 'Психоанализ Фрейда изменил самопонимание', "ha-psikho'analiza shel froid shinta et ha-havana ha-atzmit", None, 5),
        (4210, 'הסמיוטיקה מנתחת מערכות סימנים', 'Семиотика анализирует системы знаков', "ha-semiotika menatkhat ma'arkhot simanim", None, 5),
        (4280, 'המורפולוגיה חוקרת את מבנה המילים', 'Морфология исследует структуру слов', 'ha-morfologia khokeret et mivne ha-milim', None, 5),
        (4350, 'הפרוזה של עגנון מאופיינת בסגנון ייחודי', 'Проза Агнона отличается уникальным стилем', "ha-proza shel agnon me'ufyenet be-signon yikhudi", None, 5),
        (4420, 'האנתרופולוגיה חוקרת תרבויות אנושיות', 'Антропология изучает человеческие культуры', "ha-antropologia khokeret tarbu'ot enoshiyot", None, 5),
        (4490, 'המעבר מהמודרניזם לפוסט-מודרניזם משמעותי', 'Переход от модернизма к постмодернизму значителен', "ha-ma'avar me-ha-modernizm la-post-modernizm mashma'uti", None, 5),
        (4560, 'ההיפותזה לא אושרה באופן סטטיסטי', 'Гипотеза не подтверждена статистически', 'ha-hipoteza lo ushra be-ofen statisty', None, 5),
        (4630, 'הטענה הפילוסופית דורשת ביסוס לוגי', 'Философское утверждение требует логического обоснования', "ha-ta'ana ha-filosofit doreshet bisus logi", None, 5),
        (4700, 'הנראטולוגיה מנתחת מבני סיפור', 'Нарратология анализирует структуры повествования', 'ha-narratologia menatkhat mivnei sipur', None, 5),
        (4770, 'הדוגמטיות מונעת חשיבה ביקורתית', 'Догматизм препятствует критическому мышлению', "ha-dogmatiyut mona'at khashiva bikortit", None, 5),
        (4840, 'הסכולסטיקה שלטה בפילוסופיה של ימי הביניים', 'Схоластика доминировала в философии Средневековья', 'ha-skholastika shalta ba-filosofia shel ymei ha-beinayim', None, 5),
        (4910, 'הבינתחומיות מאפשרת מחקר מקיף יותר', 'Междисциплинарность позволяет более комплексное исследование', "ha-bein-tkhumiyut me'afsheret mekhkar makif yoter", None, 5),
        (4980, 'המטאנרטיב מספר על עצמו כסיפור', 'Метанарратив рассказывает о себе как о повествовании', 'ha-metanarativ mesaper al atzmo ke-sipur', None, 5),
        (5050, 'הרב-קוליות בספרות מייצגת מגוון דעות', 'Полифония в литературе представляет разнообразие мнений', "ha-rav-koliyut ba-sifrut meyatzget migvan de'ot", None, 5),
        (5120, 'האינדוקציה עוברת מן הפרט אל הכלל', 'Индукция идёт от частного к общему', 'ha-induktzya overet min ha-prat el ha-klal', None, 5),
        (5190, 'הדדוקציה עוברת מן הכלל אל הפרט', 'Дедукция идёт от общего к частному', 'ha-deduktzya overet min ha-klal el ha-prat', None, 5),
        (5260, 'הסילוגיזם הוא צורה בסיסית של היסק', 'Силлогизм — базовая форма умозаключения', 'ha-silogizm hu tzura bsisit shel hesek', None, 5),
        (5330, 'האנלוגיה מסייעת להבנת מושגים מופשטים', 'Аналогия помогает понять абстрактные понятия', 'ha-analogia mesayaat le-havanat musagim mufshatim', None, 5),
        (5400, 'הרדוקציוניזם מפשט תופעות מורכבות', 'Редукционизм упрощает сложные явления', "ha-reduktzionizm mefshet tofa'ot murkavot", None, 5),
        (5470, 'ההוליזם מדגיש את השלם מעבר לחלקיו', 'Холизм подчёркивает целое сверх его частей', "ha-holizm madgish et ha-shalem me'ever la-khalakav", None, 5),
        (5540, 'הרפלקסיביות היא מאפיין של מחקר איכותני', 'Рефлексивность — характеристика качественного исследования', "ha-refleksiviyut hi me'afen shel mekhkar ekhutani", None, 5),
        (5610, 'ההפשטה מאפשרת הכללה תיאורטית', 'Абстрагирование позволяет теоретическое обобщение', "ha-hafshata me'afsheret hakhlala te'oretit", None, 5),
        (5680, 'הפנומן מתואר מנקודת מבט סובייקטיבית', 'Феномен описывается с субъективной точки зрения', "ha-fenomen metu'ar mi-nekudat mabat subyektivit", None, 5),
        (5750, 'הקונטקסט ההיסטורי חיוני להבנת הטקסט', 'Исторический контекст необходим для понимания текста', 'ha-kontekst ha-histori khiyuni le-havanat ha-tekst', None, 5),
        (1580, 'השיח הציבורי משקף מתחים חברתיים', 'Общественный дискурс отражает социальные напряжения', 'ha-siakh ha-tziburi meshakef metakhim khevratiyim', None, 5),
        (1650, 'הביקורת הספרותית מעניקה פרשנות לטקסט', 'Литературная критика даёт интерпретацию текста', "ha-bikoret ha-sifrutit ma'anika parshanut la-tekst", None, 5),
        (1720, 'הפילוסופיה האנליטית מדגישה בהירות לשונית', 'Аналитическая философия подчёркивает языковую ясность', 'ha-filosofia ha-analitit madgisha behirut leshonit', None, 5),
        (1790, 'הסוציולינגוויסטיקה חוקרת שפה בהקשר חברתי', 'Социолингвистика изучает язык в социальном контексте', 'ha-sotziolingvistika khokeret safa be-heksher khevrati', None, 5),
        (1860, 'האינטרפרטציה תלויה ברקע התרבותי של הקורא', 'Интерпретация зависит от культурного фона читателя', 'ha-interpretatzya tluya ba-reka ha-tarbuti shel ha-kore', None, 5),
        (1930, 'הקונצפטואליזם באמנות מעדיף רעיון על ביצוע', 'Концептуализм в искусстве предпочитает идею исполнению', "ha-kontzeptualizm ba-omanut ma'adif ra'ayon al bitzu'a", None, 5),
        (2000, 'ההיסטוריציזם טוען שכל ידיעה מותנית היסטורית', 'Историцизм утверждает, что всё знание исторически обусловлено', "ha-historitzizm to'en she-kol yedi'a mutnit historit", None, 5),
        (2070, 'הסינכרוניה בלשנית בוחנת שפה ברגע נתון', 'Лингвистическая синхрония изучает язык в данный момент', 'ha-sinkhroniya balshenit bokhenet safa be-rega natun', None, 5),
        (2140, 'הדיאכרוניה בוחנת התפתחות שפה לאורך זמן', 'Диахрония изучает развитие языка во времени', 'ha-diakhroniya bokhenet hitpathut safa le-orekh zman', None, 5),
        (6000, 'הפואטיקה של אריסטו השפיעה על הביקורת הספרותית', 'Поэтика Аристотеля повлияла на литературную критику', "ha-po'etika shel aristo hishpi'a al ha-bikoret ha-sifrutit", None, 5),
        (6100, 'הלקסיקוגרפיה עוסקת בעריכת מילונים', 'Лексикография занимается составлением словарей', 'ha-leksikografiya oseket ba-arikhat millonim', None, 5),
        (6200, 'הפילולוגיה חוקרת טקסטים עתיקים', 'Филология исследует древние тексты', 'ha-filologia khokeret tekstim atikim', None, 5),
        (6300, 'האטימולוגיה חוקרת מקורות מילים', 'Этимология исследует происхождение слов', 'ha-etimologia khokeret mekorot milim', None, 5),
        (6400, 'הדיגלוסיה מאפיינת חברות רבות', 'Диглоссия характерна для многих обществ', "ha-diglosia me'afyenet khavarot rabot", None, 5),
        (6500, 'הפוליסמיה היא ריבוי משמעויות של מילה', 'Полисемия — множественность значений слова', "ha-polisemiya hi ribuy mashma'uyot shel mila", None, 5),
        (6600, 'הסינתזה משלבת רעיונות מנוגדים', 'Синтез объединяет противоположные идеи', "ha-sinteza meshalevet ra'ayonot menugadim", None, 5),
        (6700, 'האנטינומיה מציגה סתירה בין עקרונות', 'Антиномия представляет противоречие между принципами', 'ha-antinomiya matziga stira bein ekronot', None, 5),
        (6800, 'הטלאולוגיה מפרשת תופעות לפי תכליתן', 'Телеология интерпретирует явления по их цели', "ha-teleologia mefarshet tofa'ot lefi takhlitan", None, 5),
        (1650, 'השיח הפוסט-קולוניאלי בוחן יחסי כוח', 'Постколониальный дискурс изучает отношения власти', 'ha-siakh ha-post-koloniali bokhen yakhasei koakh', None, 6),
        (1750, 'הדרשנות הרבנית פיתחה שיטות פרשנות ייחודיות', 'Раввинская проповедь развила уникальные методы интерпретации', 'ha-darshanut ha-rabanit pitakha shitot parshanut yikhudiyot', None, 6),
        (1850, 'האפוריזם מרכז חוכמה במילים מעטות', 'Афоризм концентрирует мудрость в нескольких словах', "ha-aforizm merakez khokhma be-milim me'atot", None, 6),
        (1950, 'הפאתוס הרטורי מכוון להשפיע רגשית', 'Риторический пафос направлен на эмоциональное воздействие', "ha-patos ha-retori mekhaven lehashpi'a rigsheet", None, 6),
        (2050, 'הלוגוס מייצג את היסוד הרציונלי בשכנוע', 'Логос представляет рациональный элемент убеждения', "ha-logos meyatzeg et ha-yesod ha-ratzionali ba-shikhnu'a", None, 6),
        (2150, 'האתוס של הדובר משפיע על האמינות שלו', 'Этос говорящего влияет на его достоверность', "ha-etos shel ha-dover mashpi'a al ha-aminut shelo", None, 6),
        (2250, 'המליצה הבלתי נשלטת פוגעת באותנטיות', 'Неконтролируемая высокопарность вредит аутентичности', "ha-melitza ha-bilti nishletet poga'at ba-otentiyut", None, 6),
        (2350, 'הליטוטס מביע תוכן חיובי בניסוח שלילי', 'Литота выражает позитивное содержание в отрицательной формулировке', "ha-litotes mabi'a tokhen khiyuvi be-nisuakh shlili", None, 6),
        (2450, 'האוקסימורון מחבר מושגים סותרים', 'Оксиморон соединяет противоречивые понятия', 'ha-oksimoron mekhaber musagim sotrim', None, 6),
        (2550, 'הכיאזמוס יוצר הקבלה מוצלבת', 'Хиазм создаёт перекрёстную параллель', 'ha-khiazmus yotzer hakbala mutzlevet', None, 6),
        (2650, 'האנאפורה חוזרת על מילה בתחילת משפטים', 'Анафора повторяет слово в начале предложений', 'ha-anafora khozeret al mila bi-tkhilat mishpatim', None, 6),
        (2750, 'הקתרזיס הוא טיהור רגשי דרך אמנות', 'Катарсис — это эмоциональное очищение через искусство', 'ha-katarsis hu tihur rigshi derekh omanut', None, 6),
        (2850, 'הסינקרטיזם משלב אלמנטים מתרבויות שונות', 'Синкретизм объединяет элементы разных культур', "ha-sinkretizm meshalev elementim mi-tarbu'ot shonot", None, 6),
        (2950, 'הפליאדה הצרפתית השפיעה על הספרות האירופית', 'Французская Плеяда повлияла на европейскую литературу', "ha-ple'ada ha-tzarfatit hishpi'a al ha-sifrut ha-eropit", None, 6),
        (3050, 'הפרוסודיה מנתחת קצב וטעם בשפה', 'Просодия анализирует ритм и ударение в речи', "ha-prosodia menatkhat ketzev ve-ta'am ba-safa", None, 6),
        (3150, 'הגראפולוגיה טוענת לקשר בין כתב יד לאישיות', 'Графология утверждает о связи между почерком и личностью', "ha-grafologia to'enet le-kesher bein ktav yad le-ishiyut", None, 6),
        (3350, 'הנאו-קלאסיציזם שאב השראה מיוון ורומא', 'Неоклассицизм черпал вдохновение из Греции и Рима', "ha-neo-klasitzizm sha'av hash'ra'a mi-yavan ve-roma", None, 6),
        (3550, 'הדיסטופיה מתארת חברה עתידית מפחידה', 'Антиутопия описывает пугающее будущее общество', "ha-distopia meta'eret khevra atidiy mafkhida", None, 6),
        (3750, 'האקספרסיוניזם מבטא רגשות פנימיים עזים', 'Экспрессионизм выражает сильные внутренние чувства', 'ha-ekspresyonizm mevate regashot pnimiyim azim', None, 6),
        (3950, 'הסוריאליזם מאתגר את גבולות המציאות', 'Сюрреализм бросает вызов границам реальности', "ha-suriyalizm me'atger et gvulot ha-metzi'ut", None, 6),
        (4150, 'האבסורד בספרות מציג את חוסר המשמעות', 'Абсурд в литературе представляет бессмысленность', "ha-absurd ba-sifrut matziy et khoser ha-mashma'ut", None, 6),
        (4350, 'האלגוריזציה היא תהליך הפיכת טקסט לאלגוריה', 'Аллегоризация — процесс превращения текста в аллегорию', 'ha-alegorizatzya hi takhlit hafikhat tekst le-alegorya', None, 6),
        (4550, 'הפרוטוקול הדיפלומטי קובע כללי התנהגות', 'Дипломатический протокол устанавливает правила поведения', "ha-protokol ha-diplomati kove'a klalei hitnagut", None, 6),
        (4750, 'הריטואל מעניק משמעות לאירועי חיים', 'Ритуал придаёт смысл жизненным событиям', "ha-ritu'al ma'anik mashma'ut le-iru'ei khayim", None, 6),
        (4950, 'ההגות היהודית מציעה מגוון גישות לאתיקה', 'Еврейская мысль предлагает разнообразие подходов к этике', "ha-hagut ha-yehudit metzi'a migvan gishot le-etika", None, 6),
        (5150, 'הפילוסופיה האנליטית מנתחת מושגים בדייקנות', 'Аналитическая философия анализирует понятия с точностью', 'ha-filosofia ha-analitit menatkhat musagim be-daykanut', None, 6),
        (5350, 'האינטלקטואליזם מייחס חשיבות עליונה לשכל', 'Интеллектуализм придаёт высшее значение разуму', "ha-intelektu'alizm meyakhes khashivut eliona la-sekhel", None, 6),
        (5550, 'ההומניזם מציב את האדם במרכז', 'Гуманизм ставит человека в центр', 'ha-humanizm matziv et ha-adam ba-merkaz', None, 6),
        (5750, 'הסקולריזציה היא תהליך חילון החברה', 'Секуляризация — процесс обмирщения общества', 'ha-sekularizatzya hi takhlit khilun ha-khevra', None, 6),
        (5950, 'הפרטיקולריזם מדגיש את הייחודיות של כל תרבות', 'Партикуляризм подчёркивает уникальность каждой культуры', 'ha-partikularizm madgish et ha-yikhudiyut shel kol tarbut', None, 6),
        (6150, 'האוניברסליזם טוען לערכים משותפים לכל האנושות', 'Универсализм утверждает об общих ценностях для всего человечества', "ha-universalizm to'en la-arakhim meshutafim le-khol ha-enoshut", None, 6),
        (6350, 'הנורמטיביות קובעת מה נחשב לנכון ולראוי', 'Нормативность определяет, что считается правильным и должным', "ha-normativiyut kova'at ma nekhshav le-nakhon u-le-ra'uy", None, 6),
        (6550, 'הדיסקורס המשפטי מאופיין בדיוק טרמינולוגי', 'Юридический дискурс характеризуется терминологической точностью', "ha-diskurs ha-mishpati me'ufyan be-diyuk terminologi", None, 6),
        (6750, 'הרטוריקה הפוליטית משתמשת באמצעי שכנוע מגוונים', 'Политическая риторика использует разнообразные средства убеждения', "ha-retorika ha-politit mishtameshet be-emtza'ei shikhnu'a megavanim", None, 6),
        (6950, 'הפילולוגיה ההשוואתית חוקרת קשרי שפות', 'Сравнительная филология исследует связи между языками', "ha-filologia ha-hashva'atit khokeret kishrei safot", None, 6),
        (7050, 'הסמנטיקה הקוגניטיבית בוחנת קשר בין שפה לחשיבה', 'Когнитивная семантика изучает связь языка и мышления', 'ha-semantika ha-kognitivit bokhenet kesher bein safa le-khashiva', None, 6),
        (7150, 'הפרגמטיזם האמריקאי שינה את הפילוסופיה', 'Американский прагматизм изменил философию', "ha-pragmatizm ha-amerik'i shina et ha-filosofia", None, 6),
        (7250, 'הניהיליזם שולל כל ערך ומשמעות', 'Нигилизм отрицает всякую ценность и смысл', "ha-nihilizm sholel kol erekh u-mashma'ut", None, 6),
        (7350, 'הסטואיציזם מציע שליטה עצמית כמפתח לאושר', 'Стоицизм предлагает самоконтроль как ключ к счастью', "ha-stoitzizm metzi'a shlita atzmit ke-mafte'akh le-osher", None, 6),
        (7450, 'האפיקוריאניזם מזהה אושר עם היעדר סבל', 'Эпикуреизм отождествляет счастье с отсутствием страдания', "ha-epikuri'anizm mezahe osher im he'ader sevel", None, 6),
        (7550, 'הסקפטיציזם מטיל ספק ביכולת להשיג ידע מוחלט', 'Скептицизм ставит под сомнение возможность достижения абсолютного знания', 'ha-skeptitzizm matil safek ba-yekholet lehasig yeda mukhlat', None, 6),
        (7650, 'הפוזיטיביזם מכיר רק בידע אמפירי מוכח', 'Позитивизм признаёт только доказанное эмпирическое знание', 'ha-pozitivizm makir rak be-yeda empiri mukhakh', None, 6),
        (7750, 'הנאו-פלטוניזם שילב מסורות פילוסופיות שונות', 'Неоплатонизм объединил разные философские традиции', 'ha-neo-platonizm shilev masorot filosofiyot shonot', None, 6),
        (7850, 'המיסטיקה היהודית מציעה דרכי התקרבות לאלוהי', 'Еврейская мистика предлагает пути приближения к Божественному', "ha-mistika ha-yehudit metzi'a darkhei hitkarvut la-elohi", None, 6),
        (7950, 'הפנתאיזם מזהה את האלוהי עם הטבע', 'Пантеизм отождествляет Божественное с природой', "ha-pante'izm mezahe et ha-elohi im ha-teva", None, 6),
        (8050, 'הטרנסצנדנציה מתייחסת למה שמעבר לניסיון', 'Трансценденция относится к тому, что за пределами опыта', "ha-transtendentsya mityakheset le-ma she-me'ever la-nisayon", None, 6),
        # Extra L4 (+11)
        (4600, 'הבורסה רשמה עליות חדות היום', 'Биржа зафиксировала резкий рост сегодня', 'ha-bursa rashma aliyot khadot ha-yom', None, 4),
        (4650, 'שר האוצר הציג תוכנית כלכלית', 'Министр финансов представил экономический план', "sar ha-otzer hetziy tokhnit kalkalit", None, 4),
        (4700, 'הפרקליט הגיש ערעור על פסק הדין', 'Адвокат подал апелляцию на приговор', "ha-praklin higish ir'ur al psak ha-din", None, 4),
        (4750, 'הוועדה בחנה את ההצעה לעומק', 'Комиссия тщательно изучила предложение', "ha-va'ada bakhna et ha-hatza'a le-omek", None, 4),
        (4800, 'שיעור האבטלה ירד ברבעון האחרון', 'Уровень безработицы снизился в последнем квартале', "shi'ur ha-avtala yarad ba-riv'on ha-akharon", None, 4),
        (4850, 'הפרופסור מינה עוזר מחקר חדש', 'Профессор назначил нового научного ассистента', 'ha-profesor mina ozer mekhkar khadash', None, 4),
        (4900, 'הצו השיפוטי נכנס לתוקף מיידי', 'Судебный ордер вступил в силу немедленно', 'ha-tzav ha-shifuti nikhnas le-tokef miyadi', None, 4),
        (4950, 'הדוח ביקורתי כלפי מדיניות הממשלה', 'Отчёт критичен по отношению к политике правительства', "ha-do'akh bikurti klapei mediniyut ha-memshala", None, 4),
        (5000, 'המשקיעים הזרים הגדילו את נוכחותם בשוק', 'Иностранные инвесторы увеличили присутствие на рынке', "ha-mashki'im ha-zarim higdilu et nokhekhtam ba-shuk", None, 4),
        (5050, 'החקיקה החדשה מגבילה את שעות העבודה', 'Новое законодательство ограничивает рабочие часы', "ha-khakika ha-khadasha magbila et she'ot ha-avoda", None, 4),
        (5100, 'הגירעון התקציבי הגיע לשיא חדש', 'Бюджетный дефицит достиг нового рекорда', "ha-gira'on ha-taktzivi higia le-si khadash", None, 4),
        # Extra L5 (+27)
        (5820, 'הפילוסוף הקדם-סוקרטי חקר את מקור היקום', 'Досократический философ исследовал происхождение Вселенной', "ha-filosof ha-kedem-sokrati khakar et makor ha-yekum", None, 5),
        (5890, 'הדיכוטומיה בין גוף לנפש העסיקה הוגים רבים', 'Дихотомия тела и души занимала многих мыслителей', "ha-dikhotomiya bein guf le-nefesh he'esika hogim rabim", None, 5),
        (5960, 'הסמיוטיקה התרבותית מנתחת סמלים בחברה', 'Культурная семиотика анализирует символы в обществе', "ha-semiotika ha-tarbutit menatkhat smalim ba-khevra", None, 5),
        (6030, 'הפרספקטיביזם טוען שאין נקודת מבט יחידה', 'Перспективизм утверждает, что нет единственной точки зрения', "ha-perspektivizm to'en she-ein nekudat mabat yekhida", None, 5),
        (6100, 'ההיסטוריוגרפיה החדשה מערערת על סיפורים מסורתיים', 'Новая историография подвергает сомнению традиционные нарративы', "ha-historiografiya ha-khadasha me'ar'eret al sipurim masortiyim", None, 5),
        (6170, 'הפונטיקה מתארת כיצד מופקים צלילי שפה', 'Фонетика описывает, как производятся звуки речи', "ha-fonetika meta'eret keitzad mufakim tzlilei safa", None, 5),
        (6240, 'המקרו-סוציולוגיה בוחנת מבנים חברתיים רחבים', 'Макросоциология изучает широкие социальные структуры', "ha-makro-sotziologia bokhenet mivnim khevratiyim rekhavim", None, 5),
        (6310, 'האנליזה הנרטיבית חושפת מבני סיפור נסתרים', 'Нарративный анализ выявляет скрытые структуры повествования', "ha-analiza ha-narrativit khosefet mivnei sipur nistarim", None, 5),
        (6380, 'הפנומנולוגיה מבקשת לתאר את החוויה כפי שהיא', 'Феноменология стремится описать опыт как он есть', "ha-fenomenologia mevakeshet leta'er et ha-khavaya kfi she-hi", None, 5),
        (6450, 'הקוגניטיביזם מדגיש תהליכים מנטליים', 'Когнитивизм подчёркивает ментальные процессы', 'ha-kognitivizm madgish takhalikhim mentaliyim', None, 5),
        (6520, 'הביהביוריזם מתמקד בהתנהגות הנצפית', 'Бихевиоризм фокусируется на наблюдаемом поведении', 'ha-bihavyorizm mitmaker ba-hitnagut ha-nitzpet', None, 5),
        (6590, 'הגשטלט מדגיש את תפיסת השלם', 'Гештальт подчёркивает восприятие целого', "ha-geshalt madgish et tfisat ha-shalem", None, 5),
        (6660, 'הסטרוקטורליזם מחפש חוקיות עמוקה במערכות', 'Структурализм ищет глубокую закономерность в системах', "ha-strukturalizm mekhapes khukiyut amuka be-ma'arakhot", None, 5),
        (6730, 'הפוסט-סטרוקטורליזם מערער על קטגוריות קבועות', 'Постструктурализм подвергает сомнению фиксированные категории', "ha-post-strukturalizm me'ar'er al kategoriyot kvu'ot", None, 5),
        (1570, 'הנוירולינגוויסטיקה חוקרת שפה במוח', 'Нейролингвистика изучает язык в мозге', 'ha-nerolingvistika khokeret safa ba-mo\'akh', None, 5),
        (1640, 'המטא-אתיקה דנה בטבע המושגים המוסריים', 'Метаэтика рассуждает о природе моральных понятий', "ha-meta-etika dana be-teva ha-musagim ha-musariyim", None, 5),
        (1710, 'הפרשנות ההרמנויטית מתחשבת בהקשר ההיסטורי', 'Герменевтическая интерпретация учитывает исторический контекст', "ha-parshanut ha-hermeneutit mitkashevet ba-heksher ha-histori", None, 5),
        (1780, 'הסינכרטיזם הדתי מאפיין תרבויות מפגש', 'Религиозный синкретизм характерен для контактных культур', "ha-sinkretizm ha-dati me'afyen tarbuyot mifgash", None, 5),
        (1850, 'הדיסקורס הביקורתי חושף מבני כוח סמויים', 'Критический дискурс выявляет скрытые структуры власти', "ha-diskurs ha-bikurti khoshef mivnei koakh smuyim", None, 5),
        (1920, 'הקונסטרוקטיביזם טוען שמציאות נבנית חברתית', 'Конструктивизм утверждает, что реальность конструируется социально', "ha-konstruktivizm to'en she-metzi'ut nivneit khevratit", None, 5),
        (1990, 'הפרגמטיקה הלשונית בוחנת משמעות בשימוש', 'Лингвистическая прагматика изучает значение в употреблении', "ha-pragmatika ha-leshonit bokhenet mashma'ut be-shimush", None, 5),
        (2060, 'הטיפולוגיה הלשונית משווה שפות שונות', 'Лингвистическая типология сравнивает разные языки', "ha-tipologia ha-leshonit mashva safot shonot", None, 5),
        (2130, 'הקורפוס הלשוני משמש למחקר אמפירי', 'Лингвистический корпус служит для эмпирического исследования', "ha-korpus ha-leshoni meshamesh le-mekhkar empiri", None, 5),
        (2200, 'הלקסיקולוגיה חוקרת את מבנה אוצר המילים', 'Лексикология исследует структуру словарного запаса', "ha-leksikologia khokeret et mivne otzar ha-milim", None, 5),
        (2270, 'האנתרופולוגיה הלשונית חוקרת שפה בהקשר תרבותי', 'Лингвистическая антропология изучает язык в культурном контексте', "ha-antropologia ha-leshonit khokeret safa be-heksher tarbuti", None, 5),
        (2340, 'הסגנון האקדמי מחייב ניסוח מדויק ועניני', 'Академический стиль требует точной и деловой формулировки', "ha-signon ha-akademi mekhayev nisuakh meduyak ve-inyani", None, 5),
        (2410, 'הביו-לינגוויסטיקה חוקרת בסיס ביולוגי לשפה', 'Биолингвистика исследует биологическую основу языка', "ha-bio-lingvistika khokeret basis biologi le-safa", None, 5),
        # Extra L6 (+2)
        (7200, 'הנומינליזם שולל קיום של אוניברסלים', 'Номинализм отрицает существование универсалий', "ha-nominalizm sholel kiyum shel universalim", None, 6),
        (7400, 'האסכטולוגיה עוסקת בתורת אחרית הימים', 'Эсхатология занимается учением о конце времён', "ha-eskhatologia oseket be-torat akharit ha-yamim", None, 6),
    ]
    op.bulk_insert(t, [
        {"word_id": r[0], "hebrew": r[1], "translation_ru": r[2],
         "transliteration": r[3], "audio_url": r[4], "level_id": r[5]}
        for r in rows
    ])
    op.execute("SELECT setval('example_sentences_id_seq', GREATEST((SELECT COALESCE(MAX(id),0) FROM example_sentences), 1))")

def downgrade():
    op.execute("DELETE FROM example_sentences WHERE id > 1671")
    op.execute("SELECT setval('example_sentences_id_seq', GREATEST((SELECT COALESCE(MAX(id),0) FROM example_sentences), 1))")
